import * as z from "zod";
import { getIeltsReadingQuestionType, type IeltsReadingQuestionType } from "@/lib/admin/ielts-reading-question-types";

// ============================================================
// Bulk "import a full reading test" format.
//
// One JSON document = one lesson (a reading test) with N passages,
// each with its own paragraphs and questions. This lets an admin
// paste a whole test (generated by an LLM, following the schema
// documented on the import page) instead of clicking through the
// question-set admin dozens of times.
//
// Cloze-style groups (a shared paragraph with several numbered
// blanks — IELTS Summary/Sentence/Note Completion) are expanded into
// one saved question per blank, matching how every other question
// type here is stored: one questions row per gradable item.
// ============================================================

const ieltsTypeKeys = z.enum([
  "true_false_not_given",
  "yes_no_not_given",
  "multiple_choice",
  "matching_headings",
  "matching_information",
  "matching_features",
  "sentence_completion",
  "summary_completion",
  "short_answer",
]);

const choiceQuestionSchema = z.object({
  kind: z.literal("choice"),
  ieltsType: ieltsTypeKeys,
  prompt: z.string().trim().min(1),
  options: z.array(z.string().trim().min(1)).min(2).optional(),
  correctOption: z.string().trim().min(1),
  marks: z.number().positive().optional(),
  explanation: z.string().trim().min(1).optional(),
});

const matchingQuestionSchema = z.object({
  kind: z.literal("matching"),
  ieltsType: ieltsTypeKeys,
  prompt: z.string().trim().min(1),
  pairs: z.array(z.object({ left: z.string().trim().min(1), right: z.string().trim().min(1) })).min(1),
  marks: z.number().positive().optional(),
  explanation: z.string().trim().min(1).optional(),
});

const fillQuestionSchema = z.object({
  kind: z.literal("fill"),
  ieltsType: ieltsTypeKeys,
  prompt: z.string().trim().min(1),
  correctAnswer: z.string().trim().min(1),
  marks: z.number().positive().optional(),
  explanation: z.string().trim().min(1).optional(),
});

const clozeFillQuestionSchema = z.object({
  kind: z.literal("cloze_fill"),
  ieltsType: ieltsTypeKeys,
  instructions: z.string().trim().min(1).optional(),
  text: z.string().trim().min(1),
  answers: z.record(z.string(), z.string().trim().min(1)),
  marks: z.number().positive().optional(),
});

const clozeChoiceQuestionSchema = z.object({
  kind: z.literal("cloze_choice"),
  ieltsType: ieltsTypeKeys,
  instructions: z.string().trim().min(1).optional(),
  text: z.string().trim().min(1),
  wordBank: z.array(z.string().trim().min(1)).min(2),
  answers: z.record(z.string(), z.string().trim().min(1)),
  marks: z.number().positive().optional(),
});

const importQuestionSchema = z.discriminatedUnion("kind", [
  choiceQuestionSchema,
  matchingQuestionSchema,
  fillQuestionSchema,
  clozeFillQuestionSchema,
  clozeChoiceQuestionSchema,
]);

export type ImportQuestion = z.infer<typeof importQuestionSchema>;

const importPassageSchema = z.object({
  passageNumber: z.number().int().min(1).max(20),
  title: z.string().trim().min(1),
  paragraphs: z
    .array(
      z.object({
        label: z.string().trim().max(20).nullable().optional(),
        text: z.string().trim().min(1),
      }),
    )
    .min(1),
  questions: z.array(importQuestionSchema).min(1),
});

export type ImportPassage = z.infer<typeof importPassageSchema>;

export const readingTestImportSchema = z.object({
  lesson: z.object({
    title: z.string().trim().min(1).max(200),
    slug: z
      .string()
      .trim()
      .toLowerCase()
      .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, "Use lowercase letters, numbers, and hyphens only."),
    excerpt: z.string().trim().max(500).optional(),
    difficulty: z.enum(["beginner", "intermediate", "advanced"]).optional(),
    estimatedMinutes: z.number().int().positive().max(600).optional(),
    seoTitle: z.string().trim().max(200).optional(),
    seoDescription: z.string().trim().max(300).optional(),
  }),
  passages: z.array(importPassageSchema).min(1).max(10),
});

export type ReadingTestImport = z.infer<typeof readingTestImportSchema>;

// --- Expansion: turns the raw import shape into flat, ready-to-insert
// question specs, splitting cloze groups into one entry per blank. ---

export type ExpandedQuestion = {
  prompt: string;
  ieltsType: string;
  marks: number;
  explanation: string | null;
} & (
  | { kind: "choice"; options: string[]; correctOption: string }
  | { kind: "matching"; pairs: { left: string; right: string }[] }
  | { kind: "fill"; correctAnswer: string }
);

const CLOZE_TOKEN = /\[\[(\d+)\]\]/g;

function isSentenceEnd(char: string) {
  return char === "." || char === "!" || char === "?";
}

// Isolates each [[N]] blank's own sentence out of a shared cloze
// paragraph, replacing every blank marker (this one and any others
// that happen to share the sentence) with "___" — good enough for a
// self-contained per-question prompt; admins can hand-edit the rare
// two-blanks-one-sentence case afterward in the question editor.
function splitCloze(text: string): { number: number; prompt: string }[] {
  const matches = [...text.matchAll(CLOZE_TOKEN)];
  return matches.map((match) => {
    const number = Number(match[1]);
    const start = match.index ?? 0;
    const end = start + match[0].length;

    let left = start;
    while (left > 0 && !isSentenceEnd(text[left - 1])) left--;
    let right = end;
    while (right < text.length && !isSentenceEnd(text[right])) right++;
    if (right < text.length) right++;

    const prompt = text.slice(left, right).trim().replace(CLOZE_TOKEN, "___");
    return { number, prompt };
  });
}

export type ExpansionError = { passageNumber: number; message: string };

export function expandPassageQuestions(
  passage: ImportPassage,
): { questions: ExpandedQuestion[]; errors: ExpansionError[] } {
  const questions: ExpandedQuestion[] = [];
  const errors: ExpansionError[] = [];

  const fail = (message: string) => errors.push({ passageNumber: passage.passageNumber, message });

  for (const q of passage.questions) {
    const preset: IeltsReadingQuestionType | null = getIeltsReadingQuestionType(q.ieltsType);
    if (!preset) {
      fail(`Unknown ieltsType "${q.ieltsType}".`);
      continue;
    }

    if (q.kind === "choice") {
      const options = q.options ?? preset.presetOptions;
      if (!options) {
        fail(`"${q.prompt.slice(0, 60)}" needs options (no preset exists for ${q.ieltsType}).`);
        continue;
      }
      const matchesCorrect = options.some(
        (o) => o.trim().toLowerCase() === q.correctOption.trim().toLowerCase(),
      );
      if (!matchesCorrect) {
        fail(`"${q.prompt.slice(0, 60)}": correctOption "${q.correctOption}" isn't one of the options.`);
        continue;
      }
      questions.push({
        prompt: q.prompt,
        ieltsType: q.ieltsType,
        marks: q.marks ?? 1,
        explanation: q.explanation ?? null,
        kind: "choice",
        options,
        correctOption: q.correctOption,
      });
    } else if (q.kind === "matching") {
      questions.push({
        prompt: q.prompt,
        ieltsType: q.ieltsType,
        marks: q.marks ?? q.pairs.length,
        explanation: q.explanation ?? null,
        kind: "matching",
        pairs: q.pairs,
      });
    } else if (q.kind === "fill") {
      questions.push({
        prompt: q.prompt,
        ieltsType: q.ieltsType,
        marks: q.marks ?? 1,
        explanation: q.explanation ?? null,
        kind: "fill",
        correctAnswer: q.correctAnswer,
      });
    } else if (q.kind === "cloze_fill") {
      const blanks = splitCloze(q.text);
      if (blanks.length === 0) {
        fail(`A cloze_fill block has no [[N]] blanks: "${q.text.slice(0, 60)}..."`);
        continue;
      }
      for (const blank of blanks) {
        const answer = q.answers[String(blank.number)];
        if (!answer) {
          fail(`Cloze blank [[${blank.number}]] has no matching entry in "answers".`);
          continue;
        }
        questions.push({
          prompt: blank.prompt,
          ieltsType: q.ieltsType,
          marks: q.marks ?? 1,
          explanation: q.instructions ?? null,
          kind: "fill",
          correctAnswer: answer,
        });
      }
    } else if (q.kind === "cloze_choice") {
      const blanks = splitCloze(q.text);
      if (blanks.length === 0) {
        fail(`A cloze_choice block has no [[N]] blanks: "${q.text.slice(0, 60)}..."`);
        continue;
      }
      for (const blank of blanks) {
        const answer = q.answers[String(blank.number)];
        if (!answer) {
          fail(`Cloze blank [[${blank.number}]] has no matching entry in "answers".`);
          continue;
        }
        if (!q.wordBank.some((w) => w.trim().toLowerCase() === answer.trim().toLowerCase())) {
          fail(`Answer "${answer}" for blank [[${blank.number}]] isn't in the wordBank.`);
          continue;
        }
        questions.push({
          prompt: blank.prompt,
          ieltsType: q.ieltsType,
          marks: q.marks ?? 1,
          explanation: q.instructions ?? null,
          kind: "choice",
          options: q.wordBank,
          correctOption: answer,
        });
      }
    }
  }

  return { questions, errors };
}
