-- ============================================================
-- 024_ielts_vocabulary_words_0_199.sql
-- Content batch: IELTS Band 8 vocabulary words 0-199,
-- transcribed from "1000 Essential Words for Band 8" (word, part of
-- speech, definition, and example extracted from the source; Bangla
-- meanings authored fresh, since the PDF's own Bangla text layer is
-- corrupted at the font level -- see migration notes).
-- ============================================================

do $$
declare
  v_education uuid;
  v_technology uuid;
  v_environment uuid;
  v_health_and_lifestyle uuid;
  v_crime_and_law uuid;
begin
  select cn.id into v_education from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'education';
  select cn.id into v_technology from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'technology';
  select cn.id into v_environment from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'environment';
  select cn.id into v_health_and_lifestyle from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'health-and-lifestyle';
  select cn.id into v_crime_and_law from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'crime-and-law';

  insert into vocabulary (word, part_of_speech, bangla_meaning, english_definition, example_sentence, difficulty, node_id) values
    ('curriculum', 'noun', 'পাঠ্যক্রম', 'the subjects and content taught in a course', 'The curriculum places too much emphasis on memorisation rather than understanding.', 'advanced', v_education),
    ('rote learning', 'noun phrase', 'মুখস্থ-নির্ভর শিক্ষা', 'learning by repeating without understanding', 'Many schools still rely heavily on rote learning instead of critical thinking.', 'advanced', v_education),
    ('vocational training', 'noun phrase', 'কারিগরি প্রশিক্ষণ', 'practical training for a specific trade or job', 'Vocational training gives students job-ready skills straight after school.', 'advanced', v_education),
    ('tuition fees', 'noun phrase', 'শিক্ষা ব্যয়/টিউশন ফি', 'money paid for instruction, especially at university', 'Rising tuition fees have made higher education inaccessible for many families.', 'advanced', v_education),
    ('dropout rate', 'noun phrase', 'ঝরে পড়ার হার', 'the proportion of students who leave school early', 'The dropout rate is significantly higher in rural areas.', 'advanced', v_education),
    ('academic rigour', 'noun phrase', 'একাডেমিক কঠোরতা', 'high intellectual standards in study', 'Critics argue that grade inflation has come at the cost of academic rigour.', 'advanced', v_education),
    ('lifelong learning', 'noun phrase', 'আজীবন শিক্ষা', 'continuing to learn throughout one''s life', 'In a fast-changing job market, lifelong learning is no longer optional.', 'advanced', v_education),
    ('student debt', 'noun phrase', 'শিক্ষাঋণ', 'money owed after borrowing to pay for education', 'Graduates are entering the workforce already burdened with student debt.', 'advanced', v_education),
    ('literacy rate', 'noun phrase', 'সাক্ষরতার হার', 'the percentage of people who can read and write', 'The literacy rate has improved dramatically over the past two decades.', 'advanced', v_education),
    ('higher education', 'noun phrase', 'উচ্চশিক্ষা', 'education beyond secondary school, e.g. university', 'Access to higher education remains unequal across income groups.', 'advanced', v_education),
    ('academic achievement', 'noun phrase', 'একাডেমিক সাফল্য', 'success in formal study', 'Parental involvement is closely linked to a child''s academic achievement.', 'advanced', v_education),
    ('extracurricular activities', 'noun phrase', 'পাঠ্যক্রম-বহির্ভূত কার্যক্রম', 'activities outside the regular curriculum, e.g. sports, clubs', 'Extracurricular activities help students develop skills that exams do not measure.', 'advanced', v_education),
    ('peer pressure', 'noun phrase', 'সমবয়সীদের চাপ', 'influence from people of the same age', 'Peer pressure can push teenagers into both positive and harmful behaviour.', 'advanced', v_education),
    ('mentorship', 'noun', 'পরামর্শদান', 'guidance from a more experienced person', 'Mentorship programmes connect new graduates with experienced professionals.', 'advanced', v_education),
    ('scholarship', 'noun', 'বৃত্তি', 'financial award to support study', 'She was awarded a full scholarship to study engineering abroad.', 'advanced', v_education),
    ('underprivileged students', 'noun phrase', 'সুবিধাবঞ্চিত শিক্ষার্থী', 'students lacking basic advantages others have', 'The programme provides free books and meals to underprivileged students.', 'advanced', v_education),
    ('teacher-student ratio', 'noun phrase', 'শিক্ষক-শিক্ষার্থী অনুপাত', 'the number of students per teacher', 'A lower teacher-student ratio allows for more individual attention.', 'advanced', v_education),
    ('standardised testing', 'noun phrase', 'মানসম্মত পরীক্ষা', 'tests administered and scored uniformly', 'Standardised testing is often criticised for ignoring creativity.', 'advanced', v_education),
    ('critical thinking', 'noun phrase', 'সমালোচনামূলক চিন্তা', 'analysing facts to form a judgement', 'Schools should nurture critical thinking rather than passive memorisation.', 'advanced', v_education),
    ('hands-on experience', 'noun phrase', 'হাতে-কলমে অভিজ্ঞতা', 'practical, direct experience of doing something', 'Internships give students hands-on experience that lectures cannot provide.', 'advanced', v_education),
    ('distance learning', 'noun phrase', 'দূরশিক্ষণ', 'studying remotely rather than in person', 'Distance learning has opened up education to people in remote areas.', 'advanced', v_education),
    ('private tutoring', 'noun phrase', 'ব্যক্তিগত গৃহশিক্ষা', 'individual paid instruction outside school', 'Reliance on private tutoring puts pressure on families with limited income.', 'advanced', v_education),
    ('coaching centre', 'noun phrase', 'কোচিং সেন্টার', 'a private institute that prepares students for exams', 'Many students spend more time at coaching centres than at school.', 'advanced', v_education),
    ('examination-oriented', 'adjective', 'পরীক্ষা-কেন্দ্রিক', 'focused mainly on passing exams', 'An examination-oriented system discourages genuine curiosity.', 'advanced', v_education),
    ('memorisation', 'noun', 'মুখস্থকরণ', 'the act of learning something by heart', 'Memorisation alone rarely leads to a deep understanding of a subject.', 'advanced', v_education),
    ('plagiarism', 'noun', 'চৌর্যবৃত্তি', 'copying someone else''s work and presenting it as one''s own', 'Universities have introduced software to detect plagiarism in assignments.', 'advanced', v_education),
    ('academic integrity', 'noun phrase', 'একাডেমিক সততা', 'honesty in study and research', 'Academic integrity is taken seriously from the very first year.', 'advanced', v_education),
    ('well-rounded education', 'noun phrase', 'সর্বাঙ্গীণ শিক্ষা', 'education covering many areas, not just academics', 'A well-rounded education combines academics, sport and the arts.', 'advanced', v_education),
    ('early childhood education', 'noun phrase', 'শৈশব শিক্ষা', 'education for very young children', 'Investment in early childhood education pays off later in life.', 'advanced', v_education),
    ('special needs education', 'noun phrase', 'বিশেষ চাহিদাসম্পন্ন শিক্ষা', 'education adapted for children with disabilities', 'Special needs education requires trained staff and adapted resources.', 'advanced', v_education),
    ('brain drain', 'noun phrase', 'মেধা পাচার', 'skilled people leaving their country for opportunities elsewhere', 'Brain drain remains a serious concern for developing economies.', 'advanced', v_education),
    ('skill gap', 'noun phrase', 'দক্ষতার ঘাটতি', 'the difference between skills employers need and skills workers have', 'There is a growing skill gap between what universities teach and what industries need.', 'advanced', v_education),
    ('employability', 'noun', 'কর্মযোগ্যতা', 'how suitable someone is for employment', 'Work placements significantly improve a graduate''s employability.', 'advanced', v_education),
    ('apprenticeship', 'noun', 'শিক্ষানবিশি', 'on-the-job training combined with study', 'An apprenticeship lets you earn a wage while you learn a trade.', 'advanced', v_education),
    ('continuing education', 'noun phrase', 'চলমান শিক্ষা', 'further education taken after formal schooling', 'Many professionals return to continuing education to stay competitive.', 'advanced', v_education),
    ('remedial classes', 'noun phrase', 'প্রতিকারমূলক ক্লাস', 'extra classes to help struggling students catch up', 'Remedial classes are offered to students who fall behind.', 'advanced', v_education),
    ('grade inflation', 'noun phrase', 'গ্রেড স্ফীতি', 'the gradual rise in average grades without a rise in standards', 'Grade inflation makes it harder for employers to judge real ability.', 'advanced', v_education),
    ('home schooling', 'noun', 'গৃহশিক্ষণ', 'educating children at home instead of school', 'Home schooling gives parents more control over the curriculum.', 'advanced', v_education),
    ('boarding school', 'noun phrase', 'আবাসিক স্কুল', 'a school where students live during term time', 'She was sent to a boarding school at the age of twelve.', 'advanced', v_education),
    ('co-education', 'noun', 'সহশিক্ষা', 'education of boys and girls together', 'Co-education is now the norm in most urban schools.', 'advanced', v_education),
    ('single-sex school', 'noun phrase', 'একলিঙ্গ বিদ্যালয়', 'a school for only boys or only girls', 'Advocates of single-sex schools claim they reduce social distraction.', 'advanced', v_education),
    ('truancy', 'noun', 'অনুপস্থিতি (স্কুল)', 'staying away from school without permission', 'Truancy rates tend to rise in the final years of secondary school.', 'advanced', v_education),
    ('disciplinary action', 'noun phrase', 'শৃঙ্খলামূলক ব্যবস্থা', 'formal punishment for breaking rules', 'Repeated misconduct can lead to serious disciplinary action.', 'advanced', v_education),
    ('inclusive education', 'noun phrase', 'অন্তর্ভুক্তিমূলক শিক্ষা', 'educating all students together regardless of ability', 'Inclusive education benefits both disabled and non-disabled children.', 'advanced', v_education),
    ('digital classroom', 'noun phrase', 'ডিজিটাল শ্রেণিকক্ষ', 'a classroom using technology as its main teaching tool', 'The pandemic accelerated the shift towards the digital classroom.', 'advanced', v_education),
    ('blended learning', 'noun phrase', 'মিশ্র শিক্ষণ', 'a mix of online and face-to-face teaching', 'Blended learning combines the flexibility of online study with classroom interaction.', 'advanced', v_technology),
    ('self-paced learning', 'noun phrase', 'স্ব-গতিতে শিক্ষা', 'learning at a speed the learner chooses', 'Self-paced learning suits students who need extra time to master concepts.', 'advanced', v_technology),
    ('transferable skills', 'noun phrase', 'স্থানান্তরযোগ্য দক্ষতা', 'skills useful across different jobs or situations', 'Communication and teamwork are transferable skills valued in every profession.', 'advanced', v_technology),
    ('to broaden one''s horizons', 'idiom', 'দৃষ্টিভঙ্গি প্রসারিত করা', 'to gain wider knowledge and experience', 'Studying abroad really broadened her horizons.', 'advanced', v_technology),
    ('to instil discipline', 'collocation', 'শৃঙ্খলা শেখানো', 'to teach someone to behave in a controlled way', 'Boarding schools are often praised for instilling discipline in students. Example', 'advanced', v_technology),
    ('automation', 'noun', 'স্বয়ংক্রিয়করণ', 'using machines to do work previously done by people', 'Automation has replaced many routine jobs in manufacturing.', 'advanced', v_technology),
    ('artificial intelligence', 'noun phrase', 'কৃত্রিম বুদ্ধিমত্তা', 'computer systems performing tasks that need human intelligence', 'Artificial intelligence is increasingly used to diagnose diseases.', 'advanced', v_technology),
    ('digital divide', 'noun phrase', 'ডিজিটাল বিভাজন', 'the gap between those with and without internet access', 'The digital divide left rural students unable to attend online classes.', 'advanced', v_technology),
    ('cyber security', 'noun phrase', 'সাইবার নিরাপত্তা', 'protection of computer systems from attack', 'Companies are investing heavily in cyber security following recent hacks.', 'advanced', v_technology),
    ('data privacy', 'noun phrase', 'তথ্য গোপনীয়তা', 'the right to control one''s personal information', 'Data privacy has become a major concern in the age of social media.', 'advanced', v_technology),
    ('surveillance', 'noun', 'নজরদারি', 'close observation, especially by authorities', 'Increased surveillance raises questions about individual freedom.', 'advanced', v_technology),
    ('connectivity', 'noun', 'সংযোগ', 'the state of being connected, e.g. to the internet', 'Improved connectivity has transformed rural communities.', 'advanced', v_technology),
    ('obsolete', 'adjective', 'অপ্রচলিত', 'no longer used because something newer exists', 'Many traditional skills have become obsolete because of automation.', 'advanced', v_technology),
    ('streamline', 'verb', 'সহজতর/সুবিন্যস্ত করা', 'to make a process more efficient', 'The new software streamlines the entire ordering process.', 'advanced', v_technology),
    ('e-commerce', 'noun', 'ই-কমার্স', 'buying and selling goods online', 'E-commerce has changed the way people shop for everyday items.', 'advanced', v_technology),
    ('cutting-edge', 'adjective', 'অত্যাধুনিক', 'most advanced and up to date', 'The hospital uses cutting-edge equipment to treat patients.', 'advanced', v_technology),
    ('tech-savvy', 'adjective', 'প্রযুক্তি-দক্ষ', 'skilled and comfortable with technology', 'Younger generations tend to be far more tech-savvy than their parents.', 'advanced', v_technology),
    ('user-friendly', 'adjective', 'ব্যবহারবান্ধব', 'easy for people to use', 'The app was redesigned to be more user-friendly for elderly users.', 'advanced', v_technology),
    ('breakthrough', 'noun', 'যুগান্তকারী আবিষ্কার', 'an important discovery or development', 'Scientists announced a breakthrough in battery technology.', 'advanced', v_technology),
    ('innovation', 'noun', 'উদ্ভাবন', 'a new idea, method or product', 'Continuous innovation keeps a company competitive.', 'advanced', v_technology),
    ('disruptive technology', 'noun phrase', 'বিঘ্নসৃষ্টিকারী প্রযুক্তি', 'technology that fundamentally changes an industry', 'Ride-sharing apps are a classic example of disruptive technology.', 'advanced', v_technology),
    ('algorithm', 'noun', 'অ্যালগরিদম', 'a set of rules a computer follows to solve a problem', 'Social media algorithms decide exactly what content users see.', 'advanced', v_technology),
    ('virtual reality', 'noun phrase', 'ভার্চুয়াল রিয়েলিটি', 'a computer-generated simulated environment', 'Virtual reality is being used to train surgeons before real operations.', 'advanced', v_technology),
    ('machine learning', 'noun phrase', 'মেশিন লার্নিং', 'a type of AI that learns from data', 'Machine learning enables systems to improve their accuracy over time.', 'advanced', v_technology),
    ('cloud storage', 'noun phrase', 'ক্লাউড স্টোরেজ', 'storing data on remote servers accessed via the internet', 'Cloud storage means files can be accessed from any device.', 'advanced', v_technology),
    ('digital footprint', 'noun phrase', 'ডিজিটাল পদচিহ্ন', 'the trail of data left by online activity', 'Employers now routinely check a candidate''s digital footprint.', 'advanced', v_technology),
    ('screen addiction', 'noun phrase', 'স্ক্রিন আসক্তি', 'compulsive, excessive use of screens', 'Screen addiction among children has alarmed health professionals.', 'advanced', v_technology),
    ('information overload', 'noun phrase', 'তথ্যের আধিক্য', 'being exposed to too much information at once', 'Constant notifications contribute to information overload.', 'advanced', v_technology),
    ('paperless office', 'noun phrase', 'কাগজবিহীন অফিস', 'a workplace that avoids using paper documents', 'The company moved to a paperless office to cut costs and waste.', 'advanced', v_technology),
    ('remote access', 'noun phrase', 'দূরবর্তী প্রবেশাধিকার', 'the ability to access a system from a distance', 'Remote access allows employees to work securely from home.', 'advanced', v_technology),
    ('biometric authentication', 'noun phrase', 'বায়োমেট্রিক যাচাই', 'identity verification using fingerprints, face, etc.', 'Most modern smartphones use biometric authentication instead of passwords.', 'advanced', v_technology),
    ('malware', 'noun', 'ম্যালওয়্যার', 'software designed to damage or disrupt a system', 'The company''s network was infected with malware last month.', 'advanced', v_technology),
    ('phishing', 'noun', 'ফিশিং প্রতারণা', 'tricking people into revealing personal information online', 'She almost fell victim to a phishing email disguised as her bank.', 'advanced', v_technology),
    ('digital literacy', 'noun phrase', 'ডিজিটাল সাক্ষরতা', 'the ability to use digital tools effectively', 'Digital literacy is now considered as essential as reading and writing.', 'advanced', v_technology),
    ('tech giant', 'noun phrase', 'বৃহৎ প্রযুক্তি কোম্পানি', 'a very large and powerful technology company', 'A handful of tech giants dominate the global market.', 'advanced', v_technology),
    ('wearable device', 'noun phrase', 'পরিধানযোগ্য যন্ত্র', 'a small electronic device worn on the body', 'Wearable devices can now monitor heart rate throughout the day.', 'advanced', v_technology),
    ('smart home', 'noun phrase', 'স্মার্ট হোম', 'a home with internet-connected, automated devices', 'A smart home can adjust lighting and temperature automatically.', 'advanced', v_technology),
    ('3D printing', 'noun phrase', 'থ্রিডি প্রিন্টিং', 'creating physical objects from a digital design', '3D printing is beginning to revolutionise manufacturing.', 'advanced', v_technology),
    ('robotics', 'noun', 'রোবোটিক্স', 'the design and use of robots', 'Robotics has transformed how cars are assembled.', 'advanced', v_technology),
    ('digital nomad', 'noun phrase', 'ডিজিটাল যাযাবর', 'someone who works remotely while travelling', 'More young professionals are choosing to become digital nomads.', 'advanced', v_technology),
    ('online privacy', 'noun phrase', 'অনলাইন গোপনীয়তা', 'protection of personal information on the internet', 'Online privacy is increasingly difficult to guarantee.', 'advanced', v_technology),
    ('data breach', 'noun phrase', 'তথ্য ফাঁস', 'an incident where protected data is exposed', 'The data breach affected millions of customer accounts.', 'advanced', v_technology),
    ('encrypted', 'adjective', 'এনক্রিপ্টেড', 'converted into a code to prevent unauthorised access', 'All messages on the app are fully encrypted.', 'advanced', v_technology),
    ('glitch', 'noun', 'সাময়িক ত্রুটি', 'a small, temporary technical fault', 'A software glitch delayed the flight by two hours.', 'advanced', v_technology),
    ('outdated', 'adjective', 'পুরনো/অপ্রচলিত', 'no longer modern or useful', 'The factory still runs on outdated machinery.', 'advanced', v_technology),
    ('state-of-the-art', 'adjective', 'অত্যাধুনিক প্রযুক্তির', 'using the most modern methods or ideas', 'The lab is equipped with state-of- the-art scanning equipment.', 'advanced', v_technology),
    ('tech dependency', 'noun phrase', 'প্রযুক্তি-নির্ভরতা', 'excessive reliance on technology', 'Tech dependency has raised concerns about children''s attention spans.', 'advanced', v_technology),
    ('digital transformation', 'noun phrase', 'ডিজিটাল রূপান্তর', 'the integration of digital technology into all areas of business', 'The bank underwent a full digital transformation over five years.', 'advanced', v_environment),
    ('augmented reality', 'noun phrase', 'অগমেন্টেড রিয়েলিটি', 'technology that overlays digital images onto the real world', 'Augmented reality apps let shoppers preview furniture in their own homes.', 'advanced', v_environment),
    ('facial recognition', 'noun phrase', 'মুখমণ্ডল শনাক্তকরণ', 'technology that identifies a person from their face', 'Facial recognition is used at airports to speed up passport checks.', 'advanced', v_environment),
    ('open-source', 'adjective', 'উন্মুক্ত-উৎস', 'software with publicly available source code', 'Open-source software allows developers worldwide to improve it collaboratively.', 'advanced', v_environment),
    ('bandwidth', 'noun', 'ব্যান্ডউইথ', 'the capacity for data transfer on a network', 'Video calls require significantly more bandwidth than text messaging.', 'advanced', v_environment),
    ('to go viral', 'idiom', 'ভাইরাল হওয়া', 'to spread very quickly online', 'The video went viral within hours of being posted.', 'advanced', v_environment),
    ('to keep pace with technology', 'collocation', 'প্রযুক্তির সাথে তাল মেলানো', 'to stay up to date as technology changes', 'Small businesses often struggle to keep pace with technology.', 'advanced', v_environment),
    ('digital detox', 'noun phrase', 'ডিজিটাল ডিটক্স', 'a period of deliberately avoiding digital devices', 'She takes a digital detox every weekend to reduce screen time. Example', 'advanced', v_environment),
    ('carbon footprint', 'noun phrase', 'কার্বন পদচিহ্ন', 'the total greenhouse gases produced by a person or activity', 'Flying frequently significantly increases a person''s carbon footprint.', 'advanced', v_environment),
    ('deforestation', 'noun', 'বনভূমি নিধন', 'the clearing of forests', 'Deforestation in the region has accelerated over the past decade.', 'advanced', v_environment),
    ('biodiversity', 'noun', 'জীববৈচিত্র্য', 'the variety of plant and animal life in an area', 'Wetlands support an extraordinary level of biodiversity.', 'advanced', v_environment),
    ('fossil fuels', 'noun phrase', 'জীবাশ্ম জ্বালানি', 'coal, oil and gas formed from ancient organisms', 'Reliance on fossil fuels remains the biggest driver of emissions.', 'advanced', v_environment),
    ('renewable energy', 'noun phrase', 'নবায়নযোগ্য জ্বালানি', 'energy from sources that naturally replenish', 'Investment in renewable energy has fallen in cost dramatically.', 'advanced', v_environment),
    ('greenhouse gas emissions', 'noun phrase', 'গ্রিনহাউস গ্যাস নিঃসরণ', 'gases released that trap heat in the atmosphere', 'Industrial activity accounts for a large share of greenhouse gas emissions.', 'advanced', v_environment),
    ('global warming', 'noun phrase', 'বৈশ্বিক উষ্ণায়ন', 'the long-term rise in Earth''s average temperature', 'Global warming is accelerating the melting of polar ice.', 'advanced', v_environment),
    ('climate change', 'noun phrase', 'জলবায়ু পরিবর্তন', 'long-term shifts in weather patterns', 'Climate change is already affecting agricultural yields worldwide.', 'advanced', v_environment),
    ('sustainable development', 'noun phrase', 'টেকসই উন্নয়ন', 'development that meets present needs without harming the future', 'Sustainable development balances economic growth with environmental protection.', 'advanced', v_environment),
    ('endangered species', 'noun phrase', 'বিপন্ন প্রজাতি', 'a species at risk of extinction', 'Poaching remains the biggest threat to many endangered species.', 'advanced', v_environment),
    ('ecosystem', 'noun', 'বাস্তুতন্ত্র', 'a community of living things and their environment', 'Coral reefs form one of the richest ecosystems on the planet.', 'advanced', v_environment),
    ('ecological balance', 'noun phrase', 'বাস্তুসংস্থানিক ভারসাম্য', 'a stable relationship between living things and their environment', 'Overfishing has disrupted the ecological balance of the region.', 'advanced', v_environment),
    ('pollution', 'noun', 'দূষণ', 'the presence of harmful substances in the environment', 'Air pollution levels in the capital regularly exceed safety limits.', 'advanced', v_environment),
    ('waste management', 'noun phrase', 'বর্জ্য ব্যবস্থাপনা', 'the collection and disposal of waste', 'Poor waste management has led to overflowing landfills.', 'advanced', v_environment),
    ('recycling', 'noun', 'পুনর্ব্যবহার', 'converting waste into reusable material', 'Recycling rates remain low compared to neighbouring countries.', 'advanced', v_environment),
    ('single-use plastic', 'noun phrase', 'একবার-ব্যবহারযোগ্য প্লাস্টিক', 'plastic used once then discarded', 'Several countries have banned single-use plastic bags.', 'advanced', v_environment),
    ('ozone layer', 'noun phrase', 'ওজোন স্তর', 'the layer of the atmosphere that blocks UV radiation', 'The ozone layer has slowly begun to recover.', 'advanced', v_environment),
    ('conservation', 'noun', 'সংরক্ষণ', 'protecting the natural environment', 'Conservation efforts have helped tiger numbers recover slightly.', 'advanced', v_environment),
    ('natural habitat', 'noun phrase', 'প্রাকৃতিক আবাসস্থল', 'the natural environment where a species lives', 'Urban expansion continues to destroy the natural habitat of wildlife.', 'advanced', v_environment),
    ('environmental degradation', 'noun phrase', 'পরিবেশগত অবক্ষয়', 'the deterioration of the environment', 'Rapid industrialisation has caused severe environmental degradation.', 'advanced', v_environment),
    ('air quality', 'noun phrase', 'বায়ুর গুণমান', 'the level of pollution in the air', 'Air quality worsens noticeably during the dry season.', 'advanced', v_environment),
    ('water scarcity', 'noun phrase', 'পানির অভাব', 'a shortage of available water', 'Water scarcity is expected to affect billions by mid-century.', 'advanced', v_environment),
    ('drought', 'noun', 'খরা', 'a prolonged period of abnormally low rainfall', 'The drought has devastated crops across the region.', 'advanced', v_environment),
    ('carbon-neutral', 'adjective', 'কার্বন-নিরপেক্ষ', 'not adding to overall carbon emissions', 'The company pledged to become carbon-neutral by 2030.', 'advanced', v_environment),
    ('eco-friendly', 'adjective', 'পরিবেশবান্ধব', 'not harmful to the environment', 'Eco-friendly packaging has become a selling point for many brands.', 'advanced', v_environment),
    ('green initiative', 'noun phrase', 'সবুজ উদ্যোগ', 'a project aimed at protecting the environment', 'The city launched a green initiative to plant a million trees.', 'advanced', v_environment),
    ('mitigation', 'noun', 'প্রশমন', 'action taken to reduce the severity of something', 'Flood mitigation measures include better drainage systems.', 'advanced', v_environment),
    ('adaptation', 'noun', 'অভিযোজন', 'adjusting to new conditions', 'Farmers are adopting drought- resistant crops as a form of adaptation.', 'advanced', v_environment),
    ('rising sea levels', 'noun phrase', 'সমুদ্রপৃষ্ঠের উচ্চতা বৃদ্ধি', 'the increase in ocean levels caused by warming', 'Rising sea levels threaten to submerge low-lying coastal areas.', 'advanced', v_environment),
    ('extreme weather', 'noun phrase', 'চরম আবহাওয়া', 'unusually severe weather events', 'Extreme weather events have become more frequent in recent years.', 'advanced', v_environment),
    ('food security', 'noun phrase', 'খাদ্য নিরাপত্তা', 'reliable access to sufficient, affordable food', 'Climate change poses a direct threat to food security.', 'advanced', v_environment),
    ('overfishing', 'noun', 'অতিরিক্ত মাছ ধরা', 'catching fish faster than populations can recover', 'Overfishing has pushed several species to the brink of collapse.', 'advanced', v_environment),
    ('soil erosion', 'noun phrase', 'মাটি ক্ষয়', 'the wearing away of topsoil', 'Deforestation has accelerated soil erosion on hillsides.', 'advanced', v_environment),
    ('urban sprawl', 'noun phrase', 'শহরের অপরিকল্পিত সম্প্রসারণ', 'the uncontrolled expansion of a city', 'Urban sprawl has consumed farmland on the city''s outskirts.', 'advanced', v_environment),
    ('industrial waste', 'noun phrase', 'শিল্প বর্জ্য', 'waste produced by factories', 'Untreated industrial waste continues to pollute the river.', 'advanced', v_environment),
    ('toxic emissions', 'noun phrase', 'বিষাক্ত নিঃসরণ', 'harmful gases or substances released into the air', 'Toxic emissions from factories have been linked to respiratory illness.', 'advanced', v_environment),
    ('environmental awareness', 'noun phrase', 'পরিবেশ সচেতনতা', 'understanding of environmental issues', 'Environmental awareness among young people has grown considerably.', 'advanced', v_environment),
    ('sustainable agriculture', 'noun phrase', 'টেকসই কৃষি', 'farming methods that protect long-term resources', 'Sustainable agriculture reduces reliance on chemical fertilisers.', 'advanced', v_environment),
    ('solar power', 'noun phrase', 'সৌরশক্তি', 'energy generated from sunlight', 'Solar power now accounts for a growing share of electricity generation.', 'advanced', v_environment),
    ('wind energy', 'noun phrase', 'বায়ুশক্তি', 'energy generated from wind', 'Coastal regions are ideal locations for wind energy projects.', 'advanced', v_environment),
    ('energy-efficient', 'adjective', 'জ্বালানি-সাশ্রয়ী', 'using less energy to achieve the same result', 'Energy-efficient appliances can significantly cut household bills.', 'advanced', v_environment),
    ('non-renewable resources', 'noun phrase', 'অনবায়নযোগ্য সম্পদ', 'resources that cannot be replaced once used', 'Non-renewable resources such as coal will eventually run out.', 'advanced', v_environment),
    ('carbon offset', 'noun phrase', 'কার্বন অফসেট', 'compensating for emissions by funding environmental projects', 'Airlines now offer passengers the option to purchase a carbon offset.', 'advanced', v_environment),
    ('wildlife conservation', 'noun phrase', 'বন্যপ্রাণী সংরক্ষণ', 'protecting animal species and habitats', 'Wildlife conservation projects rely heavily on local community support.', 'advanced', v_environment),
    ('natural disaster', 'noun phrase', 'প্রাকৃতিক দুর্যোগ', 'a severe natural event causing damage', 'The region is highly vulnerable to natural disasters such as cyclones.', 'advanced', v_environment),
    ('coastal erosion', 'noun phrase', 'উপকূল ক্ষয়', 'the wearing away of coastline by the sea', 'Coastal erosion is forcing entire villages to relocate inland.', 'advanced', v_environment),
    ('to phase out', null, 'ধীরে ধীরে বন্ধ করা', 'to gradually stop using something', 'Several countries plan to phase out petrol cars within a decade.', 'advanced', v_environment),
    ('to curb emissions', 'collocation', 'নিঃসরণ নিয়ন্ত্রণ করা', 'to reduce or control emissions', 'New regulations aim to curb emissions from heavy industry.', 'advanced', v_environment),
    ('to take a toll on', 'idiom', 'ক্ষতিসাধন করা', 'to have a harmful effect on something over time', 'Rapid industrialisation has taken a heavy toll on local rivers.', 'advanced', v_environment),
    ('net zero', 'noun phrase', 'নেট শূন্য নিঃসরণ', 'a state where emissions produced equal emissions removed', 'The country has pledged to reach net zero by 2050.', 'advanced', v_environment),
    ('obesity', 'noun', 'স্থূলতা', 'the condition of being severely overweight', 'Childhood obesity has more than doubled in the past thirty years.', 'advanced', v_health_and_lifestyle),
    ('sedentary lifestyle', 'noun phrase', 'বসে থাকা জীবনধারা', 'a way of life involving little physical activity', 'A sedentary lifestyle is a major risk factor for heart disease.', 'advanced', v_health_and_lifestyle),
    ('chronic illness', 'noun phrase', 'দীর্ঘস্থায়ী রোগ', 'a long-lasting medical condition', 'Chronic illness places a huge strain on public healthcare systems.', 'advanced', v_health_and_lifestyle),
    ('preventive care', 'noun phrase', 'প্রতিরোধমূলক চিকিৎসা', 'healthcare aimed at preventing illness before it occurs', 'Preventive care is far cheaper than treating advanced disease.', 'advanced', v_health_and_lifestyle),
    ('public health', 'noun phrase', 'জনস্বাস্থ্য', 'the health of the population as a whole', 'Vaccination campaigns are a cornerstone of public health policy.', 'advanced', v_health_and_lifestyle),
    ('mental wellbeing', 'noun phrase', 'মানসিক সুস্থতা', 'a state of good psychological health', 'Employers are increasingly recognising the importance of staff mental wellbeing.', 'advanced', v_health_and_lifestyle),
    ('life expectancy', 'noun phrase', 'গড় আয়ুষ্কাল', 'the average number of years a person is expected to live', 'Life expectancy has risen sharply thanks to improved healthcare.', 'advanced', v_health_and_lifestyle),
    ('malnutrition', 'noun', 'অপুষ্টি', 'lack of proper nutrition', 'Malnutrition remains widespread among children in the region.', 'advanced', v_health_and_lifestyle),
    ('healthcare provision', 'noun phrase', 'স্বাস্থ্যসেবা ব্যবস্থা', 'the supply of medical services to a population', 'Healthcare provision in rural areas lags far behind that in cities.', 'advanced', v_health_and_lifestyle),
    ('epidemic', 'noun', 'মহামারী', 'a widespread outbreak of disease', 'An epidemic of dengue fever swept through the city last summer.', 'advanced', v_health_and_lifestyle),
    ('immunisation', 'noun', 'টিকাদান', 'making someone immune to disease, usually by vaccine', 'Immunisation programmes have virtually eliminated several deadly diseases.', 'advanced', v_health_and_lifestyle),
    ('medical infrastructure', 'noun phrase', 'চিকিৎসা অবকাঠামো', 'the facilities and systems supporting healthcare', 'Rural hospitals often lack basic medical infrastructure.', 'advanced', v_health_and_lifestyle),
    ('stress-related illness', 'noun phrase', 'মানসিক চাপজনিত রোগ', 'illness caused or worsened by stress', 'Stress-related illness is on the rise among office workers.', 'advanced', v_health_and_lifestyle),
    ('balanced diet', 'noun phrase', 'সুষম খাদ্য', 'a diet containing the right proportions of nutrients', 'Doctors recommend a balanced diet alongside regular exercise.', 'advanced', v_health_and_lifestyle),
    ('junk food', 'noun phrase', 'জাংক ফুড', 'food high in calories but low in nutrition', 'Junk food advertising aimed at children has been widely criticised.', 'advanced', v_health_and_lifestyle),
    ('sanitation', 'noun', 'স্যানিটেশন', 'systems for maintaining hygiene and disposing of waste', 'Poor sanitation is a leading cause of disease in developing countries.', 'advanced', v_health_and_lifestyle),
    ('life-threatening', 'adjective', 'প্রাণঘাতী', 'capable of causing death', 'The disease can become life- threatening if left untreated.', 'advanced', v_health_and_lifestyle),
    ('quality of life', 'noun phrase', 'জীবনযাত্রার মান', 'the general wellbeing of an individual or society', 'Access to green spaces significantly improves quality of life in cities.', 'advanced', v_health_and_lifestyle),
    ('work-life balance', 'noun phrase', 'কর্ম-জীবন ভারসাম্য', 'a healthy balance between work and personal life', 'Many employees struggle to maintain a healthy work-life balance.', 'advanced', v_health_and_lifestyle),
    ('burnout', 'noun', 'চরম ক্লান্তি (বার্নআউট)', 'extreme exhaustion caused by prolonged stress', 'Burnout among healthcare workers has become a serious concern.', 'advanced', v_health_and_lifestyle),
    ('insomnia', 'noun', 'অনিদ্রা', 'persistent difficulty sleeping', 'Excessive screen time before bed can contribute to insomnia.', 'advanced', v_health_and_lifestyle),
    ('physical fitness', 'noun phrase', 'শারীরিক সুস্থতা', 'the condition of being physically healthy and strong', 'Schools should place greater emphasis on physical fitness.', 'advanced', v_health_and_lifestyle),
    ('alternative medicine', 'noun phrase', 'বিকল্প চিকিৎসা', 'medical practices outside conventional medicine', 'Interest in alternative medicine has grown despite limited scientific evidence.', 'advanced', v_health_and_lifestyle),
    ('vaccination hesitancy', 'noun phrase', 'টিকা নিতে দ্বিধা', 'reluctance to receive vaccines despite availability', 'Vaccination hesitancy has allowed preventable diseases to resurface.', 'advanced', v_health_and_lifestyle),
    ('medical breakthrough', 'noun phrase', 'চিকিৎসা যুগান্তকারী আবিষ্কার', 'a major advance in medical science', 'The medical breakthrough offers new hope for cancer patients.', 'advanced', v_health_and_lifestyle),
    ('ageing population', 'noun phrase', 'বয়োবৃদ্ধ জনসংখ্যা', 'a population with a rising proportion of elderly people', 'An ageing population puts increasing pressure on pension systems.', 'advanced', v_health_and_lifestyle),
    ('a clean bill of health', 'idiom', 'সম্পূর্ণ সুস্থতার প্রত্যয়নপত্র', 'confirmation that someone is completely healthy', 'After the check-up, the doctor gave him a clean bill of health.', 'advanced', v_health_and_lifestyle),
    ('to take its toll', 'idiom', 'ক্ষতিসাধন করা', 'to have a harmful effect over time', 'Years of overwork eventually took its toll on her health.', 'advanced', v_health_and_lifestyle),
    ('to be on the mend', 'idiom', 'সুস্থ হয়ে উঠছে', 'to be recovering from an illness', 'She is still weak, but she is on the mend.', 'advanced', v_health_and_lifestyle),
    ('to run in the family', 'idiom', 'বংশগতভাবে চলে আসা', 'to be a trait passed through generations', 'Heart disease runs in the family, so he watches his diet carefully.', 'advanced', v_health_and_lifestyle),
    ('a balanced approach to eating', 'collocation', 'সুষম খাদ্যাভ্যাস', 'moderate, sensible eating habits', 'Nutritionists encourage a balanced approach to eating rather than strict dieting.', 'advanced', v_health_and_lifestyle),
    ('to boost immunity', 'collocation', 'রোগ প্রতিরোধ ক্ষমতা বাড়ানো', 'to strengthen the body''s defence against illness', 'A varied diet helps to boost immunity naturally.', 'advanced', v_health_and_lifestyle),
    ('to curb an epidemic', 'collocation', 'মহামারী নিয়ন্ত্রণ করা', 'to bring an outbreak of disease under control', 'Strict quarantine measures helped curb the epidemic.', 'advanced', v_health_and_lifestyle),
    ('underlying condition', 'noun phrase', 'অন্তর্নিহিত স্বাস্থ্য সমস্যা', 'an existing health problem that increases risk', 'Patients with an underlying condition are more vulnerable to complications.', 'advanced', v_health_and_lifestyle),
    ('over-the-counter medication', 'noun phrase', 'প্রেসক্রিপশন ছাড়া ওষুধ', 'medicine available without a prescription', 'Over-the-counter medication should still be used with caution.', 'advanced', v_health_and_lifestyle),
    ('healthcare disparity', 'noun phrase', 'স্বাস্থ্যসেবায় বৈষম্য', 'unequal access to medical care', 'Healthcare disparity between urban and rural areas remains stark.', 'advanced', v_health_and_lifestyle),
    ('recovery rate', 'noun phrase', 'সুস্থতার হার', 'the proportion of patients who recover', 'The recovery rate has improved thanks to earlier diagnosis.', 'advanced', v_health_and_lifestyle),
    ('risk factor', 'noun phrase', 'ঝুঁকির কারণ', 'something that increases the chance of disease', 'Smoking is the single biggest risk factor for lung cancer.', 'advanced', v_health_and_lifestyle),
    ('holistic approach', 'noun phrase', 'সামগ্রিক চিকিৎসা পদ্ধতি', 'treating the whole person, not just symptoms', 'A holistic approach considers mental as well as physical health.', 'advanced', v_health_and_lifestyle),
    ('to lead a healthy lifestyle', 'collocation', 'স্বাস্থ্যকর জীবনযাপন করা', 'to live in a way that promotes good health', 'She tries to lead a healthy lifestyle despite a demanding job.', 'advanced', v_health_and_lifestyle),
    ('exhausted', 'adjective', 'ক্লান্ত', 'extremely tired', 'After the night shift, the nurses were completely exhausted.', 'advanced', v_health_and_lifestyle),
    ('deteriorate', 'verb', 'অবনতি ঘটা', 'to become progressively worse', 'His condition deteriorated rapidly over the weekend.', 'advanced', v_health_and_lifestyle),
    ('contagious', 'adjective', 'সংক্রামক', 'able to spread from person to person', 'The virus is highly contagious and spreads through close contact.', 'advanced', v_health_and_lifestyle),
    ('a sedentary desk job', 'collocation', 'বসে থাকা ডেস্ক-কাজ', 'office work involving little movement', 'A sedentary desk job for years took a toll on his fitness.', 'advanced', v_health_and_lifestyle),
    ('to nip something in the bud', 'idiom', 'শুরুতেই সমস্যা দমন করা', 'to stop a problem before it develops further', 'Early screening allows doctors to nip many illnesses in the bud.', 'advanced', v_health_and_lifestyle),
    ('detrimental to health', 'collocation', 'স্বাস্থ্যের জন্য ক্ষতিকর', 'harmful to physical or mental health', 'Prolonged exposure to noise pollution is detrimental to health.', 'advanced', v_health_and_lifestyle),
    ('dietary habits', 'noun phrase', 'খাদ্যাভ্যাস', 'a person''s usual pattern of eating', 'Dietary habits established in childhood often continue into adulthood.', 'advanced', v_health_and_lifestyle),
    ('overprescribed', 'adjective', 'অতিরিক্ত প্রেসক্রাইব করা', 'prescribed too frequently or in excess', 'Antibiotics are widely believed to be overprescribed.', 'advanced', v_health_and_lifestyle),
    ('a growing health concern', 'collocation', 'ক্রমবর্ধমান স্বাস্থ্য উদ্বেগ', 'a health issue that is increasingly worrying', 'Mental health among teenagers has become a growing health concern.', 'advanced', v_crime_and_law),
    ('a health scare', 'noun phrase', 'স্বাস্থ্য-আতঙ্ক', 'a frightening but often temporary health incident', 'A minor health scare made him rethink his entire lifestyle.', 'advanced', v_crime_and_law);
end $$;
