-- ============================================================
-- 025_ielts_vocabulary_words_200_399.sql
-- Content batch: IELTS Band 8 vocabulary words 200-399,
-- transcribed from "1000 Essential Words for Band 8" (word, part of
-- speech, definition, and example extracted from the source; Bangla
-- meanings authored fresh, since the PDF's own Bangla text layer is
-- corrupted at the font level -- see migration notes).
-- ============================================================

do $$
declare
  v_crime_and_law uuid;
  v_economy_and_work uuid;
  v_society_and_culture uuid;
  v_government_and_politics uuid;
  v_media_and_advertising uuid;
  v_travel_and_tourism uuid;
begin
  select cn.id into v_crime_and_law from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'crime-and-law';
  select cn.id into v_economy_and_work from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'economy-and-work';
  select cn.id into v_society_and_culture from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'society-and-culture';
  select cn.id into v_government_and_politics from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'government-and-politics';
  select cn.id into v_media_and_advertising from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'media-and-advertising';
  select cn.id into v_travel_and_tourism from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'travel-and-tourism';

  insert into vocabulary (word, part_of_speech, bangla_meaning, english_definition, example_sentence, difficulty, node_id) values
    ('deterrent', 'noun', 'প্রতিরোধক', 'something that discourages an action', 'Harsh penalties are intended to act as a deterrent to crime.', 'advanced', v_crime_and_law),
    ('rehabilitation', 'noun', 'পুনর্বাসন', 'helping offenders return to a law-abiding life', 'Rehabilitation programmes aim to reduce reoffending rates.', 'advanced', v_crime_and_law),
    ('recidivism', 'noun', 'পুনরায় অপরাধ প্রবণতা', 'the tendency of a convicted criminal to reoffend', 'Vocational training in prison has been shown to reduce recidivism.', 'advanced', v_crime_and_law),
    ('custodial sentence', 'noun phrase', 'কারাদণ্ড', 'a punishment involving imprisonment', 'The judge handed down a lengthy custodial sentence.', 'advanced', v_crime_and_law),
    ('petty crime', 'noun phrase', 'লঘু অপরাধ', 'minor, non-violent offences', 'Petty crime such as shoplifting tends to rise during economic downturns.', 'advanced', v_crime_and_law),
    ('law enforcement', 'noun phrase', 'আইনশৃঙ্খলা রক্ষা', 'the police and related agencies', 'Law enforcement agencies have adopted new surveillance technology.', 'advanced', v_crime_and_law),
    ('root causes of crime', 'noun phrase', 'অপরাধের মূল কারণ', 'the underlying factors that lead to criminal behaviour', 'Poverty is widely regarded as one of the root causes of crime.', 'advanced', v_crime_and_law),
    ('organised crime', 'noun phrase', 'সংগঠিত অপরাধ', 'crime carried out by structured criminal groups', 'Organised crime networks often operate across national borders.', 'advanced', v_crime_and_law),
    ('juvenile delinquency', 'noun phrase', 'কিশোর অপরাধ', 'criminal behaviour by young people', 'Juvenile delinquency is often linked to family instability.', 'advanced', v_crime_and_law),
    ('capital punishment', 'noun phrase', 'মৃত্যুদণ্ড', 'the death penalty', 'Capital punishment remains a deeply divisive issue worldwide.', 'advanced', v_crime_and_law),
    ('miscarriage of justice', 'noun phrase', 'বিচারিক ভুল', 'a wrongful conviction or unjust legal outcome', 'The case was later found to be a miscarriage of justice.', 'advanced', v_crime_and_law),
    ('surveillance camera', 'noun phrase', 'নজরদারি ক্যামেরা', 'a camera used to monitor an area', 'Surveillance cameras have become common in city centres.', 'advanced', v_crime_and_law),
    ('white-collar crime', 'noun phrase', 'হোয়াইট-কলার অপরাধ', 'non-violent crime committed for financial gain', 'White-collar crime such as fraud is notoriously difficult to detect.', 'advanced', v_crime_and_law),
    ('cybercrime', 'noun', 'সাইবার অপরাধ', 'crime committed using computers or the internet', 'Cybercrime has grown rapidly alongside internet use.', 'advanced', v_crime_and_law),
    ('vandalism', 'noun', 'ভাঙচুর', 'deliberate destruction of property', 'Vandalism in the park has cost the council thousands to repair.', 'advanced', v_crime_and_law),
    ('community service', 'noun phrase', 'সমাজসেবা (শাস্তি হিসেবে)', 'unpaid work as a form of punishment', 'The court ordered him to complete 100 hours of community service.', 'advanced', v_crime_and_law),
    ('probation', 'noun', 'প্রবেশন', 'supervised release instead of prison', 'She was placed on probation rather than sent to prison.', 'advanced', v_crime_and_law),
    ('to break the law', 'collocation', 'আইন ভঙ্গ করা', 'to act illegally', 'Few people set out intending to break the law.', 'advanced', v_crime_and_law),
    ('to serve a sentence', 'collocation', 'সাজা ভোগ করা', 'to spend time in prison as punishment', 'He served a five-year sentence for fraud.', 'advanced', v_crime_and_law),
    ('zero-tolerance policy', 'noun phrase', 'শূন্য-সহনশীলতা নীতি', 'a strict policy that punishes any violation', 'The school introduced a zero- tolerance policy on bullying.', 'advanced', v_crime_and_law),
    ('offender', 'noun', 'অপরাধী', 'a person who commits a crime', 'First-time offenders are often given lighter sentences.', 'advanced', v_crime_and_law),
    ('to be behind bars', 'idiom', 'কারাগারে থাকা', 'to be in prison', 'He has been behind bars for nearly a decade.', 'advanced', v_crime_and_law),
    ('crackdown', 'noun', 'কঠোর অভিযান', 'strict action taken to stop illegal activity', 'The government launched a crackdown on drug trafficking.', 'advanced', v_crime_and_law),
    ('forensic evidence', 'noun phrase', 'ফরেনসিক প্রমাণ', 'scientific evidence used in criminal investigations', 'Forensic evidence played a decisive role in the trial.', 'advanced', v_crime_and_law),
    ('wrongful conviction', 'noun phrase', 'ভুল অভিযোগে দণ্ড', 'being found guilty despite being innocent', 'DNA testing has helped overturn several wrongful convictions.', 'advanced', v_crime_and_law),
    ('to turn to crime', 'collocation', 'অপরাধে জড়িয়ে পড়া', 'to begin engaging in criminal activity', 'Many young people turn to crime out of financial desperation.', 'advanced', v_crime_and_law),
    ('anti-social behaviour', 'noun phrase', 'সমাজবিরোধী আচরণ', 'behaviour that disturbs or harms others in a community', 'Anti-social behaviour has increased in some neighbourhoods.', 'advanced', v_crime_and_law),
    ('a repeat offender', 'noun phrase', 'পুনরাবৃত্ত অপরাধী', 'someone who commits crimes more than once', 'Repeat offenders often receive harsher sentences.', 'advanced', v_crime_and_law),
    ('crime rate', 'noun phrase', 'অপরাধের হার', 'the frequency of crimes in a given area', 'The crime rate has fallen steadily over the past five years.', 'advanced', v_crime_and_law),
    ('to bring someone to justice', 'idiom', 'বিচারের আওতায় আনা', 'to ensure someone is legally punished for a crime', 'Investigators worked for years to bring the perpetrators to justice.', 'advanced', v_crime_and_law),
    ('domestic violence', 'noun phrase', 'পারিবারিক সহিংসতা', 'violence occurring within a household', 'Domestic violence remains significantly underreported.', 'advanced', v_crime_and_law),
    ('to acquit', 'verb', 'খালাস দেওয়া', 'to declare someone not guilty', 'The jury acquitted the defendant after two days of deliberation.', 'advanced', v_crime_and_law),
    ('tighten security', 'collocation', 'নিরাপত্তা কঠোর করা', 'to make security measures stricter', 'Airports tightened security following the incident.', 'advanced', v_crime_and_law),
    ('illicit activity', 'noun phrase', 'অবৈধ কার্যকলাপ', 'illegal or forbidden activity', 'The warehouse was reportedly used for illicit activity.', 'advanced', v_crime_and_law),
    ('a hardened criminal', 'noun phrase', 'কট্টর অপরাধী', 'someone experienced in and unaffected by crime', 'By his thirties, he had become a hardened criminal.', 'advanced', v_economy_and_work),
    ('neighbourhood watch', 'noun phrase', 'পাড়া প্রতিরক্ষা দল', 'a local scheme where residents help prevent crime', 'The neighbourhood watch has helped reduce burglaries significantly.', 'advanced', v_economy_and_work),
    ('punitive measures', 'noun phrase', 'শাস্তিমূলক ব্যবস্থা', 'actions intended to punish', 'Critics argue that purely punitive measures rarely address root causes.', 'advanced', v_economy_and_work),
    ('to get away with something', 'idiom', 'পার পেয়ে যাওয়া', 'to avoid punishment for wrongdoing', 'For years, the fraud went unnoticed and he got away with it.', 'advanced', v_economy_and_work),
    ('loophole', 'noun', 'আইনি ফাঁক', 'a gap or ambiguity in the law', 'The company exploited a legal loophole to avoid taxes.', 'advanced', v_economy_and_work),
    ('to uphold the law', 'collocation', 'আইন সমুন্নত রাখা', 'to make sure the law is respected and followed', 'Police officers are sworn to uphold the law impartially. (50', 'advanced', v_economy_and_work),
    ('economic growth', 'noun phrase', 'অর্থনৈতিক প্রবৃদ্ধি', 'an increase in a country''s production of goods and services', 'Economic growth has slowed amid global uncertainty.', 'advanced', v_economy_and_work),
    ('disposable income', 'noun phrase', 'ব্যয়যোগ্য আয়', 'income left after essential expenses', 'Rising prices have squeezed households'' disposable income.', 'advanced', v_economy_and_work),
    ('job creation', 'noun phrase', 'কর্মসংস্থান সৃষ্টি', 'the generation of new employment opportunities', 'The new factory is expected to boost job creation in the region.', 'advanced', v_economy_and_work),
    ('a burden on taxpayers', 'noun phrase', 'করদাতাদের উপর বোঝা', 'a cost that falls on those who pay tax', 'Bailing out failing companies places a heavy burden on taxpayers.', 'advanced', v_economy_and_work),
    ('cost of living', 'noun phrase', 'জীবনযাত্রার ব্যয়', 'the amount of money needed to cover basic expenses', 'The cost of living has risen sharply over the past two years.', 'advanced', v_economy_and_work),
    ('inflation', 'noun', 'মুদ্রাস্ফীতি', 'a general rise in prices over time', 'Inflation has eroded the purchasing power of ordinary households.', 'advanced', v_economy_and_work),
    ('recession', 'noun', 'মন্দা', 'a period of economic decline', 'The country entered a recession after two quarters of negative growth.', 'advanced', v_economy_and_work),
    ('unemployment rate', 'noun phrase', 'বেকারত্বের হার', 'the percentage of the workforce without a job', 'The unemployment rate remains stubbornly high among young graduates.', 'advanced', v_economy_and_work),
    ('minimum wage', 'noun phrase', 'সর্বনিম্ন মজুরি', 'the lowest legally permitted pay rate', 'Raising the minimum wage remains a contentious policy debate.', 'advanced', v_economy_and_work),
    ('income inequality', 'noun phrase', 'আয় বৈষম্য', 'the unequal distribution of income across a population', 'Income inequality has widened significantly over the past decade.', 'advanced', v_economy_and_work),
    ('purchasing power', 'noun phrase', 'ক্রয়ক্ষমতা', 'the value of money in terms of what it can buy', 'Wages have not kept pace, eroding workers'' purchasing power.', 'advanced', v_economy_and_work),
    ('subsidy', 'noun', 'ভর্তুকি', 'financial support given by the government', 'Farmers rely heavily on government subsidies during poor harvests.', 'advanced', v_economy_and_work),
    ('foreign investment', 'noun phrase', 'বৈদেশিক বিনিয়োগ', 'capital invested by companies or individuals from abroad', 'Foreign investment has driven much of the country''s industrial growth.', 'advanced', v_economy_and_work),
    ('entrepreneurs hip', 'noun', 'উদ্যোক্তা মনোভাব', 'the activity of starting and running a business', 'The government has launched schemes to encourage entrepreneurship among youth.', 'advanced', v_economy_and_work),
    ('startup', 'noun', 'নবপ্রতিষ্ঠিত ব্যবসা', 'a newly established business, typically small', 'The city has become a hub for technology startups.', 'advanced', v_economy_and_work),
    ('redundancy', 'noun', 'চাকরি বাতিলকরণ', 'the loss of a job because it is no longer needed', 'Hundreds of workers faced redundancy when the factory closed.', 'advanced', v_economy_and_work),
    ('job security', 'noun phrase', 'চাকরির নিরাপত্তা', 'the likelihood of keeping one''s job', 'Job security in the gig economy is notoriously low.', 'advanced', v_economy_and_work),
    ('gig economy', 'noun phrase', 'অস্থায়ী কাজের অর্থনীতি', 'a labour market of short-term, freelance work', 'The gig economy offers flexibility but often lacks stable benefits.', 'advanced', v_economy_and_work),
    ('workforce', 'noun', 'কর্মশক্তি', 'the total number of people employed or available to work', 'Automation could displace a significant share of the workforce.', 'advanced', v_economy_and_work),
    ('overqualified', 'adjective', 'অতিরিক্ত-যোগ্য', 'having more qualifications than a job requires', 'Many graduates find themselves overqualified for entry-level positions.', 'advanced', v_economy_and_work),
    ('skills shortage', 'noun phrase', 'দক্ষতার ঘাটতি', 'a lack of workers with the necessary skills', 'The construction industry is facing a severe skills shortage.', 'advanced', v_economy_and_work),
    ('wage gap', 'noun phrase', 'বেতন বৈষম্য', 'the difference in pay between groups, e.g. men and women', 'Closing the wage gap remains a slow and uneven process.', 'advanced', v_economy_and_work),
    ('bureaucracy', 'noun', 'আমলাতন্ত্র', 'a system of complex administrative procedures', 'Excessive bureaucracy discourages small businesses from expanding.', 'advanced', v_economy_and_work),
    ('taxation', 'noun', 'করব্যবস্থা', 'the system of imposing taxes', 'Progressive taxation is intended to reduce income inequality.', 'advanced', v_economy_and_work),
    ('budget deficit', 'noun phrase', 'বাজেট ঘাটতি', 'when spending exceeds revenue', 'The government''s budget deficit has widened due to increased spending.', 'advanced', v_economy_and_work),
    ('trade deficit', 'noun phrase', 'বাণিজ্য ঘাটতি', 'when a country imports more than it exports', 'The trade deficit has raised concerns about economic dependency.', 'advanced', v_economy_and_work),
    ('consumer spending', 'noun phrase', 'ভোক্তা ব্যয়', 'the total money spent by households on goods and services', 'Consumer spending typically falls during periods of high inflation.', 'advanced', v_economy_and_work),
    ('financial stability', 'noun phrase', 'আর্থিক স্থিতিশীলতা', 'a secure and reliable economic situation', 'Central banks aim to maintain financial stability during crises.', 'advanced', v_economy_and_work),
    ('outsourcing', 'noun', 'আউটসোর্সিং', 'hiring an outside firm to handle certain operations', 'Outsourcing manufacturing has cut costs but reduced local jobs.', 'advanced', v_economy_and_work),
    ('supply chain', 'noun phrase', 'সরবরাহ শৃঙ্খল', 'the network involved in producing and delivering a product', 'The pandemic exposed serious weaknesses in global supply chains.', 'advanced', v_economy_and_work),
    ('a booming economy', 'collocation', 'রমরমা অর্থনীতি', 'a rapidly growing and prosperous economy', 'A booming economy attracted workers from neighbouring regions.', 'advanced', v_economy_and_work),
    ('to make ends meet', 'idiom', 'সংসার চালানো', 'to have just enough money to live on', 'Many families are struggling to make ends meet.', 'advanced', v_economy_and_work),
    ('to tighten one''s belt', 'idiom', 'খরচ কমানো', 'to spend less money than before', 'Households have had to tighten their belts amid rising prices.', 'advanced', v_economy_and_work),
    ('to be laid off', 'collocation', 'চাকরিচ্যুত হওয়া', 'to lose one''s job due to company decisions', 'Thousands of employees were laid off during the restructuring.', 'advanced', v_economy_and_work),
    ('to climb the corporate ladder', 'idiom', 'পদোন্নতির সিঁড়ি বেয়ে ওঠা', 'to be promoted through a company''s ranks', 'She worked tirelessly to climb the corporate ladder.', 'advanced', v_economy_and_work),
    ('a steady income', 'collocation', 'স্থির আয়', 'a reliable and consistent source of income', 'A steady income allows families to plan for the future.', 'advanced', v_economy_and_work),
    ('economic downturn', 'noun phrase', 'অর্থনৈতিক মন্দা', 'a decline in economic activity', 'Small businesses are the first to suffer during an economic downturn.', 'advanced', v_economy_and_work),
    ('venture capital', 'noun phrase', 'ভেঞ্চার ক্যাপিটাল', 'funding provided to promising startups', 'The startup secured venture capital to expand internationally.', 'advanced', v_economy_and_work),
    ('productivity', 'noun', 'উৎপাদনশীলতা', 'the efficiency of production, output per worker', 'Remote work has had mixed effects on employee productivity.', 'advanced', v_economy_and_work),
    ('to go bankrupt', 'collocation', 'দেউলিয়া হওয়া', 'to become financially unable to pay debts', 'Several airlines went bankrupt during the crisis.', 'advanced', v_economy_and_work),
    ('stagnant wages', 'noun phrase', 'স্থবির মজুরি', 'wages that have not increased for a long time', 'Stagnant wages have failed to keep up with the cost of living.', 'advanced', v_economy_and_work),
    ('economic hardship', 'noun phrase', 'অর্থনৈতিক দুরবস্থা', 'severe financial difficulty', 'The pandemic caused widespread economic hardship.', 'advanced', v_society_and_culture),
    ('a lucrative career', 'collocation', 'লাভজনক পেশা', 'a career that pays very well', 'Many students are drawn to a lucrative career in finance.', 'advanced', v_society_and_culture),
    ('cut corners', 'idiom', 'কাজে ফাঁকি দেওয়া', 'to do something poorly to save time or money', 'The company cut corners on safety to reduce costs.', 'advanced', v_society_and_culture),
    ('underemploy ment', 'noun', 'অপর্যাপ্ত কর্মসংস্থান', 'working fewer hours or below one''s skill level', 'Underemployment is often overlooked compared with unemployment.', 'advanced', v_society_and_culture),
    ('freelance', null, 'স্বাধীনভাবে কাজ করা', 'working independently, not employed by a single company', 'More professionals are choosing to freelance rather than work full-time.', 'advanced', v_society_and_culture),
    ('a competitive salary', 'collocation', 'প্রতিযোগিতামূলক বেতন', 'a salary comparable to or better than the market rate', 'The company offers a competitive salary to attract top talent.', 'advanced', v_society_and_culture),
    ('economic resilience', 'noun phrase', 'অর্থনৈতিক সহনশীলতা', 'the ability of an economy to withstand shocks', 'Diversifying exports strengthens a country''s economic resilience.', 'advanced', v_society_and_culture),
    ('to break even', 'idiom', 'লাভ-ক্ষতি সমান হওয়া', 'to make neither a profit nor a loss', 'The business finally broke even after eighteen months.', 'advanced', v_society_and_culture),
    ('to downsize', 'verb', 'জনবল কমানো', 'to reduce the size of a company or its workforce', 'The firm was forced to downsize after losing its biggest client. (45', 'advanced', v_society_and_culture),
    ('social cohesion', 'noun phrase', 'সামাজিক সংহতি', 'the sense of connection and solidarity within a society', 'Community events help strengthen social cohesion in diverse neighbourhoods.', 'advanced', v_society_and_culture),
    ('social mobility', 'noun phrase', 'সামাজিক গতিশীলতা', 'the ability to move between social classes', 'Free education is often seen as a key driver of social mobility.', 'advanced', v_society_and_culture),
    ('cultural identity', 'noun phrase', 'সাংস্কৃতিক পরিচয়', 'a sense of belonging to a particular culture', 'Migration can put a person''s cultural identity under pressure.', 'advanced', v_society_and_culture),
    ('income inequality', 'noun phrase', 'আয় বৈষম্য', 'unequal distribution of income across society', 'Income inequality tends to widen during periods of rapid growth.', 'advanced', v_society_and_culture),
    ('generation gap', 'noun phrase', 'প্রজন্মের ব্যবধান', 'differences in attitudes between older and younger generations', 'The generation gap is often most visible in attitudes towards technology.', 'advanced', v_society_and_culture),
    ('social norms', 'noun phrase', 'সামাজিক রীতিনীতি', 'unwritten rules of behaviour within a society', 'Social norms around marriage have shifted considerably in recent decades.', 'advanced', v_society_and_culture),
    ('traditional values', 'noun phrase', 'ঐতিহ্যবাহী মূল্যবোধ', 'beliefs and customs passed down through generations', 'Rapid urbanisation has challenged many traditional values.', 'advanced', v_society_and_culture),
    ('nuclear family', 'noun phrase', 'একক পরিবার', 'a family unit of parents and children only', 'The nuclear family has largely replaced the extended family in cities.', 'advanced', v_society_and_culture),
    ('extended family', 'noun phrase', 'যৌথ পরিবার', 'a family including relatives beyond parents and children', 'In many rural communities, the extended family still lives together.', 'advanced', v_society_and_culture),
    ('gender equality', 'noun phrase', 'লিঙ্গ সমতা', 'equal rights and opportunities regardless of gender', 'Gender equality in the workplace remains an unfinished goal.', 'advanced', v_society_and_culture),
    ('social stigma', 'noun phrase', 'সামাজিক কলঙ্ক', 'disapproval attached to a particular circumstance', 'Mental illness still carries considerable social stigma in many cultures.', 'advanced', v_society_and_culture),
    ('assimilation', 'noun', 'আত্তীকরণ', 'the process of adapting to a new culture', 'Assimilation policies have often come at the cost of cultural diversity.', 'advanced', v_society_and_culture),
    ('multiculturalism', 'noun', 'বহুসংস্কৃতিবাদ', 'the coexistence of diverse cultures within a society', 'Multiculturalism is often cited as a strength of large global cities.', 'advanced', v_society_and_culture),
    ('cultural heritage', 'noun phrase', 'সাংস্কৃতিক ঐতিহ্য', 'traditions, monuments and practices inherited from the past', 'Efforts are underway to preserve the city''s cultural heritage.', 'advanced', v_society_and_culture),
    ('a close-knit community', 'collocation', 'ঘনিষ্ঠ সম্প্রদায়', 'a community with strong social bonds', 'Growing up in a close-knit community shaped her sense of belonging.', 'advanced', v_society_and_culture),
    ('generational divide', 'noun phrase', 'প্রজন্মগত বিভাজন', 'a significant difference in views between generations', 'The generational divide is stark on issues such as climate change.', 'advanced', v_society_and_culture),
    ('social hierarchy', 'noun phrase', 'সামাজিক স্তরবিন্যাস', 'a system of ranked social classes', 'Traditional social hierarchy has weakened considerably in urban areas.', 'advanced', v_society_and_culture),
    ('tight-knit', 'adjective', 'ঘনিষ্ঠভাবে সংযুক্ত', 'closely connected, with strong relationships', 'The village remains a tight-knit community despite modernisation.', 'advanced', v_society_and_culture),
    ('collectivist society', 'noun phrase', 'সমষ্টিবাদী সমাজ', 'a society valuing the group over the individual', 'Bangladesh is often described as a broadly collectivist society.', 'advanced', v_society_and_culture),
    ('individualism', 'noun', 'ব্যক্তিস্বাতন্ত্র্যবাদ', 'the value placed on personal independence', 'Western societies are often characterised by a stronger sense of individualism.', 'advanced', v_society_and_culture),
    ('urbanisation', 'noun', 'নগরায়ণ', 'the growth of cities as populations shift from rural areas', 'Rapid urbanisation has placed enormous strain on city infrastructure.', 'advanced', v_society_and_culture),
    ('demographic shift', 'noun phrase', 'জনতাত্ত্বিক পরিবর্তন', 'a significant change in population characteristics', 'The demographic shift towards an older population affects healthcare planning.', 'advanced', v_society_and_culture),
    ('social welfare', 'noun phrase', 'সামাজিক কল্যাণ', 'government support for citizens in need', 'Social welfare programmes provide a safety net for vulnerable families.', 'advanced', v_society_and_culture),
    ('community spirit', 'noun phrase', 'সম্প্রদায় চেতনা', 'a sense of togetherness among community members', 'The flood response showed a remarkable community spirit.', 'advanced', v_society_and_culture),
    ('gender roles', 'noun phrase', 'লিঙ্গভিত্তিক ভূমিকা', 'expected behaviours based on gender', 'Traditional gender roles are gradually being questioned by younger generations.', 'advanced', v_society_and_culture),
    ('a melting pot', 'idiom', 'সংস্কৃতির মিশ্রণস্থল', 'a place where many cultures blend together', 'The city has long been described as a melting pot of cultures.', 'advanced', v_society_and_culture),
    ('to break with tradition', 'collocation', 'প্রথা ভেঙে ফেলা', 'to stop following an established custom', 'More couples are breaking with tradition and choosing not to marry.', 'advanced', v_society_and_culture),
    ('social fabric', 'noun phrase', 'সামাজিক কাঠামো', 'the underlying structure of a society', 'Mass migration can strain the social fabric of host communities.', 'advanced', v_society_and_culture),
    ('a rite of passage', 'idiom', 'জীবনের গুরুত্বপূর্ণ অনুষ্ঠান', 'a ceremony or event marking a significant life stage', 'In many cultures, graduation is treated as a rite of passage.', 'advanced', v_society_and_culture),
    ('upward mobility', 'noun phrase', 'উর্ধ্বমুখী সামাজিক গতিশীলতা', 'the ability to improve one''s social or economic status', 'Education remains the most reliable path to upward mobility.', 'advanced', v_society_and_culture),
    ('deeply rooted', 'adjective', 'গভীরভাবে প্রোথিত', 'firmly established, especially over a long time', 'These customs are deeply rooted in the region''s history.', 'advanced', v_society_and_culture),
    ('social exclusion', 'noun phrase', 'সামাজিক বহিষ্করণ', 'being denied full participation in society', 'Poverty often leads to social exclusion in unexpected ways.', 'advanced', v_society_and_culture),
    ('civic responsibility', 'noun phrase', 'নাগরিক দায়িত্ব', 'the duty of citizens to contribute to society', 'Voting is widely regarded as a basic civic responsibility.', 'advanced', v_society_and_culture),
    ('a shift in attitudes', 'collocation', 'দৃষ্টিভঙ্গির পরিবর্তন', 'a change in how people generally think about something', 'There has been a marked shift in attitudes towards mental health.', 'advanced', v_society_and_culture),
    ('communal harmony', 'noun phrase', 'সাম্প্রদায়িক সম্প্রীতি', 'peaceful coexistence between different communities', 'Interfaith events have helped promote communal harmony.', 'advanced', v_society_and_culture),
    ('socioeconomic status', 'noun phrase', 'আর্থ-সামাজিক অবস্থান', 'a person''s social and economic position', 'Access to quality healthcare often depends on socioeconomic status.', 'advanced', v_society_and_culture),
    ('a taboo subject', 'noun phrase', 'নিষিদ্ধ বিষয়', 'a topic considered inappropriate to discuss openly', 'Mental health used to be something of a taboo subject.', 'advanced', v_society_and_culture),
    ('norms and customs', 'collocation', 'রীতিনীতি ও প্রথা', 'the accepted practices of a society', 'Visitors are expected to respect local norms and customs.', 'advanced', v_society_and_culture),
    ('a sense of belonging', 'collocation', 'অন্তর্ভুক্তির অনুভূতি', 'a feeling of being accepted as part of a group', 'Community centres give newcomers a sense of belonging.', 'advanced', v_government_and_politics),
    ('intergeneratio nal', 'adjective', 'আন্তঃপ্রজন্মীয়', 'involving different generations', 'Intergenerational households were once the norm across the region.', 'advanced', v_government_and_politics),
    ('xenophobia', 'noun', 'বিদেশি-ভীতি', 'fear or dislike of people from other countries', 'Rising xenophobia has been linked to economic insecurity.', 'advanced', v_government_and_politics),
    ('cultural exchange', 'noun phrase', 'সাংস্কৃতিক আদান-প্রদান', 'the sharing of ideas and customs between cultures', 'Student exchange programmes promote genuine cultural exchange.', 'advanced', v_government_and_politics),
    ('patriarchal society', 'noun phrase', 'পিতৃতান্ত্রিক সমাজ', 'a society dominated by male authority', 'Reforms have slowly begun to challenge patriarchal society structures.', 'advanced', v_government_and_politics),
    ('communal living', 'noun phrase', 'সাম্প্রদায়িক জীবনযাপন', 'living arrangements shared among a group', 'Communal living was once common in extended family compounds.', 'advanced', v_government_and_politics),
    ('a double-edged sword', 'idiom', 'দ্বিধারী তরবারি', 'something with both good and bad consequences', 'Social media is very much a double-edged sword for young people. (35', 'advanced', v_government_and_politics),
    ('public policy', 'noun phrase', 'সরকারি নীতি', 'a course of action adopted by government', 'Public policy on housing needs urgent reform.', 'advanced', v_government_and_politics),
    ('legislation', 'noun', 'আইন প্রণয়ন', 'laws formally passed by a governing body', 'New legislation aims to curb pollution from factories.', 'advanced', v_government_and_politics),
    ('accountability', 'noun', 'জবাবদিহিতা', 'being responsible and answerable for actions', 'Greater accountability is needed among elected officials.', 'advanced', v_government_and_politics),
    ('infrastructure', 'noun', 'অবকাঠামো', 'basic physical systems such as roads and utilities', 'Investment in infrastructure is essential for economic growth.', 'advanced', v_government_and_politics),
    ('welfare state', 'noun phrase', 'কল্যাণ রাষ্ট্র', 'a system where government provides for citizens'' basic needs', 'The welfare state provides a safety net during hard times.', 'advanced', v_government_and_politics),
    ('budget allocation', 'noun phrase', 'বাজেট বরাদ্দ', 'the distribution of government funds', 'Budget allocation to healthcare has increased this year.', 'advanced', v_government_and_politics),
    ('civil liberties', 'noun phrase', 'নাগরিক অধিকার', 'basic rights and freedoms of individuals', 'New surveillance laws have raised concerns about civil liberties.', 'advanced', v_government_and_politics),
    ('corruption', 'noun', 'দুর্নীতি', 'dishonest or fraudulent conduct by those in power', 'Corruption remains one of the biggest obstacles to development.', 'advanced', v_government_and_politics),
    ('transparency', 'noun', 'স্বচ্ছতা', 'openness and clarity in decision-making', 'Transparency in public spending helps build citizens'' trust.', 'advanced', v_government_and_politics),
    ('decentralisati on', 'noun', 'বিকেন্দ্রীকরণ', 'transferring power away from a central authority', 'Decentralisation has given local governments more decision-making power.', 'advanced', v_government_and_politics),
    ('regulatory body', 'noun phrase', 'নিয়ন্ত্রক সংস্থা', 'an organisation that oversees a particular industry', 'The regulatory body fined the company for safety violations.', 'advanced', v_government_and_politics),
    ('grassroots movement', 'noun phrase', 'তৃণমূল আন্দোলন', 'a movement driven by ordinary citizens', 'The reform began as a grassroots movement rather than government policy.', 'advanced', v_government_and_politics),
    ('bipartisan', 'adjective', 'দ্বিদলীয়', 'supported by two opposing political parties', 'The bill passed with rare bipartisan support.', 'advanced', v_government_and_politics),
    ('electoral reform', 'noun phrase', 'নির্বাচনী সংস্কার', 'changes to how elections are conducted', 'Electoral reform has been debated for over a decade.', 'advanced', v_government_and_politics),
    ('public sector', 'noun phrase', 'সরকারি খাত', 'the part of the economy controlled by the state', 'Wages in the public sector have failed to keep pace with inflation.', 'advanced', v_government_and_politics),
    ('red tape', 'idiom', 'লালফিতার দৌরাত্ম্য', 'excessive bureaucracy that slows down processes', 'Small businesses often struggle with red tape when registering.', 'advanced', v_government_and_politics),
    ('a policy overhaul', 'collocation', 'নীতি সংস্কার', 'a complete revision of an existing policy', 'The education system is in need of a serious policy overhaul.', 'advanced', v_government_and_politics),
    ('public trust', 'noun phrase', 'জনগণের আস্থা', 'confidence that citizens have in their institutions', 'Repeated scandals have eroded public trust in government.', 'advanced', v_government_and_politics),
    ('vested interests', 'noun phrase', 'স্বার্থান্বেষী মহল', 'personal or group interests influencing decisions', 'Reform has stalled because of powerful vested interests.', 'advanced', v_government_and_politics),
    ('to hold someone accountable', 'collocation', 'জবাবদিহি করানো', 'to make someone answerable for their actions', 'Voters expect to hold their representatives accountable.', 'advanced', v_government_and_politics),
    ('subsidised housing', 'noun phrase', 'ভর্তুকিযুক্ত আবাসন', 'housing supported financially by the government', 'Subsidised housing has helped thousands of low-income families.', 'advanced', v_government_and_politics),
    ('a policy shift', 'collocation', 'নীতি পরিবর্তন', 'a change in government approach or direction', 'The policy shift towards renewable energy came after years of pressure.', 'advanced', v_government_and_politics),
    ('good governance', 'noun phrase', 'সুশাসন', 'effective, fair and transparent administration', 'Good governance is essential for sustainable development.', 'advanced', v_government_and_politics),
    ('enact a law', 'collocation', 'আইন পাস করা', 'to pass a law formally', 'Parliament enacted the law after months of debate.', 'advanced', v_government_and_politics),
    ('public consultation', 'noun phrase', 'জনমত যাচাই', 'seeking public opinion before making a decision', 'A public consultation was held before the new road was approved.', 'advanced', v_government_and_politics),
    ('sweeping reforms', 'collocation', 'ব্যাপক সংস্কার', 'wide-ranging and significant changes', 'The new administration promised sweeping reforms to the tax system.', 'advanced', v_government_and_politics),
    ('local governance', 'noun phrase', 'স্থানীয় প্রশাসন', 'administration at the community or regional level', 'Strong local governance improves the delivery of basic services.', 'advanced', v_government_and_politics),
    ('an uphill battle', 'idiom', 'কঠিন সংগ্রাম', 'a difficult struggle to achieve something', 'Reforming the healthcare system has proven an uphill battle.', 'advanced', v_government_and_politics),
    ('a policy loophole', 'noun phrase', 'নীতির ফাঁকফোকর', 'a gap or weakness in a policy that can be exploited', 'Companies exploited a policy loophole to avoid regulation.', 'advanced', v_media_and_advertising),
    ('checks and balances', 'idiom', 'ক্ষমতার ভারসাম্য ব্যবস্থা', 'a system preventing any one branch of power from dominating', 'Checks and balances are essential to prevent abuse of power.', 'advanced', v_media_and_advertising),
    ('public expenditure', 'noun phrase', 'সরকারি ব্যয়', 'government spending on public services', 'Public expenditure on education has risen this fiscal year.', 'advanced', v_media_and_advertising),
    ('a landmark decision', 'collocation', 'যুগান্তকারী সিদ্ধান্ত', 'a decision that sets an important precedent', 'The court''s landmark decision changed labour law for decades.', 'advanced', v_media_and_advertising),
    ('policy implementation', 'noun phrase', 'নীতি বাস্তবায়ন', 'putting a policy into practice', 'Poor policy implementation often undermines otherwise sound ideas.', 'advanced', v_media_and_advertising),
    ('advocacy group', 'noun phrase', 'স্বার্থরক্ষা সংগঠন', 'an organisation that campaigns for a cause', 'The advocacy group lobbied successfully for stricter emissions laws.', 'advanced', v_media_and_advertising),
    ('a watchdog organisation', 'noun phrase', 'নজরদারি সংস্থা', 'a group that monitors institutions for wrongdoing', 'A watchdog organisation exposed the misuse of public funds. (35', 'advanced', v_media_and_advertising),
    ('mass media', 'noun phrase', 'গণমাধ্যম', 'media reaching a large audience, e.g. TV, newspapers', 'Mass media plays a powerful role in shaping public opinion.', 'advanced', v_media_and_advertising),
    ('misinformation', 'noun', 'ভুল তথ্য', 'false information spread regardless of intent to deceive', 'Misinformation about health spread rapidly during the outbreak.', 'advanced', v_media_and_advertising),
    ('disinformation', 'noun', 'অপতথ্য', 'false information deliberately spread to deceive', 'The report accused several accounts of spreading disinformation.', 'advanced', v_media_and_advertising),
    ('censorship', 'noun', 'সেন্সরশিপ', 'the suppression of information by authorities', 'Censorship of the press remains a contentious issue.', 'advanced', v_media_and_advertising),
    ('freedom of expression', 'noun phrase', 'মতপ্রকাশের স্বাধীনতা', 'the right to express opinions without restraint', 'Freedom of expression must be balanced against the harm of hate speech.', 'advanced', v_media_and_advertising),
    ('sensationalism', 'noun', 'চাঞ্চল্যকরভাবে উপস্থাপন', 'presenting news in a shocking or exaggerated way to attract attention', 'Some outlets rely on sensationalism to boost viewership.', 'advanced', v_media_and_advertising),
    ('media bias', 'noun phrase', 'গণমাধ্যমের পক্ষপাত', 'unfair or one-sided reporting', 'Accusations of media bias have undermined public trust in journalism.', 'advanced', v_media_and_advertising),
    ('subliminal advertising', 'noun phrase', 'অবচেতন বিজ্ঞাপন', 'advertising designed to influence people unconsciously', 'Subliminal advertising techniques are banned in many countries.', 'advanced', v_media_and_advertising),
    ('consumerism', 'noun', 'ভোগবাদ', 'a strong emphasis on buying and consuming goods', 'Advertising fuels consumerism by creating a constant sense of need.', 'advanced', v_media_and_advertising),
    ('brand loyalty', 'noun phrase', 'ব্র্যান্ড আনুগত্য', 'a consumer''s continued preference for a particular brand', 'Companies invest heavily in campaigns designed to build brand loyalty.', 'advanced', v_media_and_advertising),
    ('target audience', 'noun phrase', 'লক্ষ্য দর্শক', 'the specific group an advertisement is aimed at', 'The campaign was carefully designed for a younger target audience.', 'advanced', v_media_and_advertising),
    ('influencer marketing', 'noun phrase', 'প্রভাবক বিপণন', 'promoting products through popular social media figures', 'Influencer marketing now rivals traditional advertising in reach.', 'advanced', v_media_and_advertising),
    ('echo chamber', 'noun phrase', 'একই মতের প্রতিধ্বনি বলয়', 'an environment where people only encounter similar views', 'Social media algorithms can trap users in an echo chamber.', 'advanced', v_media_and_advertising),
    ('fact-checking', 'noun', 'তথ্য যাচাই', 'verifying the accuracy of claims', 'Reputable news organisations rely on rigorous fact-checking.', 'advanced', v_media_and_advertising),
    ('clickbait', 'noun', 'ক্লিকবেইট', 'sensational headlines designed to attract clicks', 'Clickbait headlines often fail to deliver on their promise.', 'advanced', v_media_and_advertising),
    ('deepfake', 'noun', 'ডিপফেক', 'a fabricated video or audio created using AI', 'Deepfake technology poses a serious threat to public trust in media.', 'advanced', v_media_and_advertising),
    ('subscription-based', 'adjective', 'সাবস্ক্রিপশন-ভিত্তিক', 'requiring regular payment for access', 'Many news outlets have shifted to a subscription-based model.', 'advanced', v_media_and_advertising),
    ('press freedom', 'noun phrase', 'সংবাদমাধ্যমের স্বাধীনতা', 'the right of journalists to report without government interference', 'Press freedom is often the first casualty of political instability.', 'advanced', v_media_and_advertising),
    ('a media frenzy', 'collocation', 'গণমাধ্যমের হুড়োহুড়ি', 'intense and excessive media coverage of an event', 'The scandal triggered a media frenzy that lasted for weeks.', 'advanced', v_media_and_advertising),
    ('persuasive advertising', 'noun phrase', 'প্ররোচনামূলক বিজ্ঞাপন', 'advertising designed to convince consumers to buy', 'Persuasive advertising often exploits emotional rather than rational appeal.', 'advanced', v_media_and_advertising),
    ('media literacy', 'noun phrase', 'গণমাধ্যম সাক্ষরতা', 'the ability to critically analyse media content', 'Media literacy should be taught as part of the school curriculum.', 'advanced', v_media_and_advertising),
    ('a viral campaign', 'collocation', 'ভাইরাল প্রচারণা', 'a marketing campaign that spreads rapidly online', 'The charity''s viral campaign raised millions within days.', 'advanced', v_media_and_advertising),
    ('product placement', 'noun phrase', 'পণ্য স্থাপন (বিজ্ঞাপন)', 'featuring a product within a film or show for advertising', 'Product placement has become a subtle but effective form of advertising.', 'advanced', v_media_and_advertising),
    ('gatekeeping', 'noun', 'তথ্যপ্রবাহ নিয়ন্ত্রণ', 'controlling what information reaches the public', 'Editorial gatekeeping has weakened as social media has grown.', 'advanced', v_media_and_advertising),
    ('a slanted report', 'collocation', 'পক্ষপাতদুষ্ট প্রতিবেদন', 'a report that presents a biased view', 'Critics dismissed the article as a slanted report.', 'advanced', v_media_and_advertising),
    ('paparazzi', 'noun', 'পাপারাজ্জি', 'photographers who aggressively pursue celebrities', 'Paparazzi have long been criticised for invading celebrities'' privacy.', 'advanced', v_media_and_advertising),
    ('shape public opinion', 'collocation', 'জনমত গঠন করা', 'to influence what people generally think', 'Newspapers have historically played a role in shaping public opinion.', 'advanced', v_media_and_advertising),
    ('advertorial', 'noun', 'বিজ্ঞাপনী নিবন্ধ', 'an advertisement written to look like editorial content', 'Readers often struggle to distinguish an advertorial from genuine journalism.', 'advanced', v_travel_and_tourism),
    ('a credible source', 'noun phrase', 'বিশ্বাসযোগ্য উৎস', 'a source of information that can be trusted', 'Students are taught to rely only on credible sources for research.', 'advanced', v_travel_and_tourism),
    ('airtime', 'noun', 'সম্প্রচার সময়', 'time allocated on television or radio', 'The candidate received far more airtime than her rivals.', 'advanced', v_travel_and_tourism);
end $$;
