-- ============================================================
-- 026_ielts_vocabulary_words_400_599.sql
-- Content batch: IELTS Band 8 vocabulary words 400-599,
-- transcribed from "1000 Essential Words for Band 8" (word, part of
-- speech, definition, and example extracted from the source; Bangla
-- meanings authored fresh, since the PDF's own Bangla text layer is
-- corrupted at the font level -- see migration notes).
-- ============================================================

do $$
declare
  v_travel_and_tourism uuid;
  v_family_and_relationships uuid;
  v_urbanisation_and_housing uuid;
  v_science_and_space uuid;
  v_art_and_sport uuid;
  v_globalisation uuid;
  v_opinion_and_stance uuid;
begin
  select cn.id into v_travel_and_tourism from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'travel-and-tourism';
  select cn.id into v_family_and_relationships from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'family-and-relationships';
  select cn.id into v_urbanisation_and_housing from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'urbanisation-and-housing';
  select cn.id into v_science_and_space from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'science-and-space';
  select cn.id into v_art_and_sport from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'art-and-sport';
  select cn.id into v_globalisation from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'globalisation';
  select cn.id into v_opinion_and_stance from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'opinion-and-stance';

  insert into vocabulary (word, part_of_speech, bangla_meaning, english_definition, example_sentence, difficulty, node_id) values
    ('take something at face value', 'idiom', 'যাচাই ছাড়া গ্রহণ করা', 'to accept something without questioning it', 'It is unwise to take every headline at face value.', 'advanced', v_travel_and_tourism),
    ('streaming platform', 'noun phrase', 'স্ট্রিমিং প্ল্যাটফর্ম', 'a service delivering video or audio content online', 'Streaming platforms have largely replaced traditional television viewing.', 'advanced', v_travel_and_tourism),
    ('paywall', 'noun', 'পেওয়াল', 'a system requiring payment to access online content', 'Many quality newspapers now sit behind a paywall.', 'advanced', v_travel_and_tourism),
    ('tabloid journalism', 'noun phrase', 'ট্যাবলয়েড সাংবাদিকতা', 'sensational, often gossip-focused journalism', 'Tabloid journalism prioritises entertainment value over accuracy. (35', 'advanced', v_travel_and_tourism),
    ('mass tourism', 'noun phrase', 'গণপর্যটন', 'tourism involving very large numbers of visitors', 'Mass tourism has put enormous pressure on the island''s infrastructure.', 'advanced', v_travel_and_tourism),
    ('off the beaten track', 'idiom', 'অপ্রচলিত/কম-পরিচিত পথ', 'somewhere not often visited by tourists', 'They preferred destinations off the beaten track to crowded resorts.', 'advanced', v_travel_and_tourism),
    ('cultural immersion', 'noun phrase', 'সাংস্কৃতিক নিমজ্জন', 'fully experiencing another culture', 'Homestays offer travellers genuine cultural immersion.', 'advanced', v_travel_and_tourism),
    ('eco-tourism', 'noun', 'পরিবেশবান্ধব পর্যটন', 'tourism focused on conservation and low environmental impact', 'Eco-tourism generates income while protecting fragile ecosystems.', 'advanced', v_travel_and_tourism),
    ('tourist trap', 'noun phrase', 'পর্যটক ফাঁদ', 'a place that overcharges tourists', 'The restaurant near the monument turned out to be a tourist trap.', 'advanced', v_travel_and_tourism),
    ('local economy', 'noun phrase', 'স্থানীয় অর্থনীতি', 'the economy of a particular region', 'Tourism revenue is vital to the local economy.', 'advanced', v_travel_and_tourism),
    ('heritage site', 'noun phrase', 'ঐতিহ্যবাহী স্থান', 'a place of historical or cultural significance', 'The heritage site attracts thousands of visitors every year.', 'advanced', v_travel_and_tourism),
    ('overtourism', 'noun', 'অতিমাত্রার পর্যটন', 'tourism so excessive it harms a destination', 'Overtourism has forced some cities to limit visitor numbers.', 'advanced', v_travel_and_tourism),
    ('a home away from home', 'idiom', 'দ্বিতীয় ঘরের মতো', 'a place where one feels as comfortable as at home', 'The guesthouse quickly became a home away from home.', 'advanced', v_travel_and_tourism),
    ('wanderlust', 'noun', 'ভ্রমণপিপাসা', 'a strong desire to travel', 'A childhood spent moving cities left her with lasting wanderlust.', 'advanced', v_travel_and_tourism),
    ('backpacking', 'noun', 'পিঠব্যাগ নিয়ে ভ্রমণ', 'travelling cheaply with minimal luggage', 'Backpacking through South-East Asia is a rite of passage for many students.', 'advanced', v_travel_and_tourism),
    ('visa restrictions', 'noun phrase', 'ভিসা নিষেধাজ্ঞা', 'legal limitations on entering a country', 'Visa restrictions can significantly discourage international tourism.', 'advanced', v_travel_and_tourism),
    ('a bucket-list destination', 'collocation', 'স্বপ্নের ভ্রমণ গন্তব্য', 'a place people especially want to visit', 'The Northern Lights are a bucket- list destination for many travellers.', 'advanced', v_travel_and_tourism),
    ('tourist influx', 'noun phrase', 'পর্যটকদের ঢল', 'a large arrival of tourists', 'The seasonal tourist influx strains the town''s water supply.', 'advanced', v_travel_and_tourism),
    ('a scenic route', 'collocation', 'মনোরম পথ', 'a route offering beautiful views', 'They chose the scenic route along the coast rather than the motorway.', 'advanced', v_travel_and_tourism),
    ('hospitality industry', 'noun phrase', 'আতিথেয়তা শিল্প', 'businesses providing accommodation and food to travellers', 'The hospitality industry was among the hardest hit during the pandemic.', 'advanced', v_travel_and_tourism),
    ('a hidden gem', 'idiom', 'লুকানো রত্ন (অজানা স্থান)', 'a wonderful but little-known place', 'The village turned out to be a hidden gem few tourists know about.', 'advanced', v_travel_and_tourism),
    ('sustainable tourism', 'noun phrase', 'টেকসই পর্যটন', 'tourism that minimises harm to the environment and culture', 'Sustainable tourism aims to protect destinations for future generations.', 'advanced', v_travel_and_tourism),
    ('cultural appropriation', 'noun phrase', 'সাংস্কৃতিক আত্মসাৎ', 'adopting elements of another culture inappropriately', 'Debates around cultural appropriation have influenced how festivals are marketed.', 'advanced', v_travel_and_tourism),
    ('a whirlwind tour', 'idiom', 'দ্রুতগতির ভ্রমণ', 'a very quick visit covering many places', 'They did a whirlwind tour of five countries in ten days.', 'advanced', v_travel_and_tourism),
    ('seasonal employment', 'noun phrase', 'মৌসুমি কর্মসংস্থান', 'jobs available only during certain times of year', 'Seasonal employment in tourism leaves many workers without income off- season.', 'advanced', v_travel_and_tourism),
    ('foreign exchange earnings', 'noun phrase', 'বৈদেশিক মুদ্রা আয়', 'income earned from foreign visitors or trade', 'Tourism is a major source of foreign exchange earnings.', 'advanced', v_travel_and_tourism),
    ('an unspoiled landscape', 'collocation', 'অক্ষত প্রাকৃতিক দৃশ্য', 'natural scenery undamaged by human activity', 'The valley remains an unspoiled landscape, largely untouched by development.', 'advanced', v_travel_and_tourism),
    ('a package holiday', 'noun phrase', 'প্যাকেজ ছুটি', 'a pre-arranged trip including flights and accommodation', 'Package holidays remain popular among first-time travellers.', 'advanced', v_travel_and_tourism),
    ('to broaden your horizons', 'idiom', 'দৃষ্টিভঙ্গি প্রসারিত করা', 'to gain new experiences and perspectives', 'Travelling alone really broadens your horizons.', 'advanced', v_travel_and_tourism),
    ('layover', 'noun', 'ট্রানজিট যাত্রাবিরতি', 'a stop between flights', 'They had a six-hour layover before their connecting flight.', 'advanced', v_travel_and_tourism),
    ('a once-in-a-lifetime experience', 'collocation', 'জীবনের একবারের অভিজ্ঞতা', 'a rare and memorable experience', 'Trekking to base camp was a once- in-a-lifetime experience for them.', 'advanced', v_travel_and_tourism),
    ('cultural sensitivity', 'noun phrase', 'সাংস্কৃতিক সংবেদনশীলতা', 'awareness and respect for other cultures', 'Tour guides receive training in cultural sensitivity.', 'advanced', v_travel_and_tourism),
    ('an all-inclusive resort', 'noun phrase', 'সর্বসুবিধাসহ রিসোর্ট', 'accommodation where meals and activities are included', 'Many families prefer an all-inclusive resort for stress-free holidays.', 'advanced', v_family_and_relationships),
    ('to soak up the atmosphere', 'collocation', 'পরিবেশ উপভোগ করা', 'to fully experience and enjoy the surrounding mood', 'They spent the evening soaking up the atmosphere of the old town.', 'advanced', v_family_and_relationships),
    ('tourism revenue', 'noun phrase', 'পর্যটন থেকে আয়', 'income generated by the tourism industry', 'Tourism revenue accounts for a significant share of the country''s GDP.', 'advanced', v_family_and_relationships),
    ('itinerary', 'noun', 'ভ্রমণসূচি', 'a planned route or schedule for a journey', 'Their itinerary included three cities in just one week.', 'advanced', v_family_and_relationships),
    ('a getaway', 'noun', 'স্বল্প ছুটির ভ্রমণ', 'a short holiday, especially somewhere relaxing', 'The couple booked a weekend getaway to the mountains.', 'advanced', v_family_and_relationships),
    ('cross-cultural understanding', 'noun phrase', 'আন্তঃসাংস্কৃতিক বোঝাপড়া', 'understanding and appreciation between different cultures', 'Travel fosters cross-cultural understanding in a way textbooks cannot.', 'advanced', v_family_and_relationships),
    ('responsible travel', 'noun phrase', 'দায়িত্বশীল ভ্রমণ', 'travel that respects local people and environments', 'Responsible travel involves minimising your impact on local communities. (35', 'advanced', v_family_and_relationships),
    ('upbringing', 'noun', 'শিশুপালন/লালনপালন', 'the way a child is cared for and raised', 'His strict upbringing shaped his disciplined approach to work.', 'advanced', v_family_and_relationships),
    ('a close bond', 'collocation', 'গভীর বন্ধন', 'a strong emotional connection between people', 'The sisters share a close bond despite living in different countries.', 'advanced', v_family_and_relationships),
    ('single-parent household', 'noun phrase', 'একক-অভিভাবক পরিবার', 'a family headed by one parent', 'Single-parent households often face greater financial strain.', 'advanced', v_family_and_relationships),
    ('parental guidance', 'noun phrase', 'অভিভাবকীয় দিকনির্দেশনা', 'advice and supervision provided by parents', 'Parental guidance remains crucial during the teenage years.', 'advanced', v_family_and_relationships),
    ('sibling rivalry', 'noun phrase', 'ভাইবোনের দ্বন্দ্ব', 'competition or conflict between brothers and sisters', 'A little sibling rivalry is a normal part of growing up.', 'advanced', v_family_and_relationships),
    ('estranged', 'adjective', 'সম্পর্কচ্যুত', 'no longer close to or in contact with', 'He had been estranged from his father for over a decade.', 'advanced', v_family_and_relationships),
    ('a strained relationship', 'collocation', 'টানাপোড়েনের সম্পর্ক', 'a difficult and tense relationship', 'Years of miscommunication led to a strained relationship between them.', 'advanced', v_family_and_relationships),
    ('to grow apart', 'collocation', 'দূরে সরে যাওয়া', 'to gradually become less close over time', 'Old friends sometimes grow apart after moving to different cities.', 'advanced', v_family_and_relationships),
    ('doting parents', 'collocation', 'অতি-আদুরে বাবা-মা', 'parents who are excessively affectionate or indulgent', 'The doting parents rarely said no to their only child.', 'advanced', v_family_and_relationships),
    ('empty nest', 'idiom', 'সন্তানহীন গৃহ (সন্তান চলে যাওয়ার পর)', 'the situation when children have left the family home', 'She struggled with the empty nest after her youngest left for university.', 'advanced', v_family_and_relationships),
    ('a supportive network', 'collocation', 'সহায়ক নেটওয়ার্ক', 'people who provide emotional or practical support', 'A supportive network of friends helped him through difficult times.', 'advanced', v_family_and_relationships),
    ('to run in the family', 'idiom', 'বংশগতভাবে চলে আসা', 'to be a trait shared across generations', 'A talent for music clearly runs in the family.', 'advanced', v_family_and_relationships),
    ('work-life balance', 'noun phrase', 'কর্ম-জীবন ভারসাম্য', 'a healthy balance between work and personal responsibilities', 'Achieving work-life balance is harder for parents of young children.', 'advanced', v_family_and_relationships),
    ('intergeneratio nal conflict', 'noun phrase', 'আন্তঃপ্রজন্মীয় দ্বন্দ্ব', 'disagreement between different generations of a family', 'Intergenerational conflict often centres on differing values.', 'advanced', v_family_and_relationships),
    ('a broken home', 'noun phrase', 'ভাঙা পরিবার', 'a family disrupted by separation or divorce', 'Children from a broken home may need additional emotional support.', 'advanced', v_family_and_relationships),
    ('to see eye to eye', 'idiom', 'একমত হওয়া', 'to agree with someone completely', 'The mother and daughter finally began to see eye to eye.', 'advanced', v_family_and_relationships),
    ('quality time', 'noun phrase', 'মানসম্পন্ন সময়', 'time spent giving full attention to a loved one', 'Busy schedules leave little quality time for the whole family.', 'advanced', v_family_and_relationships),
    ('a nurturing environment', 'collocation', 'লালনদায়ক পরিবেশ', 'a supportive and caring setting for growth', 'Children thrive best in a nurturing environment at home.', 'advanced', v_family_and_relationships),
    ('child-rearing practices', 'noun phrase', 'সন্তান লালনের পদ্ধতি', 'the methods used by parents to raise children', 'Child-rearing practices vary considerably between cultures.', 'advanced', v_family_and_relationships),
    ('to fall out with someone', 'idiom', 'ঝগড়া করে সম্পর্ক নষ্ট করা', 'to have an argument that damages a relationship', 'The brothers fell out with each other over the family business.', 'advanced', v_family_and_relationships),
    ('an overprotective parent', 'noun phrase', 'অতি-সুরক্ষামূলক অভিভাবক', 'a parent who is excessively protective', 'An overprotective parent can unintentionally limit a child''s independence.', 'advanced', v_family_and_relationships),
    ('filial duty', 'noun phrase', 'সন্তানের দায়িত্ববোধ', 'a child''s sense of obligation to their parents', 'Filial duty remains a strong value in many Asian societies.', 'advanced', v_family_and_relationships),
    ('a fractured relationship', 'collocation', 'ভাঙা সম্পর্ক', 'a relationship damaged, often beyond easy repair', 'It took years of effort to mend their fractured relationship.', 'advanced', v_family_and_relationships),
    ('a support system', 'noun phrase', 'সহায়তা ব্যবস্থা', 'people or resources that provide help in difficult times', 'A strong support system makes a huge difference during a crisis.', 'advanced', v_family_and_relationships),
    ('to bond with someone', 'collocation', 'গভীর সম্পর্ক গড়া', 'to develop a close emotional connection', 'The trip gave the whole family a chance to bond.', 'advanced', v_family_and_relationships),
    ('latchkey children', 'noun phrase', 'একা থাকা শিশু (অভিভাবক কর্মরত)', 'children who spend time unsupervised while parents work', 'Latchkey children are becoming more common as both parents work full-time.', 'advanced', v_family_and_relationships),
    ('an inseparable pair', 'collocation', 'অবিচ্ছেদ্য জুটি', 'two people who are almost always together', 'Since childhood, the two cousins have been an inseparable pair.', 'advanced', v_family_and_relationships),
    ('marital breakdown', 'noun phrase', 'বৈবাহিক বিচ্ছেদ', 'the failure of a marriage', 'Financial stress is a common cause of marital breakdown.', 'advanced', v_family_and_relationships),
    ('to drift apart', 'collocation', 'ধীরে ধীরে দূরে সরে যাওয়া', 'to gradually lose closeness in a relationship', 'Without regular contact, even close friends can drift apart.', 'advanced', v_urbanisation_and_housing),
    ('a nuclear household', 'noun phrase', 'একক পরিবার (গৃহ)', 'a household of parents and their children only', 'Urban migration has led to more nuclear households than before.', 'advanced', v_urbanisation_and_housing),
    ('unconditional love', 'noun phrase', 'নিঃশর্ত ভালোবাসা', 'love given without any conditions attached', 'Grandparents often show children a particularly unconditional love.', 'advanced', v_urbanisation_and_housing),
    ('to lean on someone', 'idiom', 'কারো উপর নির্ভর করা', 'to rely on someone for support', 'During tough times, it helps to have someone to lean on.', 'advanced', v_urbanisation_and_housing),
    ('blended family', 'noun phrase', 'সৎ ভাইবোনসহ পরিবার', 'a family formed from remarriage, including step-relatives', 'Blended families face unique challenges in building trust.', 'advanced', v_urbanisation_and_housing),
    ('a heart-to-heart', 'noun phrase', 'খোলামেলা আন্তরিক কথোপকথন', 'an honest, personal conversation', 'They finally had a heart-to-heart about their future plans.', 'advanced', v_urbanisation_and_housing),
    ('maternal instinct', 'noun phrase', 'মাতৃসুলভ সহজাত প্রবৃত্তি', 'a mother''s natural protective feeling towards her child', 'Maternal instinct kicked in the moment she heard him cry. / (35', 'advanced', v_urbanisation_and_housing),
    ('urban sprawl', 'noun phrase', 'শহরের অপরিকল্পিত সম্প্রসারণ', 'the uncontrolled spread of a city into surrounding areas', 'Urban sprawl has swallowed up farmland on the city''s edge.', 'advanced', v_urbanisation_and_housing),
    ('affordable housing', 'noun phrase', 'সাশ্রয়ী আবাসন', 'housing priced within reach of average incomes', 'The lack of affordable housing has pushed young families out of the city.', 'advanced', v_urbanisation_and_housing),
    ('gentrification', 'noun', 'অভিজাতকরণ', 'the process of an area becoming wealthier, displacing poorer residents', 'Gentrification has transformed the neighbourhood but priced out long-term residents.', 'advanced', v_urbanisation_and_housing),
    ('overcrowding', 'noun', 'অতিরিক্ত জনাকীর্ণতা', 'having too many people in a limited space', 'Overcrowding in informal settlements poses serious health risks.', 'advanced', v_urbanisation_and_housing),
    ('skyrocketing rents', 'collocation', 'হু হু করে বাড়া ভাড়া', 'rapidly and sharply increasing rental prices', 'Skyrocketing rents have forced many tenants to relocate further out.', 'advanced', v_urbanisation_and_housing),
    ('a high-rise building', 'noun phrase', 'বহুতল ভবন', 'a very tall building with many floors', 'High-rise buildings have transformed the city''s skyline in a decade.', 'advanced', v_urbanisation_and_housing),
    ('infrastructure development', 'noun phrase', 'অবকাঠামো উন্নয়ন', 'the building of roads, utilities and public services', 'Infrastructure development has struggled to keep up with population growth.', 'advanced', v_urbanisation_and_housing),
    ('a housing shortage', 'noun phrase', 'আবাসন সংকট', 'insufficient homes to meet demand', 'The housing shortage has driven prices to unprecedented levels.', 'advanced', v_urbanisation_and_housing),
    ('slum', 'noun', 'বস্তি', 'an overcrowded, poorly built urban area', 'Millions live in slums lacking basic sanitation.', 'advanced', v_urbanisation_and_housing),
    ('land scarcity', 'noun phrase', 'জমির অপ্রতুলতা', 'a shortage of available land', 'Land scarcity has made vertical housing the only viable option.', 'advanced', v_urbanisation_and_housing),
    ('commuting time', 'noun phrase', 'যাতায়াতের সময়', 'the time spent travelling to and from work', 'Long commuting times have become a major source of daily stress.', 'advanced', v_urbanisation_and_housing),
    ('property market', 'noun phrase', 'সম্পত্তি বাজার', 'the market for buying and selling real estate', 'The property market has cooled significantly following interest rate rises.', 'advanced', v_urbanisation_and_housing),
    ('mixed-use development', 'noun phrase', 'মিশ্র-ব্যবহার উন্নয়ন', 'development combining residential, commercial and other uses', 'Mixed-use development reduces the need for long commutes.', 'advanced', v_urbanisation_and_housing),
    ('a concrete jungle', 'idiom', 'কংক্রিটের জঙ্গল', 'a city with an overwhelming amount of buildings, lacking greenery', 'Critics describe the new district as a concrete jungle.', 'advanced', v_urbanisation_and_housing),
    ('suburban sprawl', 'noun phrase', 'শহরতলির অপরিকল্পিত সম্প্রসারণ', 'the uncontrolled growth of suburbs around a city', 'Suburban sprawl has increased dependence on private cars.', 'advanced', v_urbanisation_and_housing),
    ('a densely populated area', 'collocation', 'ঘনবসতিপূর্ণ এলাকা', 'a region with a high number of residents per area', 'Emergency services face particular challenges in densely populated areas.', 'advanced', v_urbanisation_and_housing),
    ('urban regeneration', 'noun phrase', 'নগর পুনর্গঠন', 'the renewal and improvement of a run-down urban area', 'Urban regeneration turned the derelict docks into a thriving district.', 'advanced', v_urbanisation_and_housing),
    ('green space', 'noun phrase', 'সবুজ এলাকা', 'open, natural areas within a built environment', 'Access to green space is linked to better mental health.', 'advanced', v_urbanisation_and_housing),
    ('a housing bubble', 'noun phrase', 'আবাসন বুদবুদ (মূল্য সংকট)', 'a period of rapidly rising, unsustainable property prices', 'Economists warned repeatedly of a looming housing bubble.', 'advanced', v_urbanisation_and_housing),
    ('rural-to-urban migration', 'noun phrase', 'গ্রাম থেকে শহরে অভিবাসন', 'the movement of people from the countryside to cities', 'Rural-to-urban migration has driven much of the country''s urban growth.', 'advanced', v_urbanisation_and_housing),
    ('a strain on resources', 'collocation', 'সম্পদের উপর চাপ', 'excessive pressure on limited resources', 'Rapid population growth puts a strain on water and electricity resources.', 'advanced', v_urbanisation_and_housing),
    ('zoning regulations', 'noun phrase', 'অঞ্চল বিন্যাস বিধি', 'rules determining how land in an area can be used', 'Zoning regulations restrict the height of buildings in the old town.', 'advanced', v_urbanisation_and_housing),
    ('a sprawling metropolis', 'collocation', 'বিস্তৃত মহানগর', 'a very large city that has spread over a wide area', 'The capital has grown into a sprawling metropolis of over 20 million.', 'advanced', v_urbanisation_and_housing),
    ('squatter settlement', 'noun phrase', 'অবৈধ বসতি', 'an informal settlement built without legal land rights', 'Squatter settlements often lack access to clean water and electricity.', 'advanced', v_urbanisation_and_housing),
    ('public housing', 'noun phrase', 'সরকারি আবাসন', 'housing provided or subsidised by the government', 'Public housing schemes aim to give low-income families a stable home.', 'advanced', v_urbanisation_and_housing),
    ('vertical living', 'noun phrase', 'উল্লম্ব জীবনযাপন (বহুতল)', 'living in high-rise apartments due to limited land', 'Vertical living has become the norm in space-constrained cities.', 'advanced', v_urbanisation_and_housing),
    ('a run-down neighbourhoo d', 'collocation', 'জরাজীর্ণ এলাকা', 'a neighbourhood in poor physical condition', 'The run-down neighbourhood is now scheduled for redevelopment.', 'advanced', v_urbanisation_and_housing),
    ('to price people out', 'collocation', 'সাধ্যের বাইরে ঠেলে দেওয়া', 'to make something unaffordable for certain groups', 'Rising property prices have priced first-time buyers out of the market.', 'advanced', v_science_and_space),
    ('communal spaces', 'noun phrase', 'সাধারণ ব্যবহারের স্থান', 'shared areas used by residents of a building or area', 'The new apartment complex includes communal spaces for residents.', 'advanced', v_science_and_space),
    ('sustainable urban planning', 'noun phrase', 'টেকসই নগর পরিকল্পনা', 'city planning that considers long-term environmental impact', 'Sustainable urban planning is essential as cities continue to grow.', 'advanced', v_science_and_space),
    ('a bustling city centre', 'collocation', 'কর্মচঞ্চল শহরকেন্দ্র', 'a lively, busy central area of a city', 'The bustling city centre never seems to sleep.', 'advanced', v_science_and_space),
    ('overpopulation', 'noun', 'অতিরিক্ত জনসংখ্যা', 'having more people than an area can support', 'Overpopulation has intensified pressure on housing and transport.', 'advanced', v_science_and_space),
    ('a satellite town', 'noun phrase', 'উপগ্রহ শহর', 'a smaller town built near a larger city to ease pressure', 'Satellite towns were built to relieve pressure on the overcrowded capital.', 'advanced', v_science_and_space),
    ('skyline', 'noun', 'আকাশরেখা (শহরের দৃশ্য)', 'the outline of a city''s buildings against the sky', 'The city''s skyline has changed dramatically over the past twenty years.', 'advanced', v_science_and_space),
    ('a housing crisis', 'noun phrase', 'আবাসন সংকট', 'a severe shortage or unaffordability of housing', 'The housing crisis has left many young professionals unable to buy homes. (30', 'advanced', v_science_and_space),
    ('scientific breakthrough', 'noun phrase', 'বৈজ্ঞানিক যুগান্তকারী আবিষ্কার', 'a major discovery that advances knowledge', 'The scientific breakthrough could transform how diseases are treated.', 'advanced', v_science_and_space),
    ('space exploration', 'noun phrase', 'মহাকাশ অভিযান', 'the investigation of outer space', 'Space exploration has expanded our understanding of the universe.', 'advanced', v_science_and_space),
    ('genetic engineering', 'noun phrase', 'জেনেটিক ইঞ্জিনিয়ারিং', 'the direct manipulation of an organism''s genes', 'Genetic engineering raises both scientific promise and ethical concern.', 'advanced', v_science_and_space),
    ('peer-reviewed research', 'noun phrase', 'সমকক্ষ-পর্যালোচিত গবেষণা', 'research evaluated by experts before publication', 'Only peer-reviewed research was cited in the report.', 'advanced', v_science_and_space),
    ('empirical evidence', 'noun phrase', 'পরীক্ষামূলক প্রমাণ', 'evidence gathered through observation or experiment', 'The theory lacked sufficient empirical evidence to be widely accepted.', 'advanced', v_science_and_space),
    ('hypothesis', 'noun', 'অনুকল্প', 'a proposed explanation to be tested', 'Researchers designed an experiment to test their hypothesis.', 'advanced', v_science_and_space),
    ('a groundbreakin g study', 'collocation', 'যুগান্তকারী গবেষণা', 'a study that introduces significant new findings', 'A groundbreaking study revealed the extent of ocean plastic pollution.', 'advanced', v_science_and_space),
    ('funding for research', 'collocation', 'গবেষণা তহবিল', 'financial support provided for scientific study', 'Funding for research has been cut significantly this year.', 'advanced', v_science_and_space),
    ('cutting-edge research', 'collocation', 'অত্যাধুনিক গবেষণা', 'the most advanced and current research', 'The lab is known for its cutting- edge research in renewable energy.', 'advanced', v_science_and_space),
    ('interstellar', 'adjective', 'আন্তঃনাক্ষত্রিক', 'relating to space between stars', 'Interstellar travel remains far beyond current technological capability.', 'advanced', v_science_and_space),
    ('a manned mission', 'noun phrase', 'মনুষ্যবাহী অভিযান', 'a space mission involving human astronauts', 'Plans for a manned mission to Mars have been delayed repeatedly.', 'advanced', v_science_and_space),
    ('satellite technology', 'noun phrase', 'স্যাটেলাইট প্রযুক্তি', 'technology involving orbiting devices for communication or observation', 'Satellite technology has revolutionised weather forecasting.', 'advanced', v_science_and_space),
    ('a scientific consensus', 'collocation', 'বৈজ্ঞানিক ঐকমত্য', 'general agreement among scientists on an issue', 'There is a strong scientific consensus on the causes of climate change.', 'advanced', v_science_and_space),
    ('stem cell research', 'noun phrase', 'স্টেম সেল গবেষণা', 'research into cells that can develop into other cell types', 'Stem cell research offers hope for treating previously incurable diseases.', 'advanced', v_science_and_space),
    ('an unmanned probe', 'noun phrase', 'মনুষ্যবিহীন যান', 'a spacecraft without a human crew', 'An unmanned probe was sent to collect samples from the asteroid.', 'advanced', v_science_and_space),
    ('extraterrestrial life', 'noun phrase', 'ভিনগ্রহের প্রাণ', 'life originating outside Earth', 'The search for extraterrestrial life continues to captivate scientists.', 'advanced', v_science_and_space),
    ('a paradigm shift', 'idiom', 'দৃষ্টিভঙ্গির আমূল পরিবর্তন', 'a fundamental change in approach or thinking', 'The discovery caused a paradigm shift in evolutionary biology.', 'advanced', v_science_and_space),
    ('to push the boundaries of', 'collocation', 'সীমা ছাড়িয়ে যাওয়া', 'to go beyond what was previously thought possible', 'The mission pushed the boundaries of what humans thought achievable.', 'advanced', v_science_and_space),
    ('data-driven', 'adjective', 'তথ্য-নির্ভর', 'based on the analysis of data rather than intuition', 'Modern medicine has become increasingly data-driven.', 'advanced', v_science_and_space),
    ('clinical trial', 'noun phrase', 'ক্লিনিক্যাল ট্রায়াল', 'a scientific study testing a new treatment on people', 'The vaccine passed all three phases of clinical trial.', 'advanced', v_science_and_space),
    ('cosmic', 'adjective', 'মহাজাগতিক', 'relating to the universe as a whole', 'Cosmic radiation poses a risk to long-duration space travel.', 'advanced', v_science_and_space),
    ('scientific literacy', 'noun phrase', 'বৈজ্ঞানিক সাক্ষরতা', 'a basic understanding of scientific concepts', 'Improving scientific literacy helps the public evaluate claims critically.', 'advanced', v_science_and_space),
    ('an experimental trial', 'noun phrase', 'পরীক্ষামূলক ট্রায়াল', 'a controlled scientific test of a hypothesis', 'The experimental trial produced inconclusive results.', 'advanced', v_science_and_space),
    ('to yield results', 'collocation', 'ফলাফল দেওয়া', 'to produce a particular outcome', 'Years of research finally began to yield results.', 'advanced', v_science_and_space),
    ('a scientific milestone', 'collocation', 'বৈজ্ঞানিক মাইলফলক', 'a significant point of achievement in science', 'Landing on the moon remains one of humanity''s greatest scientific milestones.', 'advanced', v_science_and_space),
    ('AI-driven', 'adjective', 'এআই-চালিত', 'powered or guided by artificial intelligence', 'AI-driven diagnostics are transforming early disease detection.', 'advanced', v_science_and_space),
    ('an unprecedented discovery', 'collocation', 'নজিরবিহীন আবিষ্কার', 'a discovery without any earlier example', 'Astronomers described the finding as an unprecedented discovery.', 'advanced', v_science_and_space),
    ('to conduct an experiment', 'collocation', 'পরীক্ষা পরিচালনা করা', 'to carry out a scientific test', 'The team conducted an experiment under strictly controlled conditions.', 'advanced', v_art_and_sport),
    ('quantum technology', 'noun phrase', 'কোয়ান্টাম প্রযুক্তি', 'technology based on the principles of quantum physics', 'Quantum technology could revolutionise computing within decades.', 'advanced', v_art_and_sport),
    ('scientific rigour', 'noun phrase', 'বৈজ্ঞানিক কঠোরতা', 'careful, precise and thorough scientific method', 'The study was praised for its scientific rigour.', 'advanced', v_art_and_sport),
    ('cultural expression', 'noun phrase', 'সাংস্কৃতিক প্রকাশ', 'the way culture is communicated through art or behaviour', 'Traditional dance remains an important cultural expression.', 'advanced', v_art_and_sport),
    ('a masterpiece', 'noun', 'শ্রেষ্ঠ শিল্পকর্ম', 'an outstanding work of art', 'The novel is widely regarded as a literary masterpiece.', 'advanced', v_art_and_sport),
    ('public funding for the arts', 'collocation', 'শিল্পকলার জন্য সরকারি তহবিল', 'government financial support for artistic activities', 'Public funding for the arts has declined over the past decade.', 'advanced', v_art_and_sport),
    ('a competitive edge', 'collocation', 'প্রতিযোগিতামূলক সুবিধা', 'an advantage over rivals', 'Regular training gives athletes a competitive edge.', 'advanced', v_art_and_sport),
    ('team spirit', 'noun phrase', 'দলগত মনোভাব', 'a sense of unity and cooperation within a group', 'The coach emphasised team spirit above individual talent.', 'advanced', v_art_and_sport),
    ('sportsmanship', 'noun', 'খেলোয়াড়সুলভ মনোভাব', 'fair and generous behaviour in sport', 'She was praised for her sportsmanship despite losing the final.', 'advanced', v_art_and_sport),
    ('physical prowess', 'noun phrase', 'শারীরিক দক্ষতা', 'great physical strength or skill', 'The athlete''s physical prowess was evident from a young age.', 'advanced', v_art_and_sport),
    ('artistic expression', 'noun phrase', 'শৈল্পিক প্রকাশ', 'the communication of ideas or emotions through art', 'Street art has become a powerful form of artistic expression.', 'advanced', v_art_and_sport),
    ('grassroots sport', 'noun phrase', 'তৃণমূল পর্যায়ের খেলা', 'sport played at a local, amateur level', 'Grassroots sport plays a vital role in discovering young talent.', 'advanced', v_art_and_sport),
    ('professional athlete', 'noun phrase', 'পেশাদার ক্রীড়াবিদ', 'someone who plays sport as a paid career', 'Becoming a professional athlete requires years of disciplined training.', 'advanced', v_art_and_sport),
    ('cultural significance', 'noun phrase', 'সাংস্কৃতিক গুরুত্ব', 'the importance of something within a culture', 'The festival holds deep cultural significance for the community.', 'advanced', v_art_and_sport),
    ('endorsement deal', 'noun phrase', 'অনুমোদন চুক্তি (বিজ্ঞাপন)', 'an agreement for a celebrity to promote a product', 'The athlete signed a lucrative endorsement deal with a sportswear brand.', 'advanced', v_art_and_sport),
    ('to push oneself to the limit', 'idiom', 'নিজেকে চরম সীমায় ঠেলে দেওয়া', 'to try as hard as physically possible', 'Marathon runners push themselves to the limit in the final mile.', 'advanced', v_art_and_sport),
    ('avant-garde', 'adjective', 'অভিনব ও পরীক্ষামূলক (শিল্পে)', 'experimental and innovative, especially in art', 'The gallery is known for showcasing avant-garde installations.', 'advanced', v_art_and_sport),
    ('a level playing field', 'idiom', 'সমান সুযোগের পরিবেশ', 'a fair situation where everyone has equal chances', 'Anti-doping rules exist to ensure a level playing field.', 'advanced', v_art_and_sport),
    ('commercialisa tion of sport', 'noun phrase', 'খেলাধুলার বাণিজ্যিকীকরণ', 'the increasing focus on profit within sport', 'The commercialisation of sport has changed how fans experience the game.', 'advanced', v_art_and_sport),
    ('aesthetic appeal', 'noun phrase', 'নান্দনিক আকর্ষণ', 'the pleasing visual or artistic quality of something', 'The building was praised for its aesthetic appeal.', 'advanced', v_art_and_sport),
    ('to break a record', 'collocation', 'রেকর্ড ভাঙা', 'to achieve a result better than any before', 'She broke the national record in the 100-metre sprint.', 'advanced', v_art_and_sport),
    ('a rigorous training regime', 'collocation', 'কঠোর প্রশিক্ষণ কর্মসূচি', 'a strict and demanding training schedule', 'Olympic athletes follow an extremely rigorous training regime.', 'advanced', v_art_and_sport),
    ('heritage arts', 'noun phrase', 'ঐতিহ্যবাহী শিল্পকলা', 'traditional art forms passed down through generations', 'Heritage arts such as pottery are at risk of dying out.', 'advanced', v_art_and_sport),
    ('an underdog', 'noun', 'পিছিয়ে থাকা প্রতিযোগী', 'a competitor expected to lose', 'The underdog stunned everyone by winning the championship.', 'advanced', v_globalisation),
    ('doping scandal', 'noun phrase', 'ডোপিং কেলেঙ্কারি', 'a controversy involving illegal performance- enhancing drugs', 'The doping scandal tarnished the reputation of the entire team.', 'advanced', v_globalisation),
    ('creative freedom', 'noun phrase', 'সৃজনশীল স্বাধীনতা', 'the freedom to express oneself artistically without restriction', 'The director insisted on complete creative freedom for the project.', 'advanced', v_globalisation),
    ('physical endurance', 'noun phrase', 'শারীরিক সহনশীলতা', 'the ability to sustain physical effort over time', 'The race tested the athletes'' physical endurance to the limit.', 'advanced', v_globalisation),
    ('a niche audience', 'noun phrase', 'সীমিত/বিশেষ দর্শকগোষ্ঠী', 'a small, specific group of interested people', 'Contemporary opera tends to attract a niche audience.', 'advanced', v_globalisation),
    ('to nurture talent', 'collocation', 'প্রতিভা লালন করা', 'to support and develop natural ability', 'The academy was founded to nurture young sporting talent.', 'advanced', v_globalisation),
    ('preserve tradition', 'collocation', 'ঐতিহ্য সংরক্ষণ করা', 'to protect customs from being lost', 'The festival helps preserve tradition amid rapid modernisation.', 'advanced', v_globalisation),
    ('team cohesion', 'noun phrase', 'দলগত সংহতি', 'the sense of unity within a team', 'Team cohesion often matters more than individual skill.', 'advanced', v_globalisation),
    ('a work of artistic merit', 'collocation', 'শৈল্পিক মূল্যসম্পন্ন কাজ', 'a creative work judged to have genuine artistic value', 'Critics debated whether the film had any artistic merit.', 'advanced', v_globalisation),
    ('an adrenaline rush', 'noun phrase', 'উত্তেজনার হঠাৎ ঢেউ', 'a sudden burst of excitement or energy', 'Extreme sports offer participants an intense adrenaline rush. Example', 'advanced', v_globalisation),
    ('globalisation', 'noun', 'বিশ্বায়ন', 'the increasing interconnection of world economies and cultures', 'Globalisation has made supply chains more efficient but more fragile.', 'advanced', v_globalisation),
    ('interconnected', 'adjective', 'পরস্পর সংযুক্ত', 'linked together, especially across the world', 'Financial markets today are more interconnected than ever before.', 'advanced', v_globalisation),
    ('multinational corporation', 'noun phrase', 'বহুজাতিক কোম্পানি', 'a company operating in multiple countries', 'Multinational corporations often wield more influence than small nations.', 'advanced', v_globalisation),
    ('cultural homogenisation', 'noun phrase', 'সাংস্কৃতিক সমরূপকরণ', 'the process of cultures becoming increasingly similar', 'Critics worry that globalisation drives cultural homogenisation.', 'advanced', v_globalisation),
    ('global supply chain', 'noun phrase', 'বৈশ্বিক সরবরাহ শৃঙ্খল', 'the international network involved in producing goods', 'Disruptions to the global supply chain caused shortages worldwide.', 'advanced', v_globalisation),
    ('trade liberalisation', 'noun phrase', 'বাণিজ্য উদারীকরণ', 'the removal of restrictions on international trade', 'Trade liberalisation has boosted exports but hurt local industries.', 'advanced', v_globalisation),
    ('economic interdependen ce', 'noun phrase', 'অর্থনৈতিক পারস্পরিক নির্ভরতা', 'countries relying on each other economically', 'Economic interdependence discourages armed conflict between trading partners.', 'advanced', v_globalisation),
    ('outsourcing', 'noun', 'আউটসোর্সিং', 'contracting work out to another country or company', 'Outsourcing manufacturing has significantly reduced production costs.', 'advanced', v_globalisation),
    ('a global village', 'idiom', 'বৈশ্বিক গ্রাম', 'the world seen as closely connected through technology', 'The internet has truly turned the world into a global village.', 'advanced', v_globalisation),
    ('local identity', 'noun phrase', 'স্থানীয় পরিচয়', 'the distinct character of a particular place or culture', 'Globalisation can threaten local identity when unchecked.', 'advanced', v_globalisation),
    ('foreign direct investment', 'noun phrase', 'প্রত্যক্ষ বৈদেশিক বিনিয়োগ', 'investment made directly into a foreign country''s businesses', 'Foreign direct investment has fuelled rapid industrial growth.', 'advanced', v_globalisation),
    ('a globalised economy', 'collocation', 'বিশ্বায়িত অর্থনীতি', 'an economy deeply linked to international trade and finance', 'Job security has become less certain in a globalised economy.', 'advanced', v_globalisation),
    ('exploitation of cheap labour', 'collocation', 'সস্তা শ্রমের শোষণ', 'unfair use of low-paid workers, often abroad', 'Some brands have faced criticism over exploitation of cheap labour.', 'advanced', v_globalisation),
    ('cultural exchange', 'noun phrase', 'সাংস্কৃতিক আদান-প্রদান', 'the sharing of ideas, customs and art between societies', 'Globalisation has accelerated cultural exchange between distant nations.', 'advanced', v_globalisation),
    ('a borderless world', 'idiom', 'সীমান্তহীন বিশ্ব', 'a world where national boundaries matter less', 'Advocates of globalisation envision a borderless world of free trade.', 'advanced', v_globalisation),
    ('income disparity', 'noun phrase', 'আয়ের বৈষম্য', 'the gap in earnings between different groups', 'Globalisation has widened income disparity within many nations.', 'advanced', v_globalisation),
    ('homogenised culture', 'noun phrase', 'সমরূপ সংস্কৃতি', 'culture that has lost distinct local variation', 'Global chains have contributed to an increasingly homogenised culture.', 'advanced', v_globalisation),
    ('offshoring', 'noun', 'অফশোরিং', 'relocating business operations to another country', 'Offshoring call centres has become common among large corporations.', 'advanced', v_globalisation),
    ('a level of interdependen ce', 'collocation', 'পারস্পরিক নির্ভরতার মাত্রা', 'the degree to which parties rely on one another', 'The pandemic revealed just how deep our level of interdependence is.', 'advanced', v_globalisation),
    ('global inequality', 'noun phrase', 'বৈশ্বিক বৈষম্য', 'unequal distribution of wealth across countries', 'Global inequality remains one of the defining issues of our time.', 'advanced', v_globalisation),
    ('a race to the bottom', 'idiom', 'তলানির দিকে প্রতিযোগিতা', 'competition that lowers standards or wages', 'Critics describe outsourcing as a race to the bottom on wages.', 'advanced', v_globalisation),
    ('protectionism', 'noun', 'সংরক্ষণবাদ', 'policies protecting domestic industry from foreign competition', 'Rising protectionism has slowed global trade growth.', 'advanced', v_globalisation),
    ('global connectivity', 'noun phrase', 'বৈশ্বিক সংযোগ', 'the state of being linked worldwide, especially digitally', 'Global connectivity has made remote work across time zones possible.', 'advanced', v_globalisation),
    ('cross-border trade', 'noun phrase', 'সীমান্তপারের বাণিজ্য', 'trade conducted between countries', 'Cross-border trade has grown substantially since trade barriers were lowered.', 'advanced', v_globalisation),
    ('a global marketplace', 'noun phrase', 'বৈশ্বিক বাজার', 'the interconnected international market for goods and services', 'Small businesses now compete in a truly global marketplace.', 'advanced', v_globalisation),
    ('economic integration', 'noun phrase', 'অর্থনৈতিক সংহতিকরণ', 'the merging of economies through trade and policy', 'Regional economic integration has boosted trade among member states.', 'advanced', v_globalisation),
    ('standardisation', 'noun', 'প্রমিতকরণ', 'making things conform to a single standard', 'Standardisation of products has made global manufacturing more efficient.', 'advanced', v_globalisation),
    ('local versus global tension', 'collocation', 'স্থানীয় বনাম বৈশ্বিক দ্বন্দ্ব', 'the conflict between local traditions and global influence', 'There is growing local versus global tension over food culture.', 'advanced', v_globalisation),
    ('a shrinking world', 'idiom', 'সংকুচিত হয়ে আসা বিশ্ব', 'the sense that distances feel smaller due to technology', 'Air travel and the internet have created a shrinking world.', 'advanced', v_globalisation),
    ('global citizenship', 'noun phrase', 'বৈশ্বিক নাগরিকত্ব', 'a sense of belonging to and responsibility for the whole world', 'Schools are increasingly promoting global citizenship among students.', 'advanced', v_globalisation),
    ('personally speaking', 'phrase', 'ব্যক্তিগতভাবে বলতে গেলে', 'used to introduce one''s own opinion', 'Personally speaking, I think remote work benefits employees more than employers.', 'advanced', v_opinion_and_stance);
end $$;
