-- ============================================================
-- 027_ielts_vocabulary_words_600_799.sql
-- Content batch: IELTS Band 8 vocabulary words 600-799,
-- transcribed from "1000 Essential Words for Band 8" (word, part of
-- speech, definition, and example extracted from the source; Bangla
-- meanings authored fresh, since the PDF's own Bangla text layer is
-- corrupted at the font level -- see migration notes).
-- ============================================================

do $$
declare
  v_opinion_and_stance uuid;
  v_hedging_and_nuance uuid;
  v_agreement_and_disagreement uuid;
  v_comparison_and_contrast uuid;
  v_cause_and_effect uuid;
  v_linking_and_discourse_markers uuid;
  v_idiomatic_spoken_expressions uuid;
begin
  select cn.id into v_opinion_and_stance from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'opinion-and-stance';
  select cn.id into v_hedging_and_nuance from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'hedging-and-nuance';
  select cn.id into v_agreement_and_disagreement from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'agreement-and-disagreement';
  select cn.id into v_comparison_and_contrast from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'comparison-and-contrast';
  select cn.id into v_cause_and_effect from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'cause-and-effect';
  select cn.id into v_linking_and_discourse_markers from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'linking-and-discourse-markers';
  select cn.id into v_idiomatic_spoken_expressions from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'idiomatic-spoken-expressions';

  insert into vocabulary (word, part_of_speech, bangla_meaning, english_definition, example_sentence, difficulty, node_id) values
    ('as far as I''m concerned', 'phrase', 'আমার দৃষ্টিতে', 'in my personal view', 'As far as I''m concerned, quality matters more than quantity.', 'advanced', v_opinion_and_stance),
    ('from my point of view', 'phrase', 'আমার দৃষ্টিকোণ থেকে', 'according to my perspective', 'From my point of view, the benefits clearly outweigh the risks.', 'advanced', v_opinion_and_stance),
    ('it seems to me that', 'phrase', 'আমার কাছে মনে হয় যে', 'in my assessment', 'It seems to me that the real problem lies elsewhere.', 'advanced', v_opinion_and_stance),
    ('I firmly believe that', 'phrase', 'আমি দৃঢ়ভাবে বিশ্বাস করি', 'used for a strongly held opinion', 'I firmly believe that education is the single best investment a country can make.', 'advanced', v_opinion_and_stance),
    ('I am inclined to think that', 'phrase', 'আমার ধারণা যে', 'a slightly softer way to state an opinion', 'I am inclined to think that the change will do more harm than good.', 'advanced', v_opinion_and_stance),
    ('my take on this is', 'phrase', 'এ ব্যাপারে আমার মত হলো', 'a conversational way to introduce one''s opinion', 'My take on this is that both sides have valid points.', 'advanced', v_opinion_and_stance),
    ('if you ask me', 'idiom', 'আমাকে জিজ্ঞেস করলে', 'a casual way to give an unsolicited opinion', 'If you ask me, the whole system needs a complete overhaul.', 'advanced', v_opinion_and_stance),
    ('the way I see it', 'phrase', 'আমি যেভাবে দেখি', 'according to how one understands a situation', 'The way I see it, both options carry roughly the same risk.', 'advanced', v_opinion_and_stance),
    ('I would argue that', 'phrase', 'আমি যুক্তি দেব যে', 'used to introduce a reasoned opinion', 'I would argue that prevention is always cheaper than cure.', 'advanced', v_opinion_and_stance),
    ('there is no denying that', 'phrase', 'এটা অস্বীকার করার উপায় নেই', 'used to state something clearly true', 'There is no denying that technology has transformed education.', 'advanced', v_opinion_and_stance),
    ('it goes without saying that', 'idiom', 'বলাই বাহুল্য যে', 'used for something obviously true', 'It goes without saying that prevention is better than cure.', 'advanced', v_opinion_and_stance),
    ('I am a firm believer in', 'phrase', 'আমি দৃঢ় সমর্থক', 'to strongly support an idea', 'I am a firm believer in lifelong learning.', 'advanced', v_opinion_and_stance),
    ('one could argue that', 'phrase', 'কেউ যুক্তি দিতে পারে যে', 'a hedged way to introduce a possible view', 'One could argue that too much choice creates its own kind of stress.', 'advanced', v_opinion_and_stance),
    ('it could be argued that', 'phrase', 'এমন যুক্তি দেওয়া যেতে পারে যে', 'academic hedge introducing a claim', 'It could be argued that social media has done more harm than good.', 'advanced', v_opinion_and_stance),
    ('in my experience', 'phrase', 'আমার অভিজ্ঞতায়', 'based on what one has personally observed', 'In my experience, small daily habits matter more than occasional effort.', 'advanced', v_opinion_and_stance),
    ('as I see it', 'phrase', 'আমি যেমনটা দেখি', 'a brief way to introduce a personal view', 'As I see it, the risks are manageable if handled carefully.', 'advanced', v_opinion_and_stance),
    ('I hold the view that', 'phrase', 'আমি এই মত পোষণ করি', 'formal way to state an opinion', 'I hold the view that public transport should be a national priority.', 'advanced', v_opinion_and_stance),
    ('speaking for myself', 'phrase', 'নিজের কথা বলতে গেলে', 'used to give a personal opinion, distinct from others', 'Speaking for myself, I would rather have less money and more free time.', 'advanced', v_opinion_and_stance),
    ('I tend to think that', 'phrase', 'আমি মনে করি যে', 'a mild way of expressing an opinion', 'I tend to think that experience matters more than qualifications.', 'advanced', v_opinion_and_stance),
    ('my honest opinion is', 'phrase', 'আমার সৎ মতামত হলো', 'an emphatic way to introduce a candid view', 'My honest opinion is that the plan was rushed and poorly thought out.', 'advanced', v_opinion_and_stance),
    ('I stand by the idea that', 'phrase', 'আমি এই ধারণায় অটল', 'to maintain a firm opinion', 'I stand by the idea that hard work eventually pays off.', 'advanced', v_opinion_and_stance),
    ('to my mind', 'phrase', 'আমার মতে', 'in my opinion', 'To my mind, the advantages far outweigh any temporary inconvenience.', 'advanced', v_opinion_and_stance),
    ('I can''t help but think', 'phrase', 'না ভেবে পারছি না যে', 'used when an opinion feels almost unavoidable', 'I can''t help but think we are relying on technology a little too much.', 'advanced', v_opinion_and_stance),
    ('it strikes me that', 'phrase', 'আমার কাছে মনে হয় যে', 'used when something suddenly seems clear or true', 'It strikes me that we often overlook the simplest solutions.', 'advanced', v_opinion_and_stance),
    ('there''s a strong case for', 'collocation', 'এর পক্ষে শক্তিশালী যুক্তি আছে', 'there are good reasons supporting something', 'There''s a strong case for investing more in early education.', 'advanced', v_opinion_and_stance),
    ('in all honesty', 'phrase', 'সততার সাথে বলতে গেলে', 'used to introduce a frank opinion', 'In all honesty, I don''t think the policy will achieve its goals.', 'advanced', v_opinion_and_stance),
    ('I subscribe to the view that', 'phrase', 'আমি এই মতের সাথে একমত', 'formal expression of agreement with a viewpoint', 'I subscribe to the view that prevention should always come before cure.', 'advanced', v_opinion_and_stance),
    ('needless to say', 'phrase', 'বলা বাহুল্য', 'used before something considered obvious', 'Needless to say, the decision was not popular with everyone.', 'advanced', v_opinion_and_stance),
    ('I am of the opinion that', 'phrase', 'আমার মত হলো', 'formal way to state a personal view', 'I am of the opinion that early intervention makes all the difference.', 'advanced', v_opinion_and_stance),
    ('it is my firm conviction that', 'phrase', 'এটি আমার দৃঢ় বিশ্বাস', 'a strong, formal expression of belief', 'It is my firm conviction that access to clean water is a basic right.', 'advanced', v_opinion_and_stance),
    ('there''s something to be said for', 'idiom', 'এর পক্ষেও কিছু বলার আছে', 'used to acknowledge a merit in something', 'There''s something to be said for slowing down and taking your time.', 'advanced', v_opinion_and_stance),
    ('I take the view that', 'phrase', 'আমি এই মত গ্রহণ করি', 'formal statement of opinion', 'I take the view that punishment alone rarely changes behaviour.', 'advanced', v_opinion_and_stance),
    ('what strikes me most is', 'phrase', 'আমাকে সবচেয়ে বেশি যা নাড়া দেয়', 'used to highlight the most notable point', 'What strikes me most is how quickly attitudes have changed.', 'advanced', v_opinion_and_stance),
    ('by and large', 'idiom', 'মোটের উপর/সাধারণভাবে', 'generally speaking, considering everything', 'By and large, the reforms have been well received.', 'advanced', v_opinion_and_stance),
    ('on the whole', 'phrase', 'সামগ্রিকভাবে', 'considering everything together', 'On the whole, I believe the changes have been positive.', 'advanced', v_hedging_and_nuance),
    ('all things considered', 'phrase', 'সবকিছু বিবেচনা করলে', 'taking every factor into account', 'All things considered, the risk seems worth taking.', 'advanced', v_hedging_and_nuance),
    ('I have mixed feelings about', 'collocation', 'এ ব্যাপারে আমার মিশ্র অনুভূতি আছে', 'to have both positive and negative feelings', 'I have mixed feelings about the new policy, to be honest.', 'advanced', v_hedging_and_nuance),
    ('I''m torn between', 'collocation', 'আমি দ্বিধাগ্রস্ত', 'unable to decide between two options', 'I''m torn between the convenience of the city and the calm of the countryside.', 'advanced', v_hedging_and_nuance),
    ('at the end of the day', 'idiom', 'শেষ পর্যন্ত', 'ultimately, when everything is considered', 'At the end of the day, people just want a stable, secure life. (30', 'advanced', v_hedging_and_nuance),
    ('to some extent', 'phrase', 'একটা পর্যায় পর্যন্ত', 'partially true, but not completely', 'To some extent, the criticism is fair.', 'advanced', v_hedging_and_nuance),
    ('it largely depends on', 'phrase', 'এটা মূলত নির্ভর করে', 'the outcome is mostly determined by', 'It largely depends on how the policy is implemented.', 'advanced', v_hedging_and_nuance),
    ('more often than not', 'idiom', 'প্রায়ই', 'usually, in most cases', 'More often than not, the simplest solution is the most effective.', 'advanced', v_hedging_and_nuance),
    ('in most cases', 'phrase', 'অধিকাংশ ক্ষেত্রে', 'generally true, with some exceptions', 'In most cases, early treatment leads to a full recovery.', 'advanced', v_hedging_and_nuance),
    ('by and large', 'idiom', 'সাধারণভাবে', 'generally, with few exceptions', 'By and large, the students responded well to the new method.', 'advanced', v_hedging_and_nuance),
    ('arguably', 'adverb', 'যুক্তিসঙ্গতভাবে বলা যায়', 'it can reasonably be argued', 'This is arguably the most significant change in a generation.', 'advanced', v_hedging_and_nuance),
    ('presumably', 'adverb', 'সম্ভবত', 'as one would reasonably assume', 'Presumably, costs will fall once the technology matures.', 'advanced', v_hedging_and_nuance),
    ('it would appear that', 'phrase', 'মনে হচ্ছে যে', 'based on available evidence, it seems that', 'It would appear that the strategy is beginning to pay off.', 'advanced', v_hedging_and_nuance),
    ('there is reason to believe that', 'phrase', 'বিশ্বাস করার কারণ আছে যে', 'evidence suggests', 'There is reason to believe that the trend will continue.', 'advanced', v_hedging_and_nuance),
    ('it is not entirely clear whether', 'phrase', 'পুরোপুরি স্পষ্ট নয় যে', 'used to express genuine uncertainty', 'It is not entirely clear whether the policy caused the improvement.', 'advanced', v_hedging_and_nuance),
    ('up to a point', 'phrase', 'একটা সীমা পর্যন্ত সত্য', 'true, but with limitations', 'I agree, up to a point, but circumstances vary a great deal.', 'advanced', v_hedging_and_nuance),
    ('broadly speaking', 'phrase', 'বিস্তৃতভাবে বলতে গেলে', 'in general terms, without going into detail', 'Broadly speaking, wealthier nations produce more emissions per person.', 'advanced', v_hedging_and_nuance),
    ('more or less', 'phrase', 'মোটামুটিভাবে', 'approximately, almost', 'The two proposals are more or less identical in cost.', 'advanced', v_hedging_and_nuance),
    ('not necessarily', 'phrase', 'তা সবসময় সত্য নয়', 'used to soften or reject an assumption', 'A higher price does not necessarily mean better quality.', 'advanced', v_hedging_and_nuance),
    ('it is fair to say that', 'phrase', 'এটা বলা ন্যায্য যে', 'used to introduce a reasonable claim', 'It is fair to say that opinions remain divided on this issue.', 'advanced', v_hedging_and_nuance),
    ('this is not always the case', 'phrase', 'এটা সবসময় সত্য নয়', 'used to note an exception to a general rule', 'This is not always the case in rural communities, however.', 'advanced', v_hedging_and_nuance),
    ('tends to be', 'collocation', 'সাধারণত হয়ে থাকে', 'usually, as a general pattern', 'Public opinion tends to be more cautious on this issue than policy suggests.', 'advanced', v_hedging_and_nuance),
    ('seemingly', 'adverb', 'আপাতদৃষ্টিতে', 'appearing to be true, though perhaps not certain', 'A seemingly small change had a surprisingly large effect.', 'advanced', v_hedging_and_nuance),
    ('to a certain degree', 'phrase', 'একটা নির্দিষ্ট মাত্রা পর্যন্ত', 'partially, but not fully', 'To a certain degree, both arguments are valid.', 'advanced', v_hedging_and_nuance),
    ('it is worth noting that', 'phrase', 'এটা উল্লেখযোগ্য যে', 'used to add a relevant, sometimes qualifying, point', 'It is worth noting that results varied considerably by region.', 'advanced', v_hedging_and_nuance),
    ('in a sense', 'phrase', 'একভাবে বলতে গেলে', 'true when viewed from a particular angle', 'In a sense, both sides are arguing for the same underlying goal.', 'advanced', v_hedging_and_nuance),
    ('strictly speaking', 'phrase', 'কঠোরভাবে বলতে গেলে', 'used to give a precise, technical qualification', 'Strictly speaking, the term applies only to a narrower category.', 'advanced', v_agreement_and_disagreement),
    ('it is generally accepted that', 'phrase', 'এটা সাধারণভাবে স্বীকৃত যে', 'a widely held view among experts', 'It is generally accepted that early diagnosis improves outcomes.', 'advanced', v_agreement_and_disagreement),
    ('as a rule of thumb', 'idiom', 'সাধারণ নিয়ম হিসেবে', 'a broadly reliable general principle', 'As a rule of thumb, save at least ten per cent of your income.', 'advanced', v_agreement_and_disagreement),
    ('give or take', 'idiom', 'কমবেশি', 'approximately', 'The project will take a year, give or take a month or two.', 'advanced', v_agreement_and_disagreement),
    ('not without reason', 'phrase', 'অকারণ নয়', 'with some justification', 'Critics are worried, not without reason, about the pace of change.', 'advanced', v_agreement_and_disagreement),
    ('it is conceivable that', 'phrase', 'এটা সম্ভবপর যে', 'it is possible, though not certain', 'It is conceivable that costs will rise further next year.', 'advanced', v_agreement_and_disagreement),
    ('in all likelihood', 'phrase', 'সম্ভাবনার দিক থেকে', 'most probably', 'In all likelihood, the trend will continue for several more years.', 'advanced', v_agreement_and_disagreement),
    ('at first glance', 'phrase', 'প্রথম দেখায়', 'based on an initial impression', 'At first glance, the idea seems reasonable, but closer inspection reveals problems.', 'advanced', v_agreement_and_disagreement),
    ('on closer inspection', 'phrase', 'গভীরভাবে দেখলে', 'when examined more carefully', 'On closer inspection, the figures tell a more complicated story. / (20', 'advanced', v_agreement_and_disagreement),
    ('I couldn''t agree more', 'idiom', 'আমি পুরোপুরি একমত', 'to agree completely with someone', 'I couldn''t agree more — prevention really is better than cure.', 'advanced', v_agreement_and_disagreement),
    ('that''s exactly how I feel', 'phrase', 'আমারও ঠিক এমনটাই মনে হয়', 'used to express strong agreement', 'That''s exactly how I feel about remote work, actually.', 'advanced', v_agreement_and_disagreement),
    ('I see your point, but', 'phrase', 'আপনার কথা বুঝেছি, কিন্তু', 'to acknowledge a view before disagreeing', 'I see your point, but I still think the risks are too high.', 'advanced', v_agreement_and_disagreement),
    ('I''m not so sure about that', 'phrase', 'এ ব্যাপারে আমি ততটা নিশ্চিত নই', 'a polite way to express doubt or disagreement', 'I''m not so sure about that — the evidence seems mixed.', 'advanced', v_agreement_and_disagreement),
    ('that''s one way of looking at it', 'phrase', 'এটাও দেখার একটা দিক', 'a diplomatic way to disagree without confrontation', 'That''s one way of looking at it, though I''d frame it differently.', 'advanced', v_agreement_and_disagreement),
    ('I beg to differ', 'idiom', 'আমি বিনীতভাবে দ্বিমত পোষণ করি', 'a formal, polite way to disagree', 'I beg to differ — the data actually suggests the opposite.', 'advanced', v_agreement_and_disagreement),
    ('I take your point, however', 'phrase', 'আপনার কথা মানছি, তবে', 'to accept part of an argument before disagreeing', 'I take your point, however, I don''t think it applies here.', 'advanced', v_agreement_and_disagreement),
    ('that''s a fair point', 'phrase', 'এটা যুক্তিসঙ্গত কথা', 'to acknowledge a valid argument', 'That''s a fair point — I hadn''t considered the cost involved.', 'advanced', v_agreement_and_disagreement),
    ('I''m inclined to agree', 'phrase', 'আমি একমত হওয়ার দিকেই ঝুঁকছি', 'a moderate way to express agreement', 'I''m inclined to agree, though I''d add a few conditions.', 'advanced', v_agreement_and_disagreement),
    ('I have to disagree there', 'phrase', 'এখানে আমি দ্বিমত পোষণ করছি', 'a direct but polite way to disagree', 'I have to disagree there — the risks seem manageable to me.', 'advanced', v_agreement_and_disagreement),
    ('that''s debatable', 'phrase', 'এটা বিতর্কসাপেক্ষ', 'used when something is not clearly true or false', 'Whether it actually saves money is debatable.', 'advanced', v_agreement_and_disagreement),
    ('you have a point there', 'phrase', 'আপনার কথায় যুক্তি আছে', 'to acknowledge a valid argument', 'You have a point there — I hadn''t thought about it that way.', 'advanced', v_agreement_and_disagreement),
    ('I''m on the fence about this', 'idiom', 'এ ব্যাপারে আমি দ্বিধাগ্রস্ত', 'undecided between two positions', 'Honestly, I''m on the fence about this one.', 'advanced', v_agreement_and_disagreement),
    ('agree to disagree', 'idiom', 'দ্বিমত নিয়েই একমত হওয়া', 'to accept differing opinions without further argument', 'We eventually just agreed to disagree on the matter.', 'advanced', v_agreement_and_disagreement),
    ('that''s a valid concern', 'phrase', 'এটা একটা যৌক্তিক উদ্বেগ', 'to acknowledge someone''s worry as reasonable', 'That''s a valid concern, and it deserves a proper answer.', 'advanced', v_agreement_and_disagreement),
    ('I wouldn''t go that far', 'phrase', 'এতদূর যেতে রাজি নই', 'to partially disagree with an extreme statement', 'I wouldn''t go that far, but I do see some truth in it.', 'advanced', v_comparison_and_contrast),
    ('on the contrary', 'phrase', 'এর বিপরীতে', 'used to state the opposite view', 'On the contrary, most evidence points in the other direction.', 'advanced', v_comparison_and_contrast),
    ('I respectfully disagree', 'phrase', 'আমি বিনীতভাবে দ্বিমত পোষণ করি', 'polite, formal disagreement', 'I respectfully disagree — I think the long-term costs are underestimated.', 'advanced', v_comparison_and_contrast),
    ('that resonates with me', 'collocation', 'এটা আমার সাথে মিলে যায়', 'to feel a personal connection to an idea', 'That really resonates with me, especially given my own experience.', 'advanced', v_comparison_and_contrast),
    ('we''re on the same page', 'idiom', 'আমরা একই মতের', 'to have the same understanding or opinion', 'It seems we''re on the same page about the main priorities. (30', 'advanced', v_comparison_and_contrast),
    ('as opposed to', 'phrase', 'এর বিপরীতে', 'in contrast to', 'People today prefer convenience, as opposed to the thrift of earlier generations.', 'advanced', v_comparison_and_contrast),
    ('in contrast to', 'phrase', 'এর বিপরীতে', 'showing a clear difference', 'In contrast to rural areas, cities offer far greater job diversity.', 'advanced', v_comparison_and_contrast),
    ('whereas', 'connector', 'যেখানে (বৈসাদৃশ্য বোঝাতে)', 'used to compare two contrasting facts', 'Some people prefer working alone, whereas others thrive in teams.', 'advanced', v_comparison_and_contrast),
    ('on the other hand', 'phrase', 'অন্যদিকে', 'introduces a contrasting point', 'On the other hand, the policy could increase costs significantly.', 'advanced', v_comparison_and_contrast),
    ('by comparison', 'phrase', 'তুলনা করলে', 'when compared with something else', 'By comparison, the older model was far less fuel-efficient.', 'advanced', v_comparison_and_contrast),
    ('far more ... than', 'collocation', 'অনেক বেশি ... তুলনায়', 'used to emphasise a large difference', 'The new system is far more efficient than the one it replaced.', 'advanced', v_comparison_and_contrast),
    ('nowhere near as ... as', 'collocation', 'কাছাকাছিও নয়', 'used to emphasise a large difference in the opposite direction', 'The turnout was nowhere near as high as organisers had hoped.', 'advanced', v_comparison_and_contrast),
    ('unlike', null, 'এর বিপরীতে', 'in contrast to', 'Unlike traditional classrooms, online courses allow flexible scheduling.', 'advanced', v_comparison_and_contrast),
    ('similarly', 'adverb', 'একইভাবে', 'in the same way', 'Similarly, employees in the private sector face comparable pressures.', 'advanced', v_comparison_and_contrast),
    ('likewise', 'adverb', 'তদ্রূপ/একইভাবে', 'in the same way, also', 'Likewise, smaller businesses have struggled to adapt.', 'advanced', v_comparison_and_contrast),
    ('both ... and', 'connector', 'উভয়ই ... এবং', 'used to include two related things', 'Both employers and employees benefit from flexible working hours.', 'advanced', v_comparison_and_contrast),
    ('in the same vein', 'idiom', 'একই সুরে', 'in a similar way or style', 'In the same vein, critics have raised concerns about data privacy.', 'advanced', v_comparison_and_contrast),
    ('a stark contrast', 'collocation', 'স্পষ্ট বৈসাদৃশ্য', 'a very clear and strong difference', 'The wealth gap presents a stark contrast between the two districts.', 'advanced', v_comparison_and_contrast),
    ('to draw a parallel between', 'collocation', 'সমান্তরাল তুলনা করা', 'to compare two similar situations', 'Economists have drawn a parallel between the two financial crises.', 'advanced', v_comparison_and_contrast),
    ('on a similar note', 'phrase', 'একই প্রসঙ্গে', 'used to introduce a related point', 'On a similar note, healthcare spending has also increased.', 'advanced', v_comparison_and_contrast),
    ('equally', 'adverb', 'সমানভাবে', 'to the same extent', 'Equally important is the need for proper regulation.', 'advanced', v_comparison_and_contrast),
    ('conversely', 'adverb', 'বিপরীতভাবে', 'in an opposite way', 'Conversely, smaller firms have found the new rules easier to follow.', 'advanced', v_comparison_and_contrast),
    ('in much the same way', 'phrase', 'অনেকটা একইভাবে', 'similarly, in a comparable manner', 'In much the same way, older workers face different but related challenges.', 'advanced', v_comparison_and_contrast),
    ('there is little to choose between', 'idiom', 'পার্থক্য করার মতো তেমন কিছু নেই', 'two things are very similar in quality', 'In terms of price, there is little to choose between the two brands.', 'advanced', v_comparison_and_contrast),
    ('pale in comparison to', 'idiom', 'তুলনায় ম্লান মনে হওয়া', 'to seem much less impressive next to something else', 'Small local floods pale in comparison to the devastation of 1998.', 'advanced', v_comparison_and_contrast),
    ('a world apart', 'idiom', 'একেবারে ভিন্ন জগৎ', 'extremely different', 'Life in the capital is a world apart from life in the villages.', 'advanced', v_cause_and_effect),
    ('twice as ... as', 'collocation', 'দ্বিগুণ ... এর তুলনায়', 'used to express a two-fold difference', 'The new model is twice as efficient as the previous version.', 'advanced', v_cause_and_effect),
    ('considerably more/less than', 'collocation', 'যথেষ্ট বেশি/কম', 'a significant difference in quantity', 'Rural households spend considerably less on transport than urban ones.', 'advanced', v_cause_and_effect),
    ('a marked difference', 'collocation', 'স্পষ্ট পার্থক্য', 'a clear and noticeable difference', 'There is a marked difference in outcomes between the two approaches.', 'advanced', v_cause_and_effect),
    ('relatively speaking', 'phrase', 'তুলনামূলকভাবে বলতে গেলে', 'when compared with something else', 'Relatively speaking, the cost of the upgrade is quite modest.', 'advanced', v_cause_and_effect),
    ('at the opposite end of the spectrum', 'idiom', 'একেবারে বিপরীত প্রান্তে', 'representing the extreme opposite position', 'At the opposite end of the spectrum are those who reject the idea entirely.', 'advanced', v_cause_and_effect),
    ('bear little resemblance to', 'idiom', 'সামান্যই মিল আছে', 'to be very different from something', 'The final policy bears little resemblance to the original proposal.', 'advanced', v_cause_and_effect),
    ('side by side', 'idiom', 'পাশাপাশি', 'placed together for comparison', 'When placed side by side, the differences become obvious.', 'advanced', v_cause_and_effect),
    ('mirror each other', 'collocation', 'একে অপরের প্রতিফলন', 'to closely resemble one another', 'The two countries'' economic policies largely mirror each other.', 'advanced', v_cause_and_effect),
    ('a close second', 'collocation', 'প্রায় সমতুল্য', 'nearly equal to the best or first', 'In terms of popularity, the second option was a close second. (25', 'advanced', v_cause_and_effect),
    ('this is largely due to', 'phrase', 'এটি মূলত এর কারণে', 'used to attribute a cause', 'The delay is largely due to unforeseen supply issues.', 'advanced', v_cause_and_effect),
    ('as a result of', 'phrase', 'এর ফলস্বরূপ', 'because of', 'As a result of the new policy, applications have doubled.', 'advanced', v_cause_and_effect),
    ('this stems from', 'collocation', 'এটি উদ্ভূত হয়েছে', 'this originates from', 'The mistrust stems from a series of broken promises.', 'advanced', v_cause_and_effect),
    ('gives rise to', 'collocation', 'জন্ম দেয়', 'to cause or lead to', 'Rapid urban growth gives rise to serious traffic problems.', 'advanced', v_cause_and_effect),
    ('this accounts for', 'collocation', 'এটি ব্যাখ্যা করে', 'this explains', 'Rising fuel costs account for much of the price increase.', 'advanced', v_cause_and_effect),
    ('leads to', 'collocation', 'পরিণত হয়', 'results in', 'Poor sleep consistently leads to reduced concentration.', 'advanced', v_cause_and_effect),
    ('contributes to', 'collocation', 'এতে অবদান রাখে', 'is one of several causes of', 'Stress at work contributes significantly to burnout.', 'advanced', v_cause_and_effect),
    ('triggers', 'verb', 'সূচনা ঘটায়', 'to cause something to start suddenly', 'A single incident triggered widespread protests.', 'advanced', v_cause_and_effect),
    ('has a knock-on effect', 'idiom', 'পরবর্তী প্রভাব ফেলে', 'to cause a chain of further effects', 'A delay at one factory has a knock- on effect throughout the supply chain.', 'advanced', v_cause_and_effect),
    ('this in turn', 'phrase', 'এটি পরিবর্তে', 'used to link a cause to its further effect', 'Fewer jobs are created, and this in turn slows local spending.', 'advanced', v_cause_and_effect),
    ('which explains why', 'phrase', 'যা ব্যাখ্যা করে কেন', 'used to connect a fact to its cause', 'Costs have fallen sharply, which explains why demand has risen.', 'advanced', v_cause_and_effect),
    ('is attributable to', 'collocation', 'এর জন্য দায়ী', 'can be explained by', 'The improvement is largely attributable to better training.', 'advanced', v_cause_and_effect),
    ('paves the way for', 'idiom', 'পথ প্রশস্ত করে', 'to create conditions that make something possible', 'The reform paves the way for greater investment.', 'advanced', v_cause_and_effect),
    ('this, coupled with', 'phrase', 'এর সাথে যুক্ত হয়ে', 'used when two causes combine', 'This, coupled with rising demand, pushed prices even higher.', 'advanced', v_cause_and_effect),
    ('precipitates', 'verb', 'হঠাৎ ঘটিয়ে দেয়', 'to cause something to happen suddenly', 'The scandal precipitated the minister''s resignation.', 'advanced', v_cause_and_effect),
    ('exacerbates', 'verb', 'আরও খারাপ করে তোলে', 'to make a problem worse', 'Poor drainage exacerbates flooding during the monsoon.', 'advanced', v_linking_and_discourse_markers),
    ('a direct consequence of', 'collocation', 'সরাসরি ফলাফল', 'a result that follows immediately from a cause', 'The shortage is a direct consequence of the factory closure.', 'advanced', v_linking_and_discourse_markers),
    ('underpins', 'verb', 'ভিত্তি তৈরি করে', 'to form the basis or support of something', 'Trust underpins every successful long-term relationship.', 'advanced', v_linking_and_discourse_markers),
    ('fuels', 'verb', 'জ্বালানি জোগায় (তীব্র করে)', 'to intensify or make something grow', 'Cheap credit fuelled the housing boom.', 'advanced', v_linking_and_discourse_markers),
    ('sets off a chain reaction', 'idiom', 'শৃঙ্খল প্রতিক্রিয়া শুরু করে', 'to start a series of related events', 'One factory closure set off a chain reaction across the local economy.', 'advanced', v_linking_and_discourse_markers),
    ('at the root of', 'idiom', 'এর মূলে রয়েছে', 'the fundamental cause of', 'Poor communication was at the root of the misunderstanding.', 'advanced', v_linking_and_discourse_markers),
    ('is symptomatic of', 'collocation', 'এটি লক্ষণ মাত্র', 'is a sign of a larger underlying problem', 'The delay is symptomatic of deeper organisational issues.', 'advanced', v_linking_and_discourse_markers),
    ('arises from', 'collocation', 'এর থেকে উদ্ভূত হয়', 'originates or results from', 'Much of the tension arises from a simple lack of communication.', 'advanced', v_linking_and_discourse_markers),
    ('has far-reaching consequences', 'collocation', 'সুদূরপ্রসারী প্রভাব ফেলে', 'has effects that extend widely', 'The decision has far-reaching consequences for the entire industry.', 'advanced', v_linking_and_discourse_markers),
    ('consequently', 'adverb', 'ফলস্বরূপ', 'as a result', 'Demand fell sharply; consequently, prices dropped too. / (35', 'advanced', v_linking_and_discourse_markers),
    ('moving on to', 'phrase', 'এবার আসা যাক', 'used to shift to a new topic', 'Moving on to the second issue, let''s consider the cost involved.', 'advanced', v_linking_and_discourse_markers),
    ('that being said', 'phrase', 'তা সত্ত্বেও/তবে বলা যায়', 'used to introduce a qualifying point', 'That being said, the plan does have some clear advantages.', 'advanced', v_linking_and_discourse_markers),
    ('having said that', 'phrase', 'তা বলা সত্ত্বেও', 'used before a contrasting point', 'Having said that, implementation has proven far harder than expected.', 'advanced', v_linking_and_discourse_markers),
    ('with that in mind', 'phrase', 'এটা মাথায় রেখে', 'considering the previous point', 'With that in mind, a more gradual approach seems sensible.', 'advanced', v_linking_and_discourse_markers),
    ('in light of this', 'phrase', 'এই আলোকে', 'considering this fact', 'In light of this, the committee has revised its recommendation.', 'advanced', v_linking_and_discourse_markers),
    ('to put it another way', 'phrase', 'অন্যভাবে বলতে গেলে', 'used to rephrase a point for clarity', 'To put it another way, cost is not the only factor at play.', 'advanced', v_linking_and_discourse_markers),
    ('in other words', 'phrase', 'অন্য কথায়', 'used to restate something more clearly', 'In other words, the policy benefits the few at the expense of the many.', 'advanced', v_linking_and_discourse_markers),
    ('that is to say', 'phrase', 'অর্থাৎ', 'used to clarify a previous statement', 'The change is temporary, that is to say, it will be reviewed next year.', 'advanced', v_linking_and_discourse_markers),
    ('above all', 'phrase', 'সবার উপরে', 'most importantly', 'Above all, the reform must be fair to those on lower incomes.', 'advanced', v_linking_and_discourse_markers),
    ('not to mention', 'phrase', 'উল্লেখ না করেও', 'used to add a further, often obvious, point', 'The plan is expensive, not to mention difficult to implement.', 'advanced', v_linking_and_discourse_markers),
    ('let alone', 'phrase', 'তো দূরের কথা', 'used to emphasise an even less likely case', 'Many families can barely afford rent, let alone save for the future.', 'advanced', v_linking_and_discourse_markers),
    ('as things stand', 'phrase', 'বর্তমান অবস্থা অনুযায়ী', 'given the current situation', 'As things stand, there is no clear timeline for the project.', 'advanced', v_linking_and_discourse_markers),
    ('bearing this in mind', 'phrase', 'এটা মনে রেখে', 'considering the point just made', 'Bearing this in mind, policymakers should proceed with caution.', 'advanced', v_linking_and_discourse_markers),
    ('against this backdrop', 'phrase', 'এই প্রেক্ষাপটে', 'given this general context', 'Against this backdrop, the announcement came as no surprise.', 'advanced', v_linking_and_discourse_markers),
    ('first and foremost', 'phrase', 'সর্বাগ্রে', 'most importantly, before anything else', 'First and foremost, safety must not be compromised.', 'advanced', v_linking_and_discourse_markers),
    ('last but not least', 'idiom', 'সর্বশেষ কিন্তু গুরুত্বপূর্ণ', 'a final point that is still important', 'Last but not least, the plan must remain affordable.', 'advanced', v_linking_and_discourse_markers),
    ('as previously mentioned', 'phrase', 'পূর্বে উল্লিখিত হিসেবে', 'referring back to an earlier point', 'As previously mentioned, costs have risen sharply this year.', 'advanced', v_linking_and_discourse_markers),
    ('building on this point', 'phrase', 'এই বিষয়ের উপর ভিত্তি করে', 'used to extend a previous point', 'Building on this point, researchers suggest further investment is needed.', 'advanced', v_linking_and_discourse_markers),
    ('turning now to', 'phrase', 'এবার আসা যাক', 'to shift attention to a new topic', 'Turning now to the second question, is this development sustainable?', 'advanced', v_linking_and_discourse_markers),
    ('with this in view', 'phrase', 'এটা বিবেচনায় নিয়ে', 'taking this into account', 'With this in view, the government has proposed a phased rollout.', 'advanced', v_linking_and_discourse_markers),
    ('it follows that', 'phrase', 'তাহলে বোঝা যায় যে', 'used to introduce a logical conclusion', 'If costs continue to rise, it follows that demand will eventually fall.', 'advanced', v_linking_and_discourse_markers),
    ('crucially', 'adverb', 'গুরুত্বপূর্ণভাবে', 'used to highlight an especially important point', 'Crucially, the funding must be sustained beyond the first year.', 'advanced', v_linking_and_discourse_markers),
    ('notably', 'adverb', 'লক্ষণীয়ভাবে', 'used to draw attention to a significant detail', 'Notably, none of the proposals addressed long-term funding.', 'advanced', v_linking_and_discourse_markers),
    ('significantly', 'adverb', 'উল্লেখযোগ্যভাবে', 'in a way that is important or considerable', 'Significantly, support for the plan cuts across political lines.', 'advanced', v_linking_and_discourse_markers),
    ('in essence', 'phrase', 'মূলত', 'basically, fundamentally', 'In essence, the reform shifts responsibility from state to individual.', 'advanced', v_linking_and_discourse_markers),
    ('at its core', 'phrase', 'এর মূলে', 'fundamentally, at the heart of the matter', 'At its core, the debate is about who should bear the cost.', 'advanced', v_linking_and_discourse_markers),
    ('for the most part', 'phrase', 'অধিকাংশ ক্ষেত্রে', 'mostly, generally', 'For the most part, the response has been positive.', 'advanced', v_linking_and_discourse_markers),
    ('in the meantime', 'phrase', 'এরই মধ্যে', 'while something else is happening', 'In the meantime, temporary measures have been put in place.', 'advanced', v_linking_and_discourse_markers),
    ('as it happens', 'phrase', 'ঘটনাক্রমে', 'used to introduce a coincidental or relevant fact', 'As it happens, a similar scheme was tried a decade ago.', 'advanced', v_linking_and_discourse_markers),
    ('incidentally', 'adverb', 'প্রসঙ্গক্রমে', 'used to introduce a related but secondary point', 'Incidentally, the same issue was raised in last year''s report.', 'advanced', v_idiomatic_spoken_expressions),
    ('all in all', 'phrase', 'সব মিলিয়ে', 'considering everything together', 'All in all, the trial can be considered a modest success.', 'advanced', v_idiomatic_spoken_expressions),
    ('to reiterate', 'phrase', 'পুনরাবৃত্তি করতে গেলে', 'to say again for emphasis', 'To reiterate, the deadline cannot be extended further.', 'advanced', v_idiomatic_spoken_expressions),
    ('as alluded to earlier', 'phrase', 'আগে যেমন উল্লেখ করা হয়েছে', 'referring back to something mentioned briefly before', 'As alluded to earlier, funding remains the biggest obstacle.', 'advanced', v_idiomatic_spoken_expressions),
    ('more importantly', 'phrase', 'আরও গুরুত্বপূর্ণভাবে', 'used to introduce a point of greater significance', 'More importantly, the reform addresses long-standing inequality.', 'advanced', v_idiomatic_spoken_expressions),
    ('in a nutshell', 'idiom', 'সংক্ষেপে বলতে গেলে', 'briefly summarised', '(', 'advanced', v_idiomatic_spoken_expressions),
    ('to sum up', 'phrase', 'সংক্ষেপে বলা', 'to briefly summarise', 'To sum up, the evidence points clearly in one direction. / (Speaking Band', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s a bit of a hassle', 'idiom', 'এটা একটু ঝামেলার', 'something mildly inconvenient or annoying', 'Renewing the passport is a bit of a hassle, to be honest.', 'advanced', v_idiomatic_spoken_expressions),
    ('I''m not really into it', 'collocation', 'আমার এতে তেমন আগ্রহ নেই', 'a casual way to say one is not interested', 'I''m not really into sport, if I''m honest.', 'advanced', v_idiomatic_spoken_expressions),
    ('that''s a tough one', 'collocation', 'এটা কঠিন প্রশ্ন', 'used when a question is difficult to answer', 'That''s a tough one — I''ve never really thought about it.', 'advanced', v_idiomatic_spoken_expressions),
    ('off the top of my head', 'idiom', 'হঠাৎ মাথায় যা আসে', 'without checking or thinking carefully', 'Off the top of my head, I''d say around thirty per cent.', 'advanced', v_idiomatic_spoken_expressions),
    ('it grew on me', 'idiom', 'ধীরে ধীরে ভালো লাগতে শুরু করেছে', 'to gradually start liking something', 'I hated the city at first, but it grew on me over time.', 'advanced', v_idiomatic_spoken_expressions),
    ('I''m on the fence about it', 'idiom', 'এ ব্যাপারে আমি দ্বিধাগ্রস্ত', 'undecided about something', 'I''m still on the fence about whether to change careers.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s not my cup of tea', 'idiom', 'এটা আমার পছন্দের নয়', 'something one does not particularly enjoy', 'Horror films just aren''t my cup of tea.', 'advanced', v_idiomatic_spoken_expressions),
    ('give it a shot', 'idiom', 'চেষ্টা করে দেখা', 'to try something', 'I''d never cooked before, but I decided to give it a shot.', 'advanced', v_idiomatic_spoken_expressions),
    ('it slipped my mind', 'idiom', 'মনে করতে ভুলে গেছি', 'to have forgotten something', 'I meant to call, but it completely slipped my mind.', 'advanced', v_idiomatic_spoken_expressions),
    ('a rule of thumb', 'idiom', 'একটি সাধারণ নিয়ম', 'a broadly reliable general principle', 'As a rule of thumb, I try to reply to emails within a day.', 'advanced', v_idiomatic_spoken_expressions),
    ('to be honest', 'phrase', 'সত্যি বলতে', 'used before a candid statement', 'To be honest, I was a little disappointed with the result.', 'advanced', v_idiomatic_spoken_expressions),
    ('at the end of the day', 'idiom', 'শেষ পর্যন্ত', 'when everything is considered', 'At the end of the day, it''s about what makes you happy.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s a double-edged sword', 'idiom', 'এটা দ্বিধারী তরবারি', 'something with both advantages and disadvantages', 'Working from home is a bit of a double-edged sword.', 'advanced', v_idiomatic_spoken_expressions),
    ('I''ll cross that bridge when I come to it', 'idiom', 'সমস্যা এলে তখন দেখা যাবে', 'to deal with a problem only when it actually arises', 'I haven''t decided yet — I''ll cross that bridge when I come to it.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s early days', 'idiom', 'এখনো অনেক আগে', 'too soon to judge the outcome', 'We''ve only just started, so it''s early days yet.', 'advanced', v_idiomatic_spoken_expressions),
    ('a piece of cake', 'idiom', 'খুব সহজ কাজ', 'something very easy', 'Compared to my last job, this is a piece of cake.', 'advanced', v_idiomatic_spoken_expressions),
    ('I''m all for it', 'collocation', 'আমি এর পক্ষে', 'strongly in favour of something', 'If it saves time and money, I''m all for it.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s down to personal taste', 'idiom', 'এটা ব্যক্তিগত পছন্দের ব্যাপার', 'a matter of individual preference', 'Whether you prefer the city or the countryside is down to personal taste.', 'advanced', v_idiomatic_spoken_expressions),
    ('it takes some getting used to', 'idiom', 'এতে অভ্যস্ত হতে সময় লাগে', 'something requires time to adapt to', 'The new system takes some getting used to.', 'advanced', v_idiomatic_spoken_expressions),
    ('a rough patch', 'idiom', 'কঠিন সময়', 'a difficult period', 'The business went through a rough patch during the pandemic.', 'advanced', v_idiomatic_spoken_expressions);
end $$;
