-- ============================================================
-- 028_ielts_vocabulary_words_800_999.sql
-- Content batch: IELTS Band 8 vocabulary words 800-999,
-- transcribed from "1000 Essential Words for Band 8" (word, part of
-- speech, definition, and example extracted from the source; Bangla
-- meanings authored fresh, since the PDF's own Bangla text layer is
-- corrupted at the font level -- see migration notes).
-- ============================================================

do $$
declare
  v_idiomatic_spoken_expressions uuid;
  v_speaking_fillers uuid;
  v_task_1_trend_and_data_language uuid;
  v_advanced_adjectives uuid;
  v_advanced_adverbs_of_degree uuid;
  v_academic_verbs uuid;
begin
  select cn.id into v_idiomatic_spoken_expressions from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'idiomatic-spoken-expressions';
  select cn.id into v_speaking_fillers from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'speaking-fillers';
  select cn.id into v_task_1_trend_and_data_language from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'task-1-trend-and-data-language';
  select cn.id into v_advanced_adjectives from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'advanced-adjectives';
  select cn.id into v_advanced_adverbs_of_degree from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'advanced-adverbs-of-degree';
  select cn.id into v_academic_verbs from content_nodes cn join content_nodes ielts_vocab on cn.parent_id = ielts_vocab.id join content_nodes ielts on ielts_vocab.parent_id = ielts.id where ielts.slug = 'ielts' and ielts_vocab.slug = 'vocabulary' and cn.slug = 'academic-verbs';

  insert into vocabulary (word, part_of_speech, bangla_meaning, english_definition, example_sentence, difficulty, node_id) values
    ('a blessing in disguise', 'idiom', 'ছদ্মবেশে আশীর্বাদ', 'something that seems bad but turns out beneficial', 'Losing that job turned out to be a blessing in disguise.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s hit or miss', 'idiom', 'অনিশ্চিত ফলাফল', 'unpredictable, sometimes good and sometimes not', 'The weather here is hit or miss, so always carry an umbrella.', 'advanced', v_idiomatic_spoken_expressions),
    ('I can''t complain', 'collocation', 'অভিযোগ করার কিছু নেই', 'a modest way of saying things are going well', 'Business has been steady, so I can''t complain.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s worth a shot', 'idiom', 'চেষ্টা করে দেখার মতো', 'worth attempting even if success is uncertain', 'We might not succeed, but it''s worth a shot.', 'advanced', v_idiomatic_spoken_expressions),
    ('a far cry from', 'idiom', 'অনেকটাই ভিন্ন', 'very different from something', 'This job is a far cry from what I studied at university.', 'advanced', v_idiomatic_spoken_expressions),
    ('out of the blue', 'idiom', 'হঠাৎ করে, অপ্রত্যাশিতভাবে', 'unexpectedly, without warning', 'The offer came completely out of the blue.', 'advanced', v_idiomatic_spoken_expressions),
    ('to weigh up the pros and cons', 'collocation', 'ভালো-মন্দ বিচার করা', 'to consider the advantages and disadvantages', 'We spent weeks weighing up the pros and cons before deciding.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s a matter of time', 'idiom', 'এটা সময়ের ব্যাপার মাত্র', 'something is certain to happen eventually', 'It''s only a matter of time before the technology becomes mainstream.', 'advanced', v_idiomatic_spoken_expressions),
    ('bear with me', 'idiom', 'একটু ধৈর্য ধরুন', 'asking for patience while thinking or explaining', 'Bear with me, I''m trying to remember the exact figures.', 'advanced', v_idiomatic_spoken_expressions),
    ('let''s put it this way', 'idiom', 'এভাবে বলা যাক', 'used to introduce a simplified explanation', 'Let''s put it this way — it wasn''t exactly what I expected.', 'advanced', v_idiomatic_spoken_expressions),
    ('for what it''s worth', 'idiom', 'যতটুকু মূল্য থাকুক', 'used when offering an opinion modestly', 'For what it''s worth, I think the decision was the right one.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s a whole other story', 'idiom', 'এটা সম্পূর্ণ আলাদা গল্প', 'used to indicate something is very different or complicated', 'Getting the visa was easy — finding accommodation is a whole other story.', 'advanced', v_idiomatic_spoken_expressions),
    ('that rings a bell', 'idiom', 'চেনা চেনা লাগছে', 'something sounds familiar', 'That name rings a bell, but I can''t place it.', 'advanced', v_idiomatic_spoken_expressions),
    ('I''m drawing a blank', 'idiom', 'কিছু মনে করতে পারছি না', 'unable to remember or think of something', 'I''m drawing a blank — I just can''t remember the title.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s a small world', 'idiom', 'পৃথিবী কত ছোট', 'said when an unexpected coincidence occurs', 'You know my cousin too? It''s a small world!', 'advanced', v_idiomatic_spoken_expressions),
    ('to make the most of it', 'collocation', 'সর্বোচ্চ কাজে লাগানো', 'to use an opportunity as well as possible', 'The trip was short, but we made the most of it.', 'advanced', v_idiomatic_spoken_expressions),
    ('easier said than done', 'idiom', 'বলা সহজ, করা কঠিন', 'something that sounds simple but is hard in practice', 'Saving money sounds easy, but it''s easier said than done.', 'advanced', v_idiomatic_spoken_expressions),
    ('at a crossroads', 'idiom', 'সিদ্ধান্তের এক মোড়ে', 'a point where an important decision must be made', 'I feel like I''m at a crossroads in my career right now.', 'advanced', v_idiomatic_spoken_expressions),
    ('food for thought', 'idiom', 'ভাবনার খোরাক', 'something that makes you think seriously', 'The documentary really gave me food for thought.', 'advanced', v_idiomatic_spoken_expressions),
    ('to have a lot on my plate', 'idiom', 'অনেক কাজের চাপে থাকা', 'to be very busy with many responsibilities', 'I can''t take on anything new — I already have a lot on my plate.', 'advanced', v_idiomatic_spoken_expressions),
    ('it''s not the end of the world', 'idiom', 'এটা পৃথিবীর শেষ নয়', 'something is unfortunate but not truly disastrous', 'If we miss the deadline, it''s not the end of the world.', 'advanced', v_idiomatic_spoken_expressions),
    ('let''s see how it goes', 'collocation', 'দেখা যাক কী হয়', 'used to express a wait-and-see attitude', 'I''m not fully committed yet — let''s see how it goes.', 'advanced', v_idiomatic_spoken_expressions),
    ('to jump on the bandwagon', 'idiom', 'জনপ্রিয়তার স্রোতে গা ভাসানো', 'to start doing something because it has become popular', 'A lot of companies jumped on the bandwagon once the trend took off.', 'advanced', v_idiomatic_spoken_expressions),
    ('to take it with a pinch of salt', 'idiom', 'পুরোপুরি বিশ্বাস না করা', 'to not fully believe something', 'I''d take that claim with a pinch of salt, honestly.', 'advanced', v_idiomatic_spoken_expressions),
    ('to hit the nail on the head', 'idiom', 'সঠিক জায়গায় আঘাত করা', 'to describe a situation exactly and accurately', 'I think you''ve hit the nail on the head with that explanation.', 'advanced', v_idiomatic_spoken_expressions),
    ('out of my comfort zone', 'idiom', 'স্বস্তির গণ্ডির বাইরে', 'in a situation that feels unfamiliar or challenging', 'Moving abroad pushed me well out of my comfort zone.', 'advanced', v_idiomatic_spoken_expressions),
    ('to get the hang of it', 'idiom', 'ধীরে ধীরে আয়ত্ত করা', 'to gradually learn how to do something', 'It took a while, but I eventually got the hang of it.', 'advanced', v_idiomatic_spoken_expressions),
    ('a work in progress', 'idiom', 'এখনো চলমান কাজ', 'something not yet finished or perfected', 'My English is still very much a work in progress.', 'advanced', v_idiomatic_spoken_expressions),
    ('to be spoilt for choice', 'idiom', 'অনেক ভালো বিকল্পের মাঝে বিভ্রান্তি', 'to have so many good options that deciding is hard', 'With so many good universities, students are spoilt for choice.', 'advanced', v_idiomatic_spoken_expressions),
    ('when it comes down to it', 'idiom', 'যখন আসল বিষয়টাই মুখ্য হয়ে দাঁড়ায়', 'when the most important factor is considered', 'When it comes down to it, price is what matters most to me. F / (20', 'advanced', v_idiomatic_spoken_expressions),
    ('that''s an interesting question', 'phrase', 'এটা মজার প্রশ্ন', 'used to acknowledge a question while thinking of an answer', 'That''s an interesting question — I''ve never really thought about it before.', 'advanced', v_speaking_fillers),
    ('let me think for a moment', 'phrase', 'একটু ভাবতে দিন', 'used to pause naturally before answering', 'Let me think for a moment... I''d say it started about five years ago.', 'advanced', v_speaking_fillers),
    ('well, ...', null, 'আচ্ছা...', 'a natural way to begin thinking aloud', 'Well, I suppose it depends on the situation.', 'advanced', v_speaking_fillers),
    ('I suppose ...', null, 'আমার মনে হয়...', 'used to introduce a tentative answer', 'I suppose the biggest factor is convenience.', 'advanced', v_speaking_fillers),
    ('how shall I put this', 'phrase', 'কীভাবে বলি...', 'used when searching for the right words', 'How shall I put this... it wasn''t quite what I expected.', 'advanced', v_speaking_fillers),
    ('let me see', 'phrase', 'দেখি তো...', 'a natural pause while thinking', 'Let me see... I''d probably choose the second option.', 'advanced', v_speaking_fillers),
    ('that''s a good one', 'collocation', 'সেটা ভালো প্রশ্ন', 'a friendly acknowledgement of a tricky question', 'That''s a good one — give me a second to think.', 'advanced', v_speaking_fillers),
    ('now, let me think', 'phrase', 'এখন একটু ভাবি', 'used to buy a moment before responding', 'Now, let me think... there are a couple of reasons, really.', 'advanced', v_speaking_fillers),
    ('I''ve never really thought about that before', 'phrase', 'এটা নিয়ে আগে কখনো ভাবিনি', 'a genuine, natural response to buy thinking time', 'I''ve never really thought about that before, to be honest.', 'advanced', v_speaking_fillers),
    ('um, actually', null, 'আসলে...', 'used before slightly changing or clarifying a point', 'Um, actually, I think it''s more complicated than that.', 'advanced', v_speaking_fillers),
    ('you know', null, 'জানো তো...', 'used to add casual emphasis (used sparingly)', 'It''s, you know, one of those things you only appreciate later.', 'advanced', v_speaking_fillers),
    ('I mean', null, 'মানে...', 'used to clarify or rephrase a point', 'I mean, it''s not perfect, but it works well enough.', 'advanced', v_speaking_fillers),
    ('to put it simply', 'phrase', 'সহজভাবে বলতে গেলে', 'used to give a simplified explanation', 'To put it simply, we just didn''t have enough time.', 'advanced', v_speaking_fillers),
    ('if I''m honest', 'phrase', 'সত্যি বলতে গেলে', 'used before a candid answer', 'If I''m honest, I hadn''t considered that angle at all.', 'advanced', v_speaking_fillers),
    ('give me a second', 'collocation', 'একটু সময় দিন', 'a casual way to ask for a moment to think', 'Give me a second — I want to get this right.', 'advanced', v_speaking_fillers),
    ('where should I start', 'phrase', 'কোথা থেকে শুরু করি', 'used before a longer answer requiring organisation', 'Where should I start... there are quite a few reasons, actually.', 'advanced', v_speaking_fillers),
    ('it''s hard to say, but', 'phrase', 'বলা কঠিন, তবে', 'used before an uncertain but genuine answer', 'It''s hard to say, but I''d guess it happens fairly often.', 'advanced', v_speaking_fillers),
    ('come to think of it', 'idiom', 'হঠাৎ মনে হলো', 'used when a thought occurs while speaking', 'Come to think of it, that might explain the whole situation.', 'advanced', v_speaking_fillers),
    ('that''s not something I''d considered', 'phrase', 'এটা ভাবিনি আগে', 'a natural way to acknowledge a new angle', 'That''s not something I''d considered, but it makes sense.', 'advanced', v_speaking_fillers),
    ('right, so', null, 'আচ্ছা, তাহলে', 'used to organise thoughts before a structured answer', 'Right, so there are basically two ways of looking at this.', 'advanced', v_speaking_fillers),
    ('rose sharply', 'collocation', 'হঠাৎ করে বেড়ে গেছে', 'increased suddenly and by a large amount', 'Sales rose sharply after the marketing campaign launched.', 'advanced', v_task_1_trend_and_data_language),
    ('fell steadily', 'collocation', 'ধীরে ধীরে কমেছে', 'decreased gradually and consistently', 'The unemployment rate fell steadily throughout the decade.', 'advanced', v_task_1_trend_and_data_language),
    ('remained stable', 'collocation', 'স্থিতিশীল রয়েছে', 'stayed roughly the same', 'Prices remained stable despite economic uncertainty.', 'advanced', v_task_1_trend_and_data_language),
    ('fluctuated', 'verb', 'ওঠানামা করেছে', 'varied up and down irregularly', 'The exchange rate fluctuated considerably over the period.', 'advanced', v_task_1_trend_and_data_language),
    ('peaked at', 'collocation', 'সর্বোচ্চ পৌঁছেছে', 'reached the highest point at a certain value', 'Demand peaked at over 90% in the final year.', 'advanced', v_task_1_trend_and_data_language),
    ('bottomed out at', 'collocation', 'সর্বনিম্নে পৌঁছে আবার বেড়েছে', 'reached the lowest point before recovering', 'The market bottomed out at its lowest level in a decade.', 'advanced', v_task_1_trend_and_data_language),
    ('plummeted', 'verb', 'হঠাৎ ধপ করে পড়ে গেছে', 'fell suddenly and dramatically', 'Tourist numbers plummeted following the announcement.', 'advanced', v_task_1_trend_and_data_language),
    ('surged', 'verb', 'হঠাৎ বেড়ে গেছে', 'increased suddenly and significantly', 'Applications surged after the deadline was extended.', 'advanced', v_task_1_trend_and_data_language),
    ('levelled off', 'collocation', 'স্থিতিশীল হয়ে গেছে', 'stopped rising or falling and became steady', 'Growth levelled off after an initial rapid expansion.', 'advanced', v_task_1_trend_and_data_language),
    ('a gradual decline', 'collocation', 'ধীরে ধীরে পতন', 'a slow, steady decrease', 'The industry has experienced a gradual decline over ten years.', 'advanced', v_task_1_trend_and_data_language),
    ('a dramatic increase', 'collocation', 'নাটকীয় বৃদ্ধি', 'a very large and sudden increase', 'There was a dramatic increase in online shopping during the period.', 'advanced', v_task_1_trend_and_data_language),
    ('a marginal rise', 'collocation', 'সামান্য বৃদ্ধি', 'a very small increase', 'Wages saw only a marginal rise compared to inflation.', 'advanced', v_task_1_trend_and_data_language),
    ('a slight dip', 'collocation', 'সামান্য পতন', 'a small, temporary decrease', 'There was a slight dip in enrolment before numbers recovered.', 'advanced', v_task_1_trend_and_data_language),
    ('overtook', 'verb', 'ছাড়িয়ে গেছে', 'moved ahead of, surpassed', 'Renewable energy overtook coal as the main power source.', 'advanced', v_task_1_trend_and_data_language),
    ('accounted for', 'collocation', 'অনুপাতে ছিল', 'made up a certain proportion of', 'Housing accounted for nearly half of total spending.', 'advanced', v_task_1_trend_and_data_language),
    ('constituted', 'verb', 'গঠন করেছে', 'made up or formed a part of', 'Young adults constituted the majority of new subscribers.', 'advanced', v_task_1_trend_and_data_language),
    ('represented', 'verb', 'প্রতিনিধিত্ব করেছে', 'made up a proportion, expressed as a share', 'The category represented just over a quarter of total sales.', 'advanced', v_task_1_trend_and_data_language),
    ('a steady upward trend', 'collocation', 'ধারাবাহিক ঊর্ধ্বমুখী প্রবণতা', 'a consistent pattern of increase', 'The data shows a steady upward trend across all regions.', 'advanced', v_task_1_trend_and_data_language),
    ('a downward trajectory', 'collocation', 'ধারাবাহিক নিম্নমুখী গতিপথ', 'a consistent pattern of decrease', 'The company has been on a downward trajectory for two years.', 'advanced', v_task_1_trend_and_data_language),
    ('approximately', 'adverb', 'প্রায়', 'roughly, close to a figure', 'Approximately 60% of respondents preferred the second option.', 'advanced', v_task_1_trend_and_data_language),
    ('just under/over', 'collocation', 'সামান্য কম/বেশি', 'slightly below or above a figure', 'Just under half of the population lives in urban areas.', 'advanced', v_task_1_trend_and_data_language),
    ('a significant proportion', 'collocation', 'একটি উল্লেখযোগ্য অংশ', 'a large share of a total', 'A significant proportion of the budget goes towards salaries.', 'advanced', v_task_1_trend_and_data_language),
    ('a negligible amount', 'collocation', 'নগণ্য পরিমাণ', 'an amount too small to be important', 'Only a negligible amount of waste is currently recycled.', 'advanced', v_task_1_trend_and_data_language),
    ('comparable to', 'collocation', 'তুলনীয়', 'similar in size or amount to', 'The figures for 2020 are comparable to those from 2015.', 'advanced', v_task_1_trend_and_data_language),
    ('twice as high as', 'collocation', 'দ্বিগুণ বেশি', 'exactly double the amount', 'Spending on healthcare was twice as high as on education.', 'advanced', v_task_1_trend_and_data_language),
    ('a stark contrast', 'collocation', 'স্পষ্ট বৈসাদৃশ্য', 'a very obvious difference', 'This is in stark contrast to the trend seen a decade earlier.', 'advanced', v_task_1_trend_and_data_language),
    ('the gap widened', 'collocation', 'ব্যবধান বেড়েছে', 'the difference between two figures increased', 'The gap between the two countries widened considerably.', 'advanced', v_task_1_trend_and_data_language),
    ('the gap narrowed', 'collocation', 'ব্যবধান কমেছে', 'the difference between two figures decreased', 'The wage gap narrowed slightly over the five-year period.', 'advanced', v_task_1_trend_and_data_language),
    ('a modest increase', 'collocation', 'সামান্য বৃদ্ধি', 'a moderate, not very large increase', 'The region saw only a modest increase in population.', 'advanced', v_task_1_trend_and_data_language),
    ('an exponential rise', 'collocation', 'দ্রুতগতির বৃদ্ধি', 'a rapidly accelerating increase', 'Internet usage has seen an exponential rise since 2005.', 'advanced', v_task_1_trend_and_data_language),
    ('stagnated', 'verb', 'স্থবির হয়ে গেছে', 'stopped growing or developing', 'Wages stagnated for much of the decade.', 'advanced', v_task_1_trend_and_data_language),
    ('recovered', 'verb', 'পুনরুদ্ধার হয়েছে', 'returned to a previous, higher level', 'The market recovered fully within eighteen months.', 'advanced', v_task_1_trend_and_data_language),
    ('hit a record high/low', 'collocation', 'সর্বোচ্চ/সর্বনিম্ন রেকর্ড', 'reached the highest or lowest level ever recorded', 'Unemployment hit a record low that same year.', 'advanced', v_task_1_trend_and_data_language),
    ('maintained a steady rate', 'collocation', 'স্থিতিশীল গতিতে চলেছে', 'continued at a consistent pace', 'Growth maintained a steady rate throughout the decade.', 'advanced', v_advanced_adjectives),
    ('halved', 'verb', 'অর্ধেক হয়েছে', 'reduced to half of the original amount', 'Costs halved after the new technology was introduced.', 'advanced', v_advanced_adjectives),
    ('doubled', 'verb', 'দ্বিগুণ হয়েছে', 'increased to twice the original amount', 'Enrolment doubled within just three years.', 'advanced', v_advanced_adjectives),
    ('a sharp decline', 'collocation', 'তীব্র পতন', 'a sudden and significant decrease', 'There was a sharp decline in exports following the tariff changes.', 'advanced', v_advanced_adjectives),
    ('showed little variation', 'collocation', 'সামান্য তারতম্য দেখিয়েছে', 'remained largely consistent with small changes', 'Rainfall showed little variation across the three years.', 'advanced', v_advanced_adjectives),
    ('climbed steadily', 'collocation', 'ধারাবাহিকভাবে বেড়েছে', 'increased at a consistent, moderate pace', 'The proportion of women in the workforce climbed steadily.', 'advanced', v_advanced_adjectives),
    ('dropped off sharply', 'collocation', 'হঠাৎ কমে গেছে', 'decreased suddenly after a period of stability', 'Attendance dropped off sharply after the initial launch period.', 'advanced', v_advanced_adjectives),
    ('meticulous', 'adjective', 'অতি সূক্ষ্মভাবে খুঁটিনাটি লক্ষ্যকারী', 'showing great attention to detail (upgrade for "careful")', 'She is meticulous about checking every figure twice.', 'advanced', v_advanced_adjectives),
    ('unprecedented', 'adjective', 'অভূতপূর্ব', 'never having happened before (upgrade for "big")', 'The scale of the flooding was unprecedented.', 'advanced', v_advanced_adjectives),
    ('profound', 'adjective', 'গভীর/প্রবল', 'very great or intense (upgrade for "big/deep")', 'The policy has had a profound effect on rural livelihoods.', 'advanced', v_advanced_adjectives),
    ('substantial', 'adjective', 'যথেষ্ট পরিমাণ', 'considerable in amount (upgrade for "a lot of")', 'The company reported a substantial increase in revenue.', 'advanced', v_advanced_adjectives),
    ('pivotal', 'adjective', 'অতি গুরুত্বপূর্ণ (কেন্দ্রীয়)', 'of crucial importance (upgrade for "important")', 'That decision proved pivotal to the company''s success.', 'advanced', v_advanced_adjectives),
    ('detrimental', 'adjective', 'ক্ষতিকর', 'causing harm or damage (upgrade for "bad")', 'Excessive screen time can be detrimental to a child''s development.', 'advanced', v_advanced_adjectives),
    ('beneficial', 'adjective', 'উপকারী', 'producing good results (upgrade for "good")', 'Regular exercise is beneficial for both body and mind.', 'advanced', v_advanced_adjectives),
    ('versatile', 'adjective', 'বহুমুখী', 'able to adapt to many functions (upgrade for "flexible")', 'A versatile employee can move easily between different roles.', 'advanced', v_advanced_adjectives),
    ('resilient', 'adjective', 'সহনশীল/দৃঢ়', 'able to recover quickly from difficulty', 'Coastal communities have become remarkably resilient to flooding.', 'advanced', v_advanced_adjectives),
    ('inevitable', 'adjective', 'অনিবার্য', 'certain to happen and unable to be avoided', 'Given current trends, further price rises seem inevitable.', 'advanced', v_advanced_adjectives),
    ('controversial', 'adjective', 'বিতর্কিত', 'causing public disagreement (upgrade for "bad" opinion)', 'The proposal remains highly controversial among residents.', 'advanced', v_advanced_adjectives),
    ('staggering', 'adjective', 'বিস্ময়কর', 'astonishing, especially in size or degree', 'The cost overrun was, frankly, staggering.', 'advanced', v_advanced_adjectives),
    ('intricate', 'adjective', 'জটিল ও সূক্ষ্ম', 'very complicated or detailed (upgrade for "complicated")', 'The system involves an intricate network of regulations.', 'advanced', v_advanced_adjectives),
    ('scarce', 'adjective', 'অপ্রতুল', 'insufficient for the demand (upgrade for "not enough")', 'Affordable housing has become increasingly scarce.', 'advanced', v_advanced_adjectives),
    ('abundant', 'adjective', 'প্রচুর', 'existing in large quantities (upgrade for "a lot")', 'The region enjoys abundant natural resources.', 'advanced', v_advanced_adjectives),
    ('tangible', 'adjective', 'বাস্তব ও স্পষ্ট', 'clear and definite; able to be perceived (upgrade for "real")', 'The reforms have produced tangible benefits for small businesses.', 'advanced', v_advanced_adjectives),
    ('dubious', 'adjective', 'সন্দেহজনক', 'of doubtful quality or validity (upgrade for "not sure")', 'The claims about the product''s benefits seem rather dubious.', 'advanced', v_advanced_adjectives),
    ('exemplary', 'adjective', 'অনুকরণীয়', 'serving as a desirable model (upgrade for "very good")', 'The nurse''s dedication was described as exemplary.', 'advanced', v_advanced_adjectives),
    ('rampant', 'adjective', 'অনিয়ন্ত্রিতভাবে বিস্তৃত', 'widespread and uncontrolled (upgrade for "very common")', 'Corruption was rampant throughout the organisation.', 'advanced', v_advanced_adjectives),
    ('meagre', 'adjective', 'অপ্রতুল/সামান্য', 'small in quantity, inadequate (upgrade for "small")', 'Workers survived on a meagre wage that barely covered rent.', 'advanced', v_advanced_adjectives),
    ('arduous', 'adjective', 'কষ্টসাধ্য', 'involving great effort and difficulty (upgrade for "hard")', 'The climb was long and arduous, taking nearly ten hours.', 'advanced', v_advanced_adjectives),
    ('formidable', 'adjective', 'শক্তিশালী ও দুর্ধর্ষ', 'impressively strong or capable (upgrade for "strong")', 'The team faced a formidable opponent in the final.', 'advanced', v_advanced_adjectives),
    ('inherent', 'adjective', 'সহজাত', 'existing as a natural or basic part of something', 'There is an inherent risk in any new technology.', 'advanced', v_advanced_adjectives),
    ('volatile', 'adjective', 'অস্থিতিশীল', 'liable to change rapidly and unpredictably (upgrade for "unstable")', 'Currency markets have remained highly volatile this year.', 'advanced', v_advanced_adjectives),
    ('precarious', 'adjective', 'অনিশ্চিত/ঝুঁকিপূর্ণ', 'not securely held; likely to fail (upgrade for "risky")', 'Many gig workers live in a financially precarious situation.', 'advanced', v_advanced_adjectives),
    ('sustainable', 'adjective', 'টেকসই', 'able to be maintained without depleting resources', 'The city aims to build a more sustainable transport network.', 'advanced', v_advanced_adjectives),
    ('stringent', 'adjective', 'কঠোর', 'strict and demanding (upgrade for "strict")', 'The factory now follows far more stringent safety standards.', 'advanced', v_advanced_adjectives),
    ('lucrative', 'adjective', 'লাভজনক', 'producing a great deal of profit (upgrade for "profitable")', 'Tech remains one of the most lucrative fields for graduates.', 'advanced', v_advanced_adjectives),
    ('far-fetched', 'adjective', 'অবিশ্বাস্য', 'unlikely and difficult to believe', 'His explanation for the delay seemed a little far-fetched.', 'advanced', v_advanced_adjectives),
    ('plausible', 'adjective', 'যুক্তিসঙ্গত বলে মনে হয়', 'seeming reasonable or probable (upgrade for "possible")', 'There is a plausible explanation for the sudden change.', 'advanced', v_advanced_adjectives),
    ('counterproduc tive', 'adjective', 'বিপরীতফলদায়ী', 'having the opposite effect to what is intended', 'Cutting funding for prevention proved deeply counterproductive.', 'advanced', v_advanced_adjectives),
    ('pertinent', 'adjective', 'প্রাসঙ্গিক', 'relevant to the matter at hand (upgrade for "relevant")', 'The report raises several pertinent questions about safety.', 'advanced', v_advanced_adjectives),
    ('subjective', 'adjective', 'বিষয়ীগত (ব্যক্তিগত মতনির্ভর)', 'based on personal opinion rather than fact', 'Taste in art is, of course, entirely subjective.', 'advanced', v_advanced_adjectives),
    ('objective', 'adjective', 'বস্তুনিষ্ঠ', 'based on facts rather than feelings (upgrade for "fair")', 'An objective assessment requires setting personal bias aside.', 'advanced', v_advanced_adjectives),
    ('indispensable', 'adjective', 'অপরিহার্য', 'absolutely necessary (upgrade for "very important")', 'Reliable electricity has become indispensable to modern life.', 'advanced', v_advanced_adjectives),
    ('disproportiona te', 'adjective', 'অসামঞ্জস্যপূর্ণ', 'too large or small in relation to something else', 'The tax places a disproportionate burden on low-income families.', 'advanced', v_advanced_adjectives),
    ('compelling', 'adjective', 'প্ররোচনামূলক ও যুক্তিগ্রাহ্য', 'convincing and interesting (upgrade for "strong" argument)', 'The researchers presented a compelling case for reform.', 'advanced', v_advanced_adjectives),
    ('mundane', 'adjective', 'একঘেয়ে/নিরস', 'lacking interest or excitement (upgrade for "boring")', 'Automation has taken over many mundane, repetitive tasks.', 'advanced', v_advanced_adjectives),
    ('dwindling', 'adjective', 'ক্রমহ্রাসমান', 'diminishing gradually in size or amount', 'Fishing communities have struggled with dwindling stocks.', 'advanced', v_advanced_adjectives),
    ('contentious', 'adjective', 'বিতর্কিত', 'likely to cause disagreement (upgrade for "controversial")', 'Immigration remains a highly contentious political topic.', 'advanced', v_advanced_adverbs_of_degree),
    ('considerably', 'adverb', 'যথেষ্ট পরিমাণে', 'to a large extent (upgrade for "a lot")', 'Prices have risen considerably over the past year.', 'advanced', v_advanced_adverbs_of_degree),
    ('significantly', 'adverb', 'উল্লেখযোগ্যভাবে', 'in an important or notable way', 'The new policy has significantly reduced waiting times.', 'advanced', v_advanced_adverbs_of_degree),
    ('markedly', 'adverb', 'লক্ষণীয়ভাবে', 'noticeably, clearly', 'Attitudes have changed markedly over the past decade.', 'advanced', v_advanced_adverbs_of_degree),
    ('substantially', 'adverb', 'যথেষ্ট মাত্রায়', 'to a great or considerable extent', 'The budget has been substantially increased this year.', 'advanced', v_advanced_adverbs_of_degree),
    ('marginally', 'adverb', 'সামান্য মাত্রায়', 'by a very small amount', 'Sales improved only marginally despite the campaign.', 'advanced', v_advanced_adverbs_of_degree),
    ('increasingly', 'adverb', 'ক্রমবর্ধমানভাবে', 'more and more over time', 'Employers are increasingly demanding digital skills.', 'advanced', v_advanced_adverbs_of_degree),
    ('overwhelmingly', 'adverb', 'অত্যধিকভাবে', 'by a very large margin', 'Respondents overwhelmingly supported the new proposal.', 'advanced', v_advanced_adverbs_of_degree),
    ('inherently', 'adverb', 'স্বভাবতই', 'in a basic or permanent way', 'The process is inherently risky, regardless of precautions.', 'advanced', v_advanced_adverbs_of_degree),
    ('invariably', 'adverb', 'সর্বদাই', 'always, without exception', 'Meetings invariably run over the scheduled time.', 'advanced', v_advanced_adverbs_of_degree),
    ('profoundly', 'adverb', 'গভীরভাবে', 'very greatly, deeply', 'The experience profoundly changed her outlook on life.', 'advanced', v_advanced_adverbs_of_degree),
    ('notoriously', 'adverb', 'কুখ্যাতভাবে', 'in a way widely known for something negative', 'The exam is notoriously difficult to pass on the first attempt.', 'advanced', v_advanced_adverbs_of_degree),
    ('consistently', 'adverb', 'ধারাবাহিকভাবে', 'in a steady, reliable manner over time', 'The team has consistently delivered strong results.', 'advanced', v_advanced_adverbs_of_degree),
    ('relentlessly', 'adverb', 'অবিরামভাবে', 'without stopping or slowing down', 'Costs have risen relentlessly over the past three years.', 'advanced', v_advanced_adverbs_of_degree),
    ('remarkably', 'adverb', 'উল্লেখযোগ্যভাবে', 'in a way worthy of attention', 'The system has remained remarkably stable despite the crisis.', 'advanced', v_advanced_adverbs_of_degree),
    ('progressively', 'adverb', 'ক্রমান্বয়ে', 'gradually, in stages', 'The rules have become progressively stricter each year.', 'advanced', v_advanced_adverbs_of_degree),
    ('disproportiona tely', 'adverb', 'অসামঞ্জস্যপূর্ণভাবে', 'to an unfairly large or small extent', 'Low-income families are disproportionately affected by the tax.', 'advanced', v_advanced_adverbs_of_degree),
    ('fundamentally', 'adverb', 'মৌলিকভাবে', 'in a basic and important way', 'The two approaches are fundamentally different.', 'advanced', v_advanced_adverbs_of_degree),
    ('precisely', 'adverb', 'সুনির্দিষ্টভাবে', 'exactly, with accuracy', 'It is not precisely known how many people were affected.', 'advanced', v_advanced_adverbs_of_degree),
    ('strikingly', 'adverb', 'লক্ষণীয়ভাবে', 'in a way that attracts attention', 'The two policies are strikingly similar in effect.', 'advanced', v_advanced_adverbs_of_degree),
    ('virtually', 'adverb', 'প্রায়', 'almost entirely', 'The two products are virtually identical in price.', 'advanced', v_advanced_adverbs_of_degree),
    ('genuinely', 'adverb', 'প্রকৃতপক্ষে/আন্তরিকভাবে', 'truly, sincerely', 'She seemed genuinely surprised by the announcement.', 'advanced', v_advanced_adverbs_of_degree),
    ('exceedingly', 'adverb', 'অত্যন্ত', 'extremely (formal, upgrade for "very")', 'The project proved exceedingly difficult to complete on time.', 'advanced', v_advanced_adverbs_of_degree),
    ('gradually', 'adverb', 'ধীরে ধীরে', 'slowly, over a period of time', 'Trust between the two sides gradually improved.', 'advanced', v_advanced_adverbs_of_degree),
    ('drastically', 'adverb', 'তীব্রভাবে/আকস্মিকভাবে', 'suddenly and to a great degree', 'Spending has been drastically cut across every department.', 'advanced', v_advanced_adverbs_of_degree),
    ('decisively', 'adverb', 'সিদ্ধান্তমূলকভাবে', 'in a way that settles a matter clearly', 'The government acted decisively to prevent further losses.', 'advanced', v_advanced_adverbs_of_degree),
    ('alleviate', 'verb', 'লাঘব করা', 'to make a problem less severe', 'Subsidies help alleviate the financial burden on farmers.', 'advanced', v_academic_verbs),
    ('mitigate', 'verb', 'প্রশমিত করা', 'to reduce the severity of something', 'Better drainage systems can mitigate the risk of flooding.', 'advanced', v_academic_verbs),
    ('exacerbate', 'verb', 'আরও খারাপ করা', 'to make a problem worse', 'Poor policy choices have exacerbated the housing shortage.', 'advanced', v_academic_verbs),
    ('undermine', 'verb', 'দুর্বল করা', 'to weaken gradually', 'Corruption undermines public trust in institutions.', 'advanced', v_academic_verbs),
    ('enhance', 'verb', 'উন্নত করা', 'to improve the quality of something', 'Training programmes enhance employee productivity.', 'advanced', v_academic_verbs),
    ('facilitate', 'verb', 'সহজতর করা', 'to make a process easier', 'The new software facilitates faster communication between teams.', 'advanced', v_academic_verbs),
    ('foster', 'verb', 'বিকাশে সহায়তা করা', 'to encourage the development of something', 'Group projects help foster teamwork skills.', 'advanced', v_academic_verbs),
    ('hinder', 'verb', 'বাধা দেওয়া', 'to make progress difficult', 'A lack of funding continues to hinder scientific research.', 'advanced', v_academic_verbs),
    ('implement', 'verb', 'বাস্তবায়ন করা', 'to put a plan or policy into effect', 'The council plans to implement the new regulations next year.', 'advanced', v_academic_verbs),
    ('advocate', 'verb', 'সমর্থন করা (প্রকাশ্যে)', 'to publicly support an idea', 'Health experts advocate for stricter regulation of sugar content.', 'advanced', v_academic_verbs),
    ('underscore', 'verb', 'গুরুত্ব তুলে ধরা', 'to emphasise the importance of something', 'The report underscores the need for urgent reform.', 'advanced', v_academic_verbs),
    ('warrant', 'verb', 'যুক্তিসঙ্গত করা', 'to justify or make necessary', 'The scale of the problem warrants immediate government action.', 'advanced', v_academic_verbs),
    ('stem from', null, 'উদ্ভূত হওয়া', 'to originate from', 'Many of these issues stem from inadequate early investment.', 'advanced', v_academic_verbs),
    ('encompass', 'verb', 'অন্তর্ভুক্ত করা', 'to include a wide range of things', 'The reform encompasses changes to both funding and curriculum.', 'advanced', v_academic_verbs),
    ('constitute', 'verb', 'গঠন করা', 'to form or make up a part of something', 'Young people constitute nearly a third of the total population.', 'advanced', v_academic_verbs),
    ('cultivate', 'verb', 'লালন-পালন করা', 'to develop or nurture over time', 'Schools should cultivate curiosity rather than mere memorisation.', 'advanced', v_academic_verbs),
    ('curb', 'verb', 'নিয়ন্ত্রণে আনা', 'to restrain or bring under control', 'New taxes aim to curb consumption of sugary drinks.', 'advanced', v_academic_verbs),
    ('deter', 'verb', 'নিরুৎসাহিত করা', 'to discourage someone from doing something', 'Higher fines are intended to deter reckless driving.', 'advanced', v_academic_verbs),
    ('disseminate', 'verb', 'ব্যাপকভাবে ছড়িয়ে দেওয়া', 'to spread information widely', 'The organisation works to disseminate accurate health information.', 'advanced', v_academic_verbs),
    ('exemplify', 'verb', 'উদাহরণস্বরূপ প্রতিনিধিত্ব করা', 'to serve as a typical example of', 'The case exemplifies a broader trend across the industry.', 'advanced', v_academic_verbs),
    ('incentivise', 'verb', 'পুরস্কারের মাধ্যমে উৎসাহিত করা', 'to motivate through rewards', 'Tax breaks can incentivise businesses to invest in renewables.', 'advanced', v_academic_verbs),
    ('jeopardise', 'verb', 'বিপদগ্রস্ত করা', 'to put something at risk of harm', 'Cutting corners on safety could jeopardise the entire project.', 'advanced', v_academic_verbs),
    ('mandate', 'verb', 'বাধ্যতামূলক করা', 'to officially require something', 'The law mandates regular safety inspections for all factories.', 'advanced', v_academic_verbs),
    ('necessitate', 'verb', 'অপরিহার্য করে তোলা', 'to make something necessary', 'The rapid growth necessitates further investment in infrastructure.', 'advanced', v_academic_verbs),
    ('optimise', 'verb', 'সর্বোত্তম করা', 'to make the best or most effective use of something', 'The system was redesigned to optimise energy consumption.', 'advanced', v_academic_verbs),
    ('perpetuate', 'verb', 'স্থায়ী করে রাখা', 'to make a situation continue indefinitely', 'Such policies risk perpetuating existing inequalities.', 'advanced', v_academic_verbs),
    ('prioritise', 'verb', 'অগ্রাধিকার দেওয়া', 'to treat something as more important', 'Governments must prioritise public health during a crisis.', 'advanced', v_academic_verbs),
    ('propel', 'verb', 'সামনের দিকে ঠেলে দেওয়া', 'to drive forward, often quickly', 'Innovation has propelled the company to market leadership.', 'advanced', v_academic_verbs),
    ('rectify', 'verb', 'সংশোধন করা', 'to correct a mistake or problem', 'Steps are being taken to rectify the imbalance.', 'advanced', v_academic_verbs),
    ('reinforce', 'verb', 'শক্তিশালী করা', 'to strengthen or support further', 'The findings reinforce earlier research on the topic.', 'advanced', v_academic_verbs),
    ('revitalise', 'verb', 'পুনরুজ্জীবিত করা', 'to give new energy or strength to something', 'The investment aims to revitalise the struggling town centre.', 'advanced', v_academic_verbs),
    ('safeguard', 'verb', 'রক্ষা করা', 'to protect from harm or damage', 'New rules aim to safeguard consumers from unfair practices.', 'advanced', v_academic_verbs),
    ('streamline', 'verb', 'সহজতর ও কার্যকর করা', 'to make a process simpler and more efficient', 'The reforms streamline the process of registering a business.', 'advanced', v_academic_verbs),
    ('substantiate', 'verb', 'প্রমাণ দিয়ে সমর্থন করা', 'to provide evidence to support a claim', 'The report fails to substantiate its central claim.', 'advanced', v_academic_verbs),
    ('transcend', 'verb', 'অতিক্রম করা', 'to go beyond the limits of something', 'The problem transcends national borders and requires global cooperation.', 'advanced', v_academic_verbs),
    ('undertake', 'verb', 'দায়িত্ব নেওয়া (কাজ শুরু করা)', 'to commit to and begin a task', 'The team will undertake a full review of the current system.', 'advanced', v_academic_verbs),
    ('validate', 'verb', 'সত্যতা যাচাই করা', 'to confirm the accuracy or worth of something', 'Further studies are needed to validate these initial findings.', 'advanced', v_academic_verbs),
    ('yield', 'verb', 'ফলাফল দেওয়া', 'to produce a result', 'The new approach has yielded encouraging early results.', 'advanced', v_academic_verbs),
    ('allocate', 'verb', 'বরাদ্দ করা', 'to distribute for a specific purpose', 'More funds should be allocated to public transport.', 'advanced', v_academic_verbs),
    ('attribute to', null, 'কারণ হিসেবে চিহ্নিত করা', 'to identify as the cause of something', 'Experts attribute the decline to changing consumer habits.', 'advanced', v_academic_verbs),
    ('compensate for', null, 'ঘাটতি পূরণ করা', 'to make up for a deficiency', 'Higher wages partly compensate for the demanding nature of the job.', 'advanced', v_academic_verbs),
    ('counteract', 'verb', 'প্রতিহত করা', 'to reduce or neutralise the effect of something', 'Regular exercise can help counteract the effects of a desk job.', 'advanced', v_academic_verbs),
    ('dictate', 'verb', 'নির্ধারণ/নিয়ন্ত্রণ করা', 'to control or determine', 'Market conditions largely dictate pricing decisions.', 'advanced', v_academic_verbs),
    ('epitomise', 'verb', 'নিখুঁত উদাহরণ হওয়া', 'to be a perfect example of something', 'The project epitomises what community-led development can achieve.', 'advanced', v_academic_verbs),
    ('instil', 'verb', 'ধীরে ধীরে গেঁথে দেওয়া', 'to gradually establish a feeling or idea in someone', 'Good teachers instil a lifelong love of learning.', 'advanced', v_academic_verbs);
end $$;
